// <auto-generated>
//   Generated by tools/component-packets/generate_seam_catalog.py from the
//   FastSignals projection in quest-capability-rules.json. Do not edit.
// </auto-generated>

namespace ComfyQuestContracts;

using System;
using System.Collections.Generic;

/// <summary>The intentionally small, live-backed signal lane used by Quest Studio.</summary>
public static class CreatorSignalCatalog {
  public readonly struct Definition {
    public string Id { get; }
    public string EventName { get; }
    public string Label { get; }
    public string Instruction { get; }
    public string Target { get; }
    public string TargetPolicy { get; }
    public string Privacy { get; }
    public string LabProfile { get; }
    public string LabRoute { get; }
    public string RuntimeAdapter { get; }

    public Definition(string id, string eventName, string label, string instruction,
        string target, string targetPolicy, string privacy, string labProfile,
        string labRoute, string runtimeAdapter) {
      Id = id; EventName = eventName; Label = label; Instruction = instruction;
      Target = target; TargetPolicy = targetPolicy; Privacy = privacy;
      LabProfile = labProfile; LabRoute = labRoute; RuntimeAdapter = runtimeAdapter;
    }
  }

  static readonly Definition[] _all = new[] {
    new Definition("say", "chat_sent", "Say something", "Say something in normal chat.", "normal", "fixed", "Message text is never persisted.", "core", "primary", "RuntimeEasyEventPatches.ChatSent"),
    new Definition("shout", "chat_sent", "Shout", "Shout in chat.", "shout", "fixed", "Message text is never persisted.", "core", "primary", "RuntimeEasyEventPatches.ChatSent"),
    new Definition("drop", "item_dropped", "Drop something", "Drop any item from your inventory.", null, "wildcard", "Only the stable item prefab is retained.", "core", "primary", "RuntimeEasyEventPatches.ItemDropped"),
    new Definition("pickup", "item_picked_up", "Pick something up", "Pick up any item from the ground.", null, "wildcard", "Only the stable item prefab is retained.", "core", "primary", "RuntimeEasyEventPatches.ItemPickedUp"),
    new Definition("equip", "item_equipped", "Equip something", "Equip any tool, weapon, shield, or armor item.", null, "wildcard", "Only the stable item prefab is retained.", "core", "primary", "RuntimeEasyEventPatches.ItemEquipped"),
    new Definition("consume", "item_consumed", "Consume something", "Consume any food, mead, or usable item.", null, "wildcard", "Only the stable item prefab is retained.", "core", "primary", "RuntimeEasyEventPatches.ItemConsumed"),
    new Definition("heal", "character_healed", "Regain health", "Regain any amount of health.", null, "wildcard", "The healing amount is not persisted.", "core", "primary", "RuntimeEasyEventPatches.CharacterHealed"),
    new Definition("wait", "timer_elapsed", "Wait", "Wait for the quest timer.", null, "engine", "No player payload is captured.", "engine", "engine", "DurableTimerStore"),
  };

  public static IReadOnlyList<Definition> All { get { return _all; } }

  public static bool TryGet(string id, out Definition definition) {
    foreach (Definition candidate in _all) {
      if (string.Equals(candidate.Id, id, StringComparison.Ordinal)) {
        definition = candidate; return true;
      }
    }
    definition = default(Definition); return false;
  }

  public static bool TryDescribe(string eventName, string target, out Definition definition) {
    foreach (Definition candidate in _all) {
      if (!string.Equals(candidate.EventName, eventName, StringComparison.OrdinalIgnoreCase)) continue;
      if (candidate.Target != null
          && !string.Equals(candidate.Target, target, StringComparison.OrdinalIgnoreCase)) continue;
      definition = candidate; return true;
    }
    definition = default(Definition); return false;
  }
}
