// <auto-generated>
//   Generated by tools/component-packets/generate_seam_catalog.py. Do not edit.
// </auto-generated>

namespace ComfyQuestContracts;

using System;
using System.Collections.Generic;

/// <summary>Exact creator-safe assembly witnesses; availability is explicit per signature.</summary>
public static class RuntimeWitnessCatalog {
  public readonly struct Definition {
    public string SignatureId { get; } public string MethodId { get; } public string EventName { get; }
    public string Route { get; } public string Profile { get; } public string DedupeGroup { get; } public string ActorScope { get; }
    public bool ProductionAvailable { get; }
    public Definition(string signatureId,string methodId,string eventName,string route,string profile,string dedupeGroup,string actorScope,bool productionAvailable){
      SignatureId=signatureId;MethodId=methodId;EventName=eventName;Route=route;Profile=profile;DedupeGroup=dedupeGroup;ActorScope=actorScope;ProductionAvailable=productionAvailable;
    }
  }
  static readonly Definition[] _all=new[] {
    new Definition("Character.Damage(HitData)", "Character.Damage", "damage_dealt", "primary", "extended", "character-damage", "local-player-caused", true),
    new Definition("Character.Heal(float, bool)", "Character.Heal", "character_healed", "primary", "core", "character-healed", "local-player", true),
    new Definition("Character.OnDeath()", "Character.OnDeath", "kill", "primary", "core", "creature-killed", "local-player-caused", true),
    new Definition("Character.RPC_Damage(long, HitData)", "Character.RPC_Damage", "damage_dealt", "alternate", "extended", "character-damage", "local-player-caused", true),
    new Definition("Character.RPC_Heal(long, float, bool)", "Character.RPC_Heal", "character_healed", "alternate", "core", "character-healed", "local-player", true),
    new Definition("Character.RPC_Stagger(long, Vector3)", "Character.RPC_Stagger", "character_staggered", "alternate", "core", "character-staggered", "local-player-caused", true),
    new Definition("Character.Stagger(Vector3)", "Character.Stagger", "character_staggered", "primary", "core", "character-staggered", "local-player-caused", true),
    new Definition("Chat.SendText(Type, string)", "Chat.SendText", "chat_sent", "primary", "core", "chat-sent", "local-player", true),
    new Definition("Container.TakeAll(Humanoid)", "Container.TakeAll", "container_emptied", "primary", "core", "container-take-all", "local-player", true),
    new Definition("CookingStation.RPC_AddFuel(long)", "CookingStation.RPC_AddFuel", "station_fuel_added", "primary", "core", "cooking-fuel-added", "local-player-caused", true),
    new Definition("CookingStation.RPC_AddItem(long, string)", "CookingStation.RPC_AddItem", "station_input_added", "primary", "core", "cooking-input-added", "local-player-caused", true),
    new Definition("CookingStation.RPC_RemoveDoneItem(long, Vector3, int)", "CookingStation.RPC_RemoveDoneItem", "station_output_collected", "primary", "core", "cooking-output-collected", "local-player-caused", true),
    new Definition("Destructible.Damage(HitData)", "Destructible.Damage", "resource_damaged", "primary", "extended", "resource-damage", "local-player-caused", true),
    new Definition("Destructible.RPC_Damage(long, HitData)", "Destructible.RPC_Damage", "resource_damaged", "alternate", "extended", "resource-damage", "local-player-caused", true),
    new Definition("Fermenter.RPC_AddItem(long, string)", "Fermenter.RPC_AddItem", "station_input_added", "primary", "core", "fermenter-input-added", "local-player-caused", true),
    new Definition("Humanoid.BlockAttack(HitData, Character)", "Humanoid.BlockAttack", "attack_blocked", "primary", "core", "attack-blocked", "local-player", true),
    new Definition("Humanoid.DropItem(Inventory, ItemData, int)", "Humanoid.DropItem", "item_dropped", "primary", "core", "item-dropped", "local-player", true),
    new Definition("Humanoid.EquipItem(ItemData, bool)", "Humanoid.EquipItem", "item_equipped", "primary", "core", "item-equipped", "local-player", true),
    new Definition("Humanoid.Pickup(GameObject, bool, bool)", "Humanoid.Pickup", "item_picked_up", "primary", "core", "item-picked-up", "local-player", true),
    new Definition("Humanoid.UnequipItem(ItemData, bool)", "Humanoid.UnequipItem", "item_unequipped", "primary", "core", "item-unequipped", "local-player", true),
    new Definition("InventoryGui.DoCrafting(Player)", "InventoryGui.DoCrafting", "item_crafted", "primary", "core", "item-crafted", "local-player", true),
    new Definition("MineRock.Damage(HitData)", "MineRock.Damage", "resource_damaged", "primary", "extended", "resource-damage", "local-player-caused", true),
    new Definition("MineRock5.Damage(HitData)", "MineRock5.Damage", "resource_damaged", "primary", "extended", "resource-damage", "local-player-caused", true),
    new Definition("MineRock5.RPC_Damage(long, HitData, int)", "MineRock5.RPC_Damage", "resource_damaged", "alternate", "extended", "resource-damage", "local-player-caused", true),
    new Definition("Pickable.Interact(Humanoid, bool, bool)", "Pickable.Interact", "resource_picked", "primary", "core", "resource-picked", "local-player", true),
    new Definition("Pickable.RPC_Pick(long, int)", "Pickable.RPC_Pick", "resource_picked", "alternate", "core", "resource-picked", "local-player", true),
    new Definition("Player.AddStamina(float)", "Player.AddStamina", "stamina_gained", "primary", "extended", "stamina-gained", "local-player", false),
    new Definition("Player.ConsumeItem(Inventory, ItemData, bool)", "Player.ConsumeItem", "item_consumed", "primary", "core", "item-consumed", "local-player", true),
    new Definition("Player.OnDeath()", "Player.OnDeath", "player_died", "primary", "core", "player-died", "local-player", false),
    new Definition("Player.PlacePiece(Piece, Vector3, Quaternion, bool)", "Player.PlacePiece", "piece_placed", "primary", "core", "piece-placed", "local-player", true),
    new Definition("Player.RaiseSkill(SkillType, float)", "Player.RaiseSkill", "skill_raised", "primary", "core", "skill-raised", "local-player", false),
    new Definition("Player.RemovePiece()", "Player.RemovePiece", "piece_removed", "primary", "core", "piece-removed", "local-player", true),
    new Definition("Player.Repair(ItemData, Piece)", "Player.Repair", "piece_repaired", "primary", "core", "piece-repaired", "local-player", true),
    new Definition("Player.SetMaxHealth(float, bool)", "Player.SetMaxHealth", "max_health_changed", "primary", "extended", "max-health-changed", "local-player", false),
    new Definition("Player.TeleportTo(Vector3, Quaternion, bool)", "Player.TeleportTo", "player_teleported", "primary", "core", "player-teleported", "local-player", true),
    new Definition("Player.UseStamina(float)", "Player.UseStamina", "stamina_spent", "primary", "extended", "stamina-spent", "local-player", false),
    new Definition("Sign.SetText(string)", "Sign.SetText", "sign_written", "primary", "core", "sign-written", "local-player", true),
    new Definition("Skills.LowerAllSkills(float)", "Skills.LowerAllSkills", "skills_lowered", "primary", "core", "skills-lowered", "local-player", false),
    new Definition("Smelter.OnAddFuel(Switch, Humanoid, ItemData)", "Smelter.OnAddFuel", "station_fuel_added", "primary", "core", "smelter-fuel-added", "local-player", true),
    new Definition("Smelter.OnAddOre(Switch, Humanoid, ItemData)", "Smelter.OnAddOre", "station_input_added", "primary", "core", "smelter-input-added", "local-player", true),
    new Definition("Smelter.RPC_AddFuel(long)", "Smelter.RPC_AddFuel", "station_fuel_added", "alternate", "core", "smelter-fuel-added", "local-player-caused", true),
    new Definition("Smelter.RPC_AddOre(long, string)", "Smelter.RPC_AddOre", "station_input_added", "alternate", "core", "smelter-input-added", "local-player-caused", true),
    new Definition("Smelter.Spawn(string, int)", "Smelter.Spawn", "station_output_produced", "primary", "core", "station-output-produced", "observed-world", true),
    new Definition("TreeBase.Damage(HitData)", "TreeBase.Damage", "resource_damaged", "primary", "extended", "resource-damage", "local-player-caused", true),
    new Definition("TreeBase.RPC_Damage(long, HitData)", "TreeBase.RPC_Damage", "resource_damaged", "alternate", "extended", "resource-damage", "local-player-caused", true),
    new Definition("TreeLog.Damage(HitData)", "TreeLog.Damage", "resource_damaged", "primary", "extended", "resource-damage", "local-player-caused", true),
    new Definition("TreeLog.RPC_Damage(long, HitData)", "TreeLog.RPC_Damage", "resource_damaged", "alternate", "extended", "resource-damage", "local-player-caused", true),
    new Definition("WearNTear.ApplyDamage(float, HitData)", "WearNTear.ApplyDamage", "piece_damaged", "primary", "extended", "piece-damaged", "local-player-caused", true),
    new Definition("WearNTear.Destroy(HitData, bool)", "WearNTear.Destroy", "piece_destroyed", "primary", "core", "piece-destroyed", "local-player-caused", true),
    new Definition("WearNTear.RPC_Remove(long, bool)", "WearNTear.RPC_Remove", "piece_removed", "alternate", "core", "piece-removed", "local-player-caused", true),
    new Definition("WearNTear.RPC_Repair(long)", "WearNTear.RPC_Repair", "piece_repaired", "alternate", "core", "piece-repaired", "local-player-caused", true),
    new Definition("ZoneSystem.RPC_SetGlobalKey(long, string)", "ZoneSystem.RPC_SetGlobalKey", "global_key_set", "alternate", "core", "global-key-set", "world-authority", false),
    new Definition("ZoneSystem.RemoveGlobalKey(GlobalKeys)", "ZoneSystem.RemoveGlobalKey", "global_key_removed", "primary", "core", "global-key-removed", "world-authority", false),
    new Definition("ZoneSystem.RemoveGlobalKey(string)", "ZoneSystem.RemoveGlobalKey", "global_key_removed", "primary", "core", "global-key-removed", "world-authority", false),
    new Definition("ZoneSystem.SetGlobalKey(GlobalKeys)", "ZoneSystem.SetGlobalKey", "global_key_set", "primary", "core", "global-key-set", "world-authority", false),
    new Definition("ZoneSystem.SetGlobalKey(GlobalKeys, float)", "ZoneSystem.SetGlobalKey", "global_key_set", "primary", "core", "global-key-set", "world-authority", false),
    new Definition("ZoneSystem.SetGlobalKey(string)", "ZoneSystem.SetGlobalKey", "global_key_set", "primary", "core", "global-key-set", "world-authority", false),
  };
  static readonly Dictionary<string,Definition> _bySignature=Build();
  static Dictionary<string,Definition> Build(){var result=new Dictionary<string,Definition>(StringComparer.Ordinal);foreach(var item in _all)result[item.SignatureId]=item;return result;}
  public static IReadOnlyList<Definition> All { get { return _all; } }
  public static int Count { get { return _all.Length; } }
  public static bool TryGet(string signatureId,out Definition definition){if(signatureId!=null&&_bySignature.TryGetValue(signatureId,out definition))return true;definition=default(Definition);return false;}
}
