// <auto-generated>
//   Generated by tools/component-packets/generate_seam_catalog.py. Do not edit.
// </auto-generated>

namespace ComfyQuestContracts;

using System;
using System.Collections.Generic;

/// <summary>Fail-closed Runtime event registry; synthetic-only creator meanings are absent.</summary>
public static class RuntimeProductionEventCatalog {
  public readonly struct Definition {
    public string Name { get; } public string RuntimeAdapter { get; }
    public string EvidenceState { get; } public string EvidenceRevision { get; }
    public string TargetPolicy { get; } public string FixedTarget { get; } public IReadOnlyList<string> AllowedTargets { get; } public bool EmitsWeaponSkill { get; } public bool EmitsProjectile { get; }
    public IReadOnlyList<string> AllowedWhereFields { get; } public IReadOnlyDictionary<string,string> FixedWhere { get; } public IReadOnlyList<string> WitnessSignatures { get; }
    public Definition(string name,string runtimeAdapter,string evidenceState,string evidenceRevision,string targetPolicy,string fixedTarget,string[] allowedTargets,
        bool emitsWeaponSkill,bool emitsProjectile,string[] allowedWhereFields,Dictionary<string,string> fixedWhere,string[] witnessSignatures) {
      Name=name; RuntimeAdapter=runtimeAdapter; EvidenceState=evidenceState; EvidenceRevision=evidenceRevision;
      TargetPolicy=targetPolicy; FixedTarget=fixedTarget; AllowedTargets=allowedTargets??new string[0]; EmitsWeaponSkill=emitsWeaponSkill; EmitsProjectile=emitsProjectile;
      AllowedWhereFields=allowedWhereFields??new string[0]; FixedWhere=fixedWhere??new Dictionary<string,string>(); WitnessSignatures=witnessSignatures??new string[0];
    }
  }
  public readonly struct EngineDefinition {
    public string Name { get; } public string Label { get; } public string Instruction { get; }
    public string RuntimeAdapter { get; } public string TargetPolicy { get; } public string FixedTarget { get; } public IReadOnlyList<string> AllowedTargets { get; } public IReadOnlyList<string> RequiredWhereFields { get; }
    public IReadOnlyList<string> AllowedWhereFields { get; } public string Privacy { get; }
    public EngineDefinition(string name,string label,string instruction,string runtimeAdapter,string targetPolicy,string fixedTarget,string[] allowedTargets,string[] required,string[] allowed,string privacy) {
      Name=name; Label=label; Instruction=instruction; RuntimeAdapter=runtimeAdapter; TargetPolicy=targetPolicy; FixedTarget=fixedTarget; AllowedTargets=allowedTargets??new string[0]; RequiredWhereFields=required; AllowedWhereFields=allowed; Privacy=privacy;
    }
  }
  static readonly Definition[] _all = new[] {
    new Definition("attack_blocked", "RuntimeKillPatches.AttackBlocked", "automated-contract", null, "optional", null, new string[0], true, true, new[] { "weapon_skill", "projectile" }, new Dictionary<string,string>(), new[] { "Humanoid.BlockAttack(HitData, Character)" }),
    new Definition("chat_sent", "RuntimeEasyEventPatches.ChatSent", "automated-contract", null, "closed", null, new[] { "normal", "shout" }, false, false, new string[0], new Dictionary<string,string>(), new[] { "Chat.SendText(Type, string)" }),
    new Definition("container_emptied", "RuntimeCoreActionPatches.ContainerEmptied", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Container.TakeAll(Humanoid)" }),
    new Definition("item_crafted", "RuntimeCraftingPatches.ItemCrafted", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "InventoryGui.DoCrafting(Player)" }),
    new Definition("item_dropped", "RuntimeEasyEventPatches.ItemDropped", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Humanoid.DropItem(Inventory, ItemData, int)" }),
    new Definition("item_picked_up", "RuntimeEasyEventPatches.ItemPickedUp", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Humanoid.Pickup(GameObject, bool, bool)" }),
    new Definition("item_equipped", "RuntimeEasyEventPatches.ItemEquipped", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Humanoid.EquipItem(ItemData, bool)" }),
    new Definition("item_unequipped", "RuntimeCoreActionPatches.ItemUnequipped", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Humanoid.UnequipItem(ItemData, bool)" }),
    new Definition("item_consumed", "RuntimeEasyEventPatches.ItemConsumed", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Player.ConsumeItem(Inventory, ItemData, bool)" }),
    new Definition("character_healed", "RuntimeEasyEventPatches.CharacterHealed", "automated-contract", null, "fixed-output", "you", new string[0], false, false, new[] { "amount" }, new Dictionary<string,string>(), new[] { "Character.Heal(float, bool)", "Character.RPC_Heal(long, float, bool)" }),
    new Definition("character_staggered", "RuntimeKillPatches.CharacterStaggered", "automated-contract", null, "optional", null, new string[0], true, true, new[] { "weapon_skill", "projectile" }, new Dictionary<string,string>(), new[] { "Character.RPC_Stagger(long, Vector3)", "Character.Stagger(Vector3)" }),
    new Definition("damage_dealt", "RuntimeKillPatches.DamageDealt", "automated-contract", null, "optional", null, new string[0], true, true, new[] { "weapon_skill", "projectile" }, new Dictionary<string,string>(), new[] { "Character.Damage(HitData)", "Character.RPC_Damage(long, HitData)" }),
    new Definition("kill", "RuntimeKillPatches.Death", "automated-contract", null, "optional", null, new string[0], true, true, new[] { "weapon_skill", "projectile" }, new Dictionary<string,string>(), new[] { "Character.OnDeath()" }),
    new Definition("piece_damaged", "RuntimeKillPatches.PieceDamage", "automated-contract", null, "optional", null, new string[0], true, true, new[] { "weapon_skill", "projectile" }, new Dictionary<string,string>(), new[] { "WearNTear.ApplyDamage(float, HitData)" }),
    new Definition("piece_destroyed", "RuntimeCoreActionPatches.PieceDestroyed", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "WearNTear.Destroy(HitData, bool)" }),
    new Definition("piece_placed", "RuntimeCooperativePatches.PlacePiece", "automated-contract", null, "optional", null, new string[0], false, false, new[] { "actor_role" }, new Dictionary<string,string> { { "actor_role", "listen_host" } }, new[] { "Player.PlacePiece(Piece, Vector3, Quaternion, bool)" }),
    new Definition("piece_removed", "RuntimeCoreActionPatches.PieceRemoved", "automated-contract", null, "fixed-output", "piece", new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Player.RemovePiece()", "WearNTear.RPC_Remove(long, bool)" }),
    new Definition("piece_repaired", "RuntimeCoreActionPatches.PieceRepaired", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Player.Repair(ItemData, Piece)", "WearNTear.RPC_Repair(long)" }),
    new Definition("player_teleported", "RuntimeCoreActionPatches.PlayerTeleported", "automated-contract", null, "none", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Player.TeleportTo(Vector3, Quaternion, bool)" }),
    new Definition("global_key_removed", "RuntimeWorldStatePatches.RemoveString", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "ZoneSystem.RemoveGlobalKey(GlobalKeys)", "ZoneSystem.RemoveGlobalKey(string)" }),
    new Definition("global_key_set", "RuntimeWorldStatePatches.SetString", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "ZoneSystem.RPC_SetGlobalKey(long, string)", "ZoneSystem.SetGlobalKey(GlobalKeys)", "ZoneSystem.SetGlobalKey(GlobalKeys, float)", "ZoneSystem.SetGlobalKey(string)" }),
    new Definition("max_health_changed", "RuntimeProgressionPatches.MaxHealthChanged", "automated-contract", null, "fixed-output", "health", new string[0], false, false, new[] { "subject", "amount" }, new Dictionary<string,string> { { "subject", "health" } }, new[] { "Player.SetMaxHealth(float, bool)" }),
    new Definition("player_died", "RuntimeProgressionPatches.PlayerDied", "automated-contract", null, "fixed-output", "you", new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Player.OnDeath()" }),
    new Definition("skill_raised", "RuntimeProgressionPatches.SkillRaised", "automated-contract", null, "optional", null, new string[0], false, false, new[] { "subject", "amount" }, new Dictionary<string,string>(), new[] { "Player.RaiseSkill(SkillType, float)" }),
    new Definition("skills_lowered", "RuntimeProgressionPatches.SkillsLowered", "automated-contract", null, "fixed-output", "all skills", new string[0], false, false, new[] { "subject", "amount" }, new Dictionary<string,string> { { "subject", "all" } }, new[] { "Skills.LowerAllSkills(float)" }),
    new Definition("stamina_gained", "RuntimeProgressionPatches.StaminaGained", "automated-contract", null, "fixed-output", "stamina", new string[0], false, false, new[] { "subject", "amount" }, new Dictionary<string,string> { { "subject", "stamina" } }, new[] { "Player.AddStamina(float)" }),
    new Definition("stamina_spent", "RuntimeProgressionPatches.StaminaSpent", "automated-contract", null, "fixed-output", "stamina", new string[0], false, false, new[] { "subject", "amount" }, new Dictionary<string,string> { { "subject", "stamina" } }, new[] { "Player.UseStamina(float)" }),
    new Definition("resource_damaged", "RuntimeHarvestPatches.ResourceDamaged", "automated-contract", null, "optional", null, new string[0], true, true, new[] { "weapon_skill", "projectile" }, new Dictionary<string,string>(), new[] { "Destructible.Damage(HitData)", "Destructible.RPC_Damage(long, HitData)", "MineRock.Damage(HitData)", "MineRock5.Damage(HitData)", "MineRock5.RPC_Damage(long, HitData, int)", "TreeBase.Damage(HitData)", "TreeBase.RPC_Damage(long, HitData)", "TreeLog.Damage(HitData)", "TreeLog.RPC_Damage(long, HitData)" }),
    new Definition("resource_picked", "RuntimeHarvestPatches.ResourcePicked", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Pickable.Interact(Humanoid, bool, bool)", "Pickable.RPC_Pick(long, int)" }),
    new Definition("station_fuel_added", "RuntimeCraftingPatches.StationFuelAdded", "automated-contract", null, "optional", null, new string[0], false, false, new[] { "station", "item", "quantity" }, new Dictionary<string,string>(), new[] { "CookingStation.RPC_AddFuel(long)", "Smelter.OnAddFuel(Switch, Humanoid, ItemData)", "Smelter.RPC_AddFuel(long)" }),
    new Definition("station_input_added", "RuntimeCraftingPatches.StationInputAdded", "automated-contract", null, "optional", null, new string[0], false, false, new[] { "station", "item", "quantity" }, new Dictionary<string,string>(), new[] { "CookingStation.RPC_AddItem(long, string)", "Fermenter.RPC_AddItem(long, string)", "Smelter.OnAddOre(Switch, Humanoid, ItemData)", "Smelter.RPC_AddOre(long, string)" }),
    new Definition("station_output_collected", "RuntimeCraftingPatches.StationOutputCollected", "automated-contract", null, "optional", null, new string[0], false, false, new[] { "station", "item", "quantity" }, new Dictionary<string,string>(), new[] { "CookingStation.RPC_RemoveDoneItem(long, Vector3, int)" }),
    new Definition("station_output_produced", "RuntimeCraftingPatches.StationOutputProduced", "automated-contract", null, "optional", null, new string[0], false, false, new[] { "station", "item", "quantity" }, new Dictionary<string,string>(), new[] { "Smelter.Spawn(string, int)" }),
    new Definition("sign_written", "RuntimeKillPatches.SignWritten", "automated-contract", null, "optional", null, new string[0], false, false, new string[0], new Dictionary<string,string>(), new[] { "Sign.SetText(string)" }),
  };
  static readonly EngineDefinition[] _engine = new[] {
    new EngineDefinition("timer_elapsed", "Timer elapsed", "Wait for a named quest timer.", "DurableTimerStore", "none", null, new string[0], new[] { "timer_id" }, new[] { "timer_id" }, "Only the quest-owned timer identifier is retained."),
    new EngineDefinition("chat_received", "Receive chat", "Receive a non-empty normal or shout message from a selected actor role.", "RuntimeCooperativePatches.EmitChat", "closed", null, new[] { "normal", "shout" }, new[] { "actor_role" }, new[] { "actor_role" }, "Message text, sender identity, and player name are never persisted."),
  };
  static readonly Dictionary<string, Definition> _byName=Build();
  static readonly Dictionary<string, EngineDefinition> _engineByName=BuildEngine();
  static Dictionary<string, Definition> Build(){var value=new Dictionary<string, Definition>(StringComparer.OrdinalIgnoreCase);foreach(var item in _all)value[item.Name]=item;return value;}
  static Dictionary<string, EngineDefinition> BuildEngine(){var value=new Dictionary<string, EngineDefinition>(StringComparer.OrdinalIgnoreCase);foreach(var item in _engine)value[item.Name]=item;return value;}
  public static IReadOnlyList<Definition> All { get { return _all; } }
  public static IReadOnlyList<EngineDefinition> EngineEvents { get { return _engine; } }
  public static int Count { get { return _all.Length; } }
  public static bool Contains(string name){return !string.IsNullOrWhiteSpace(name)&&_byName.ContainsKey(name);}
  public static bool IsEngineEvent(string name){return !string.IsNullOrWhiteSpace(name)&&_engineByName.ContainsKey(name);}
  public static bool TryGet(string name,out Definition definition){if(!string.IsNullOrWhiteSpace(name)&&_byName.TryGetValue(name,out definition))return true;definition=default(Definition);return false;}
  public static bool TryGetEngine(string name,out EngineDefinition definition){if(!string.IsNullOrWhiteSpace(name)&&_engineByName.TryGetValue(name,out definition))return true;definition=default(EngineDefinition);return false;}
  public static ISet<string> CreateSet(){return new HashSet<string>(_byName.Keys,StringComparer.OrdinalIgnoreCase);}
  public static bool IsAllowedWhere(string eventName,string field){
    if(string.IsNullOrWhiteSpace(field))return false;
    if(TryGet(eventName,out var definition)){foreach(var allowed in definition.AllowedWhereFields)if(string.Equals(allowed,field,StringComparison.OrdinalIgnoreCase))return true;return false;}
    if(TryGetEngine(eventName,out var engine)){foreach(var allowed in engine.AllowedWhereFields)if(string.Equals(allowed,field,StringComparison.OrdinalIgnoreCase))return true;}
    return false;
  }
}
