namespace Comfy.Quest.Studio;

static class QuestStudioPage
{
    public const string Html = """
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Quest Studio</title><style>
:root{color-scheme:dark;--ink:#eee8d4;--muted:#aeb1a4;--panel:#191d22;--deep:#101418;--line:#3b4446;--gold:#d7aa57;--green:#6dc69e;--red:#e08373;--blue:#6fa8dc}*{box-sizing:border-box}body{max-width:1280px;margin:24px auto;padding:0 18px;background:var(--deep);color:var(--ink);font:15px system-ui}h1{margin:0;color:var(--gold)}h2,h3{margin-top:0}.muted{color:var(--muted)}.layout{display:grid;grid-template-columns:minmax(440px,1.25fr) minmax(330px,.75fr);gap:16px}.card{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:18px;margin:16px 0}.grimoire{border-color:#79633a;background:linear-gradient(145deg,#211f1a,#191d22)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:block;margin:9px 0 5px;color:#d9d4bd;font-weight:650}input,select,textarea{width:100%;padding:9px;border-radius:7px;border:1px solid #525b5d;background:#101419;color:var(--ink);font:inherit}textarea{min-height:68px;resize:vertical}.actions,.stage-tools{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}button{border:0;border-radius:7px;padding:9px 13px;background:#886b32;color:white;font-weight:700;cursor:pointer}button.secondary{background:transparent;border:1px solid #626d70}button.danger{background:transparent;border:1px solid #76504a;color:#efb1a6}button:disabled{opacity:.42;cursor:not-allowed}.status{border-left:4px solid var(--gold)}.status.ok{border-left-color:var(--green)}.status.bad{border-left-color:var(--red)}pre{white-space:pre-wrap;overflow:auto;background:#0b0e11;padding:13px;border-radius:8px;max-height:340px}.stage-editor{border:1px solid #725f3a;border-radius:11px;background:#151714;margin:12px 0;overflow:hidden}.stage-head{display:flex;align-items:center;gap:9px;padding:10px 12px;background:#20221d;border-bottom:1px solid #564b34}.stage-number{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#6e562c;color:#fff;font-weight:800}.stage-body{padding:12px}.stage-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.graph-stage{padding:13px;border:1px solid #725f3a;border-radius:10px;background:#151714}.arrow{text-align:center;color:var(--gold);font-size:22px;line-height:1}.role{color:var(--blue)}.pill{display:inline-block;border-radius:999px;padding:2px 8px;background:#29333a;color:#cbd8df;font-size:.8rem}.topline{display:flex;align-items:flex-start;gap:14px}.topline .muted{margin:5px 0 0}.topline .pill{margin-left:auto}.history-row{border-top:1px solid #30383b;padding-top:9px}@media(max-width:900px){.layout{grid-template-columns:1fr}}@media(max-width:620px){.grid,.stage-grid{grid-template-columns:1fr}}
</style></head><body>
<header class="topline"><div><h1>Quest Studio</h1><p class="muted">Author a bounded multi-stage experience. Runtime changes only after explicit Publish, Check, and Load.</p></div><span class="pill">standalone · loopback</span></header>
<div class="layout"><main><section class="card grimoire"><h2>Project</h2><div class="grid">
<div><label for="pack">Pack ID</label><input id="pack" maxlength="64"></div><div><label for="version">Semantic version</label><input id="version" placeholder="1.0.0"></div>
<div><label for="experience">Experience ID</label><input id="experience" maxlength="64"></div><div><label for="title">Title</label><input id="title" maxlength="120"></div>
<div><label for="binding">Charm target</label><select id="binding"><option value="sign">Sign</option><option value="player_built_piece">Any player-built piece</option><option value="item_stand">Item stand</option><option value="dedicated_charm">Dedicated charm</option></select></div></div>
<div class="actions"><button class="secondary" onclick="addStage()">+ Add stage</button><button class="secondary" onclick="loadRitual()">Reset to live ritual</button></div><div id="stages"></div>
<div class="actions"><button onclick="save()">Save &amp; certify</button><button class="secondary" onclick="certify()">Validate without saving</button><button onclick="publishProject()">Publish to Runtime inbox</button></div></section></main>
<aside><section class="card"><h2>Graph preview</h2><div id="graph"></div></section>
<section class="card status" id="status"><h2 id="status-title">Loading Studio…</h2><p id="status-text" class="muted"></p><pre id="details" hidden></pre></section>
<section class="card"><h2>Runtime receipts</h2><p class="muted">The latest local Valheim receipts; refreshes after Studio actions.</p><div id="receipts">No receipts yet.</div></section>
<section class="card"><h2>Version history and diff</h2><div class="grid"><select id="diff-from"></select><select id="diff-to"></select></div><div class="actions"><button class="secondary" onclick="compareVersions()">Compare</button></div><div id="history">No saved versions yet.</div><pre id="diff" hidden></pre></section></aside></div>
<script>
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token='',events=[],eventDefinitions={},stages=[];
async function api(url,opt={},retry=true){let r=await fetch(url,{cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(token?{'X-Workbench-Token':token}:{}),...(opt.headers||{})}}),text=await r.text(),d;try{d=text?JSON.parse(text):{error:`http_${r.status}`}}catch{d={error:`http_${r.status}`,detail:text||'The server returned an empty response.'}}if(r.status===403&&retry&&!url.endsWith('/security')){token=(await api('/api/v1/workbench/security',{},false)).browser_token;return api(url,opt,false)}if(!r.ok)throw d;return d}
function ritual(){return[{id:'await-peer-shout',event:'chat_received',target:'shout',actor_role:'peer',message:'A distant voice wakes the Charm.'},{id:'await-host-sign',event:'piece_placed',target:'sign',actor_role:'listen_host',message:'The host raises the answering rune. The ritual is complete.'}]}
function normalized(p){return p.stages?.length?p.stages:[{id:'start',event:p.event||'kill',target:p.target||'',actor_role:null,message:p.message||'The Charm answers your deed.'}]}
function project(){let first=stages[0]||{};return{pack_id:q('#pack').value.trim(),version:q('#version').value.trim(),experience_id:q('#experience').value.trim(),title:q('#title').value.trim(),event:first.event||'',target:first.target?.trim()||null,message:first.message?.trim()||'',binding_target_kind:q('#binding').value,stages:stages.map(s=>({id:s.id.trim(),event:s.event,target:s.target.trim()||null,actor_role:s.actor_role||null,message:s.message.trim()}))}}
function paint(p){q('#pack').value=p.pack_id;q('#version').value=p.version;q('#experience').value=p.experience_id;q('#title').value=p.title;q('#binding').value=p.binding_target_kind||'sign';stages=normalized(p).map(x=>({...x,target:x.target||'',actor_role:x.actor_role||''}));render()}
function options(selected){return events.map(x=>`<option value="${esc(x)}"${x===selected?' selected':''}>${esc(x.replaceAll('_',' '))}</option>`).join('')}
function roleOptions(s){let roles=eventDefinitions[s.event]?.actor_roles||[];if(!roles.length)return'<option value="">Local authoritative actor</option>';return roles.map(x=>`<option value="${x}"${s.actor_role===x?' selected':''}>${x==='listen_host'?'Listen host':'Peer'}</option>`).join('')}
function render(){q('#stages').innerHTML=stages.map((s,i)=>`<article class="stage-editor"><div class="stage-head"><span class="stage-number">${i+1}</span><strong>${esc(s.id||'unnamed-stage')}</strong><span class="pill">${i===stages.length-1?'complete':`then ${esc(stages[i+1]?.id||'next stage')}`}</span></div><div class="stage-body"><div class="stage-grid"><div><label>Stage ID</label><input maxlength="64" value="${esc(s.id)}" oninput="setStage(${i},'id',this.value)"></div><div><label>Runtime event</label><select onchange="setEvent(${i},this.value)">${options(s.event)}</select><span class="muted">${esc(eventDefinitions[s.event]?.note||'')}</span></div><div><label>Target (optional)</label><input maxlength="120" value="${esc(s.target)}" oninput="setStage(${i},'target',this.value)"></div><div><label>Actor role</label><select onchange="setStage(${i},'actor_role',this.value)" ${(eventDefinitions[s.event]?.actor_roles||[]).length?'':'disabled'}>${roleOptions(s)}</select></div></div><label>Message action</label><textarea maxlength="500" oninput="setStage(${i},'message',this.value)">${esc(s.message)}</textarea><div class="stage-tools"><button class="secondary" onclick="moveStage(${i},-1)" ${i===0?'disabled':''}>↑ Earlier</button><button class="secondary" onclick="moveStage(${i},1)" ${i===stages.length-1?'disabled':''}>↓ Later</button><button class="secondary" onclick="duplicateStage(${i})">Duplicate</button><button class="danger" onclick="removeStage(${i})" ${stages.length===1?'disabled':''}>Remove</button></div></div></article>`).join('');preview()}
function setStage(i,k,v){stages[i][k]=v;renderGraph()}
function setEvent(i,v){stages[i].event=v;let roles=eventDefinitions[v]?.actor_roles||[];stages[i].actor_role=roles.includes(stages[i].actor_role)?stages[i].actor_role:(roles[0]||'');render()}
function addStage(){let n=stages.length+1;stages.push({id:`stage-${n}`,event:'piece_placed',target:'',actor_role:'',message:'The quest advances.'});render()}
function duplicateStage(i){let copy={...stages[i],id:stages[i].id+'-copy'};stages.splice(i+1,0,copy);render()}
function removeStage(i){if(stages.length>1){stages.splice(i,1);render()}}
function moveStage(i,d){let j=i+d;if(j<0||j>=stages.length)return;[stages[i],stages[j]]=[stages[j],stages[i]];render()}
function loadRitual(){q('#pack').value='studio-two-voices-one-rune';q('#version').value='1.0.0';q('#experience').value='two-voices-one-rune';q('#title').value='Two Voices, One Rune';q('#binding').value='sign';stages=ritual();render()}
function preview(){renderGraph()}
function renderGraph(){q('#graph').innerHTML=stages.length?stages.map((s,i)=>`<div class="graph-stage"><strong>${i+1}. ${esc(s.id||'unnamed')}</strong><p>When <b>${esc(s.event||'event')}</b>${s.target?` targets <b>${esc(s.target)}</b>`:''}${s.actor_role?` by <span class="role">${esc(s.actor_role)}</span>`:''}</p><p class="muted">${esc(s.message||'No message')}</p></div>${i<stages.length-1?'<div class="arrow">↓</div>':''}`).join(''):'No stages.'}
function status(ok,title,text,data){let e=q('#status');e.className='card status '+(ok?'ok':'bad');q('#status-title').textContent=title;q('#status-text').textContent=text||'';q('#details').hidden=!data;q('#details').textContent=data?JSON.stringify(data,null,2):''}
async function mutate(path){try{let d=await api(path,{method:'POST',body:JSON.stringify(project())}),validatedOnly=path.endsWith('/certify');status(true,d.status==='published'?'Published to Runtime inbox':d.status==='saved'?'Saved & certified':'Validation passed',d.receipt?`${d.receipt.pack_id} ${d.receipt.version} · ${d.receipt.content_hash}`:validatedOnly?`content ${d.content_hash} · not saved`:`content ${d.content_hash}`,d);if(path.includes('save')||path.includes('publish'))await loadHistory();await loadReceipts();return d}catch(e){status(false,'Studio rejected the project',e.error||'Validation failed',e)}}
async function loadHistory(){try{let d=await api('/api/v1/workbench/quest-studio/history'),v=d.versions||[],o=v.map(x=>`<option value="${x.content_hash}">${esc(x.project.version)} · ${esc(x.project.title)} · ${x.content_hash.slice(0,8)}</option>`).join('');q('#diff-from').innerHTML=o;q('#diff-to').innerHTML=o;if(v.length>1)q('#diff-from').selectedIndex=1;q('#history').innerHTML=v.length?v.map(x=>`<p class="history-row"><strong>${esc(x.project.version)}</strong> · ${esc(x.project.title)} · ${x.project.stages?.length||1} stage(s)<br><span class="muted">${esc(x.saved_utc)} · ${x.content_hash.slice(0,12)}</span></p>`).join(''):'No saved versions yet.'}catch{q('#history').textContent='History unavailable.'}}
async function compareVersions(){try{let from=q('#diff-from').value,to=q('#diff-to').value;if(!from||!to)return;let d=await api('/api/v1/workbench/quest-studio/diff?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to));q('#diff').hidden=false;q('#diff').textContent=d.changes.length?d.changes.map(x=>`${x.field}\n- ${x.from??''}\n+ ${x.to??''}`).join('\n\n'):'No semantic changes.'}catch(e){status(false,'Diff unavailable',e.error||'Version could not be compared.',e)}}
async function loadReceipts(){try{let d=await api('/api/v1/workbench/quest-studio/receipts'),r=d.receipts||[];q('#receipts').innerHTML=r.length?r.slice(0,8).map(x=>`<p><strong>${esc(x.operation)}</strong> · ${esc(x.status)} · ${esc(x.pack_id||'')} ${esc(x.version||'')}<br><span class="muted">${esc(x.at_utc)}${x.error?' · '+esc(x.error):''}</span></p>`).join(''):(d.available?'No Runtime receipts yet.':'Valheim unavailable; manual copy remains available.')}catch{q('#receipts').textContent='Receipts unavailable.'}}
async function save(){return mutate('/api/v1/workbench/quest-studio/save')}async function certify(){return mutate('/api/v1/workbench/quest-studio/certify')}async function publishProject(){return mutate('/api/v1/workbench/quest-studio/publish-project')}
async function init(){try{token=(await api('/api/v1/workbench/security')).browser_token;let catalog=await api('/api/v1/workbench/quest-studio/events');events=catalog.events||[];eventDefinitions=Object.fromEntries((catalog.event_definitions||[]).map(x=>[x.id,x]));paint(await api('/api/v1/workbench/quest-studio/project'));['pack','version','experience','title','binding'].forEach(x=>q('#'+x).addEventListener('input',preview));status(true,'Multi-stage draft ready',`${stages.length} stages · save, certify, or publish explicitly.`);await Promise.all([loadReceipts(),loadHistory()])}catch(e){status(false,'Studio unavailable',e.error||String(e),e)}}init();
</script></body></html>
""";
}
