namespace ComfyNetworkSense.Tests;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using ComfyQuestContracts;
using Xunit;

public sealed class ExperienceContractTests {
  [Fact] public void EasySignalsNormalizeWithoutPersistingPrivatePayloads(){var at=DateTimeOffset.UnixEpoch;var said=EasyEventContract.ChatSent("Normal","private words",at);Assert.Equal("chat_sent",said.Name);Assert.Equal("normal",said.Target);Assert.Null(said.Fields);Assert.DoesNotContain("private words",JsonConvert.SerializeObject(said));var shout=EasyEventContract.ChatSent("Shout","also private",at);Assert.Equal("shout",shout.Target);var drop=EasyEventContract.ItemDropped("Wood(Clone)",2,at);Assert.Equal("item_dropped",drop.Name);Assert.Equal("Wood",drop.Target);Assert.Equal("item_picked_up",EasyEventContract.ItemPickedUp("Stone(Clone)",at).Name);Assert.Equal("Stone",EasyEventContract.ItemPickedUp("Stone(Clone)",at).Target);Assert.Equal("item_equipped",EasyEventContract.ItemEquipped("Hammer(Clone)",at).Name);Assert.Equal("item_consumed",EasyEventContract.ItemConsumed("CookedMeat(Clone)",at).Name);var heal=EasyEventContract.CharacterHealed(0.5f,at);Assert.Equal("character_healed",heal.Name);Assert.Equal("you",heal.Target);Assert.Null(EasyEventContract.ChatSent("Whisper","no",at));Assert.Null(EasyEventContract.ItemDropped("Wood",0,at));Assert.Null(EasyEventContract.ItemPickedUp(null,at));Assert.Null(EasyEventContract.CharacterHealed(0f,at));}
  [Fact] public void EasySignalsSupportWildcardStudioTriggers(){var events=new[]{EasyEventContract.ItemDropped("Stone",1,DateTimeOffset.UnixEpoch),EasyEventContract.CharacterHealed(1f,DateTimeOffset.UnixEpoch)};Assert.True(TriggerEvaluator.Matches(new TriggerExpression{Op="EVENT",Event="item_dropped"},events));Assert.True(TriggerEvaluator.Matches(new TriggerExpression{Op="EVENT",Event="character_healed"},events));}
  [Fact] public void CoreLocalActionsNormalizeOnlyCatalogPayloads(){var at=DateTimeOffset.UnixEpoch;Assert.Equal("piece_chest_wood",CoreActionEventContract.ContainerEmptied("piece_chest_wood(Clone)",at).Target);Assert.Equal("AxeBronze",CoreActionEventContract.ItemUnequipped(" AxeBronze(Clone) ",at).Target);Assert.Equal("wood_wall",CoreActionEventContract.PieceDestroyed("wood_wall(Clone)",at).Target);Assert.Equal("piece",CoreActionEventContract.PieceRemoved(at).Target);Assert.Equal("wood_wall",CoreActionEventContract.PieceRepaired("wood_wall",at).Target);Assert.Null(CoreActionEventContract.PlayerTeleported(at).Target);Assert.Null(CoreActionEventContract.ContainerEmptied(" ",at));Assert.Null(CoreActionEventContract.ItemUnequipped(null,at));}
  [Fact] public void CoreLocalActionProofRejectsDeniedPartialStaleRemoteAndNoOpPaths(){Assert.True(CoreActionProof.ContainerEmptied(true,true,3,0,0.5));Assert.False(CoreActionProof.ContainerEmptied(true,false,3,0,0.5));Assert.False(CoreActionProof.ContainerEmptied(true,true,0,0,0.5));Assert.False(CoreActionProof.ContainerEmptied(true,true,3,1,0.5));Assert.False(CoreActionProof.ContainerEmptied(true,true,3,0,10.1));Assert.False(CoreActionProof.ContainerEmptied(false,true,3,0,0.5));Assert.True(CoreActionProof.ItemUnequipped(true,true,false));Assert.False(CoreActionProof.ItemUnequipped(true,false,false));Assert.False(CoreActionProof.ItemUnequipped(true,true,true));Assert.False(CoreActionProof.PieceDestroyed(false));Assert.False(CoreActionProof.PieceRemoved(true,false));Assert.False(CoreActionProof.PieceRepaired(true,false));Assert.False(CoreActionProof.PlayerTeleported(true,false));Assert.True(CoreActionProof.PieceDestroyed(true));Assert.True(CoreActionProof.PieceRemoved(true,true));Assert.True(CoreActionProof.PieceRepaired(true,true));Assert.True(CoreActionProof.PlayerTeleported(true,true));}
  [Fact] public void CombatHarvestEventsNormalizeOnlyApprovedTargetsAndFields(){var at=DateTimeOffset.UnixEpoch;var damage=CombatHarvestEventContract.DamageDealt("$enemy_greyling(Clone)","Axes",true,at);Assert.Equal("damage_dealt",damage.Name);Assert.Equal("$enemy_greyling",damage.Target);Assert.Equal("Axes",damage.Fields["weapon_skill"]);Assert.Equal("true",damage.Fields["projectile"]);var resource=CombatHarvestEventContract.ResourceDamaged("Beech1(Clone)","Axes",false,at);Assert.Equal("Beech1",resource.Target);Assert.Equal("false",resource.Fields["projectile"]);Assert.Equal("resource_picked",CombatHarvestEventContract.ResourcePicked("RaspberryBush(Clone)",at).Name);Assert.Null(CombatHarvestEventContract.AttackBlocked(" ","Axes",false,at));Assert.Null(CombatHarvestEventContract.CharacterStaggered("Greydwarf"," ",false,at));Assert.DoesNotContain("player",JsonConvert.SerializeObject(damage),StringComparison.OrdinalIgnoreCase);}
  [Fact] public void CombatHarvestProofRejectsNoOpRemoteRepeatedAndRefusedPaths(){Assert.True(CombatHarvestProof.DamageDealt(true,true,20,15));Assert.False(CombatHarvestProof.DamageDealt(false,true,20,15));Assert.False(CombatHarvestProof.DamageDealt(true,false,20,15));Assert.False(CombatHarvestProof.DamageDealt(true,true,20,20));Assert.False(CombatHarvestProof.DamageDealt(true,true,double.NaN,15));Assert.True(CombatHarvestProof.CharacterStaggered(true,false,true));Assert.False(CombatHarvestProof.CharacterStaggered(true,true,true));Assert.False(CombatHarvestProof.CharacterStaggered(false,false,true));Assert.True(CombatHarvestProof.AttackBlocked(true,true));Assert.False(CombatHarvestProof.AttackBlocked(true,false));Assert.True(CombatHarvestProof.ResourceDamaged(true,true,true));Assert.False(CombatHarvestProof.ResourceDamaged(true,false,true));Assert.False(CombatHarvestProof.ResourceDamaged(true,true,false));Assert.True(CombatHarvestProof.ResourcePicked(true,true,false,true));Assert.False(CombatHarvestProof.ResourcePicked(false,true,false,true));Assert.False(CombatHarvestProof.ResourcePicked(true,true,true,true));Assert.False(CombatHarvestProof.ResourcePicked(true,true,false,false));}
  [Fact] public void CraftingEventsExposeOnlyNormalizedStationItemAndQuantity(){var at=DateTimeOffset.UnixEpoch;Assert.Equal("piece_workbench",CraftingEventContract.ItemCrafted("piece_workbench(Clone)",at).Target);Assert.Equal("handcrafting",CraftingEventContract.ItemCrafted(null,at).Target);var input=CraftingEventContract.StationInputAdded("smelter(Clone)","CopperOre(Clone)",at);Assert.Equal("CopperOre",input.Target);Assert.Equal("smelter",input.Fields["station"]);Assert.Equal("1",input.Fields["quantity"]);var output=CraftingEventContract.StationOutputProduced("smelter","Copper",3,at);Assert.Equal("3",output.Fields["quantity"]);Assert.Null(CraftingEventContract.StationOutputProduced("smelter","Copper",0,at));Assert.DoesNotContain("sender",JsonConvert.SerializeObject(input),StringComparison.OrdinalIgnoreCase);}
  [Fact] public void CraftingProofRejectsFailedRemoteFullAndZeroQuantityPaths(){Assert.True(CraftingProof.ItemCrafted(true,true,1,2));Assert.False(CraftingProof.ItemCrafted(true,false,1,2));Assert.False(CraftingProof.ItemCrafted(true,true,2,2));Assert.True(CraftingProof.StationValueIncreased(true,true,1,2));Assert.False(CraftingProof.StationValueIncreased(true,true,2,2));Assert.False(CraftingProof.StationValueIncreased(false,true,1,2));Assert.True(CraftingProof.StationSlotAdded(true,true,0,1));Assert.False(CraftingProof.StationSlotAdded(true,false,0,1));Assert.True(CraftingProof.StationOutputCollected(true,true,1,0,1));Assert.False(CraftingProof.StationOutputCollected(true,true,1,1,1));Assert.False(CraftingProof.StationOutputCollected(true,true,1,0,0));Assert.True(CraftingProof.StationOutputProduced(true,true,2));Assert.False(CraftingProof.StationOutputProduced(false,true,2));Assert.False(CraftingProof.StationOutputProduced(true,false,2));}
  const string Valid = """{"schema":"comfy-quest-experience/v1","id":"hello","entry_stage":"start","stages":[{"id":"start","transitions":[{"id":"done","priority":1,"when":{"op":"EVENT","event":"kill","target":"Troll"},"actions":[{"id":"say","type":"message","text":"Skal!"}],"outcome":"complete"}]}],"bindings":[{"id":"sign","experience_id":"hello"}]}""";
  [Fact] public void CompilesMinimalExperience(){var c=ExperienceCompiler.CompileJson(Valid,new HashSet<string>{"kill"});Assert.True(c.IsValid,string.Join(";",c.Diagnostics));}
  [Fact] public void RejectsCycles(){var json=Valid.Replace("\"outcome\":\"complete\"","\"next_stage\":\"start\"");Assert.Contains(ExperienceCompiler.CompileJson(json,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="graph.cycle");}
  [Fact] public void EvaluatesSequenceDeterministically(){var x=new TriggerExpression{Op="SEQUENCE",Children=new(){new(){Op="EVENT",Event="hit"},new(){Op="EVENT",Event="kill"}}};var h=new[]{new RuntimeEvent{Name="hit",At=DateTimeOffset.UnixEpoch},new RuntimeEvent{Name="kill",At=DateTimeOffset.UnixEpoch.AddSeconds(1)}};Assert.True(TriggerEvaluator.Matches(x,h));Assert.False(TriggerEvaluator.Matches(x,new[]{h[1],h[0]}));}
  [Fact] public void RejectsUnknownActions(){Assert.Contains(ExperienceCompiler.CompileJson(Valid.Replace("message","shell"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="action.unsupported");}
  [Fact] public void RejectsUnboundedOrUnknownActionParameters(){var excessive=Valid.Replace("\"text\":\"Skal!\"","\"text\":\"Skal!\",\"command\":\"nocost\"");Assert.Contains(ExperienceCompiler.CompileJson(excessive,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="action.parameter_unknown");var spawn=Valid.Replace("{\"id\":\"say\",\"type\":\"message\",\"text\":\"Skal!\"}","{\"id\":\"say\",\"type\":\"spawn\",\"kind\":\"creature\",\"prefab\":\"Greydwarf\",\"count\":17,\"radius\":30}");Assert.Contains(ExperienceCompiler.CompileJson(spawn,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="action.parameter");}
  [Fact] public void ExperienceAndLegacyCatalogsStayIdentical(){Assert.Equal(new HashSet<string>(QuestEventCatalog.AllEventNames,StringComparer.OrdinalIgnoreCase),new HashSet<string>(CanonicalEventCatalog.All,StringComparer.OrdinalIgnoreCase));}
  [Fact] public void GeneratedCreatorAndRuntimeBoundariesHaveExactCounts(){Assert.Equal(34,CreatorEventCatalog.Count);Assert.Equal(34,RuntimeProductionEventCatalog.Count);Assert.Equal(2,RuntimeProductionEventCatalog.EngineEvents.Count);Assert.Equal(57,RuntimeWitnessCatalog.Count);foreach(var name in new[]{"kill","container_emptied","item_unequipped","piece_destroyed","piece_removed","piece_repaired","player_teleported","attack_blocked","character_staggered","damage_dealt","resource_damaged","resource_picked","item_crafted","station_fuel_added","station_input_added","station_output_collected","station_output_produced","global_key_removed","global_key_set","max_health_changed","player_died","skill_raised","skills_lowered","stamina_gained","stamina_spent"})Assert.True(RuntimeProductionEventCatalog.Contains(name),name);foreach(var creator in CreatorEventCatalog.All)Assert.True(creator.ProductionAvailable,creator.Name);}
  [Theory][InlineData("container_emptied","piece_chest_wood")][InlineData("item_unequipped","AxeBronze")][InlineData("piece_destroyed","wood_wall")][InlineData("piece_removed","piece")][InlineData("piece_repaired","wood_wall")] public void CoreLocalActionsCompileWithExactOrWildcardTargets(string eventName,string target){var exact=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"",$"\"event\":\"{eventName}\",\"target\":\"{target}\"");Assert.True(ExperienceCompiler.CompileProductionJson(exact).IsValid);var wildcard=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"",$"\"event\":\"{eventName}\"");Assert.True(ExperienceCompiler.CompileProductionJson(wildcard).IsValid);}
  [Fact] public void SuccessfulTeleportIsTargetless(){var valid=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"player_teleported\"");Assert.True(ExperienceCompiler.CompileProductionJson(valid).IsValid);Assert.Contains(ExperienceCompiler.CompileProductionJson(valid.Replace("\"event\":\"player_teleported\"","\"event\":\"player_teleported\",\"target\":\"portal\"")).Diagnostics,x=>x.Code=="trigger.target_unsupported");}
  [Theory][InlineData("attack_blocked","$enemy_greyling")][InlineData("character_staggered","$enemy_greyling")][InlineData("damage_dealt","$enemy_greyling")][InlineData("resource_damaged","Beech1")][InlineData("resource_picked","RaspberryBush")] public void CombatHarvestEventsCompileWithExactOrWildcardTargets(string eventName,string target){var exact=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"",$"\"event\":\"{eventName}\",\"target\":\"{target}\"");Assert.True(ExperienceCompiler.CompileProductionJson(exact).IsValid);var wildcard=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"",$"\"event\":\"{eventName}\"");Assert.True(ExperienceCompiler.CompileProductionJson(wildcard).IsValid);}
  [Fact] public void ProductionCompilerRejectsNonCreatorEventsAndDeadConstraints(){Assert.True(ExperienceCompiler.CompileProductionJson(Valid).IsValid);var unsupported=Valid.Replace("\"event\":\"kill\"","\"event\":\"inventory_item_added\"");Assert.Contains(ExperienceCompiler.CompileProductionJson(unsupported).Diagnostics,x=>x.Code=="event.not_production");var dead=Valid.Replace("\"target\":\"Troll\"","\"target\":\"Troll\",\"where\":{\"amount\":\"1\"}");Assert.Contains(ExperienceCompiler.CompileProductionJson(dead).Diagnostics,x=>x.Code=="trigger.where_unsupported");}
  [Theory][InlineData("projectile","any")][InlineData("projectile","false")][InlineData("weapon_skill","")][InlineData("weapon_skill","                                                                                                                                x")] public void ProductionCompilerRejectsInvalidWhereValues(string field,string value){var json=Valid.Replace("\"target\":\"Troll\"",$"\"target\":\"Troll\",\"where\":{{\"{field}\":\"{value}\"}}");Assert.Contains(ExperienceCompiler.CompileProductionJson(json).Diagnostics,x=>x.Code=="trigger.where_value");}
  [Theory][InlineData("NaN")][InlineData("Infinity")][InlineData("-1")][InlineData("0")] public void ProductionCompilerRequiresPositiveFiniteAmounts(string value){var json=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"",$"\"event\":\"character_healed\",\"target\":\"you\",\"where\":{{\"amount\":\"{value}\"}}");Assert.Contains(ExperienceCompiler.CompileProductionJson(json).Diagnostics,x=>x.Code=="trigger.where_value");}
  [Fact] public void ProductionCompilerEnforcesAdapterFixedFields(){var placed=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"piece_placed\",\"target\":\"wood_wall\",\"where\":{\"actor_role\":\"peer\"}");Assert.Contains(ExperienceCompiler.CompileProductionJson(placed).Diagnostics,x=>x.Code=="trigger.where_fixed");Assert.True(ExperienceCompiler.CompileProductionJson(placed.Replace("\"peer\"","\"listen_host\"")).IsValid);}
  [Fact] public void ProductionCompilerRejectsTargetsAdaptersCannotEmit(){var heal=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"character_healed\",\"target\":\"someone_else\"");Assert.Contains(ExperienceCompiler.CompileProductionJson(heal).Diagnostics,x=>x.Code=="trigger.target_fixed");var chat=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"chat_sent\",\"target\":\"whisper\"");Assert.Contains(ExperienceCompiler.CompileProductionJson(chat).Diagnostics,x=>x.Code=="trigger.target_value");Assert.True(ExperienceCompiler.CompileProductionJson(chat.Replace("\"whisper\"","\"normal\"")).IsValid);var timer=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"timer_elapsed\",\"target\":\"bell\",\"where\":{\"timer_id\":\"bell\"}");Assert.Contains(ExperienceCompiler.CompileProductionJson(timer).Diagnostics,x=>x.Code=="trigger.target_unsupported");}
  [Fact] public void RuntimeNormalizationDropsUnknownPayloadAndRejectsNonCreatorEvents(){var normalized=RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="character_healed",Target="you(Clone)",At=DateTimeOffset.UnixEpoch,Fields=new Dictionary<string,string>{{"amount","2.5"},{"player_name","secret"}}});Assert.Equal("you",normalized.Target);Assert.Equal("2.5",normalized.Fields["amount"]);Assert.False(normalized.Fields.ContainsKey("player_name"));var combat=RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="attack_blocked",Target="Greydwarf(Clone)",Fields=new Dictionary<string,string>{{"weapon_skill","Blocking"},{"projectile","false"},{"player_name","secret"}}});Assert.Equal("Greydwarf",combat.Target);Assert.Equal(2,combat.Fields.Count);var progression=RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="max_health_changed",Target="health",Fields=new Dictionary<string,string>{{"subject","health"},{"amount","125"},{"player_name","secret"}}});Assert.Equal("health",progression.Target);Assert.Equal(2,progression.Fields.Count);Assert.Null(RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="inventory_item_added",Target="Wood"}));}
  [Fact] public void RuntimeNormalizationEnforcesClosedAndFixedTargets(){Assert.Null(RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="character_healed",Target="someone_else"}));Assert.Null(RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="chat_sent",Target="whisper"}));Assert.Equal("normal",RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="chat_sent",Target="normal"}).Target);Assert.Null(RuntimeEventPolicy.Normalize(new RuntimeEvent{Name="timer_elapsed",Target="bell",Fields=new Dictionary<string,string>{{"timer_id","bell"}}}));}
  [Fact] public void RuntimeActionCorrelationJoinsAlternateWitnessButNotRepeat(){var dedupe=new RuntimeActionDedupe();var first=dedupe.Key("heal","player","2.5","Character.Heal",10);var alternate=dedupe.Key("heal","player","2.5","Character.RPC_Heal",10.1);var repeat=dedupe.Key("heal","player","2.5","Character.Heal",10.2);Assert.Equal(first,alternate);Assert.NotEqual(first,repeat);}
  [Fact] public void DefaultPackInspectionUsesProductionBoundary(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;var path=Path.Combine(inbox,"unsupported.questpack");WritePack(path,"1.0.0",Valid.Replace("\"event\":\"kill\"","\"event\":\"inventory_item_added\""));Assert.Contains(new QuestPackStore(root).Inspect(path).Diagnostics,x=>x.Code=="event.not_production");}finally{Directory.Delete(root,true);}}
  [Fact] public void ProgressionAndWorldContractsRequireActualBoundedChanges(){var health=ProgressionEventContract.MaxHealthChanged(125f,DateTimeOffset.UnixEpoch);Assert.Equal("health",health.Target);Assert.Equal("health",health.Fields["subject"]);Assert.Equal("125",health.Fields["amount"]);var skill=ProgressionEventContract.SkillRaised("Axes",1.5f,DateTimeOffset.UnixEpoch);Assert.Equal("Axes",skill.Target);Assert.Equal("Axes",skill.Fields["subject"]);Assert.Null(ProgressionEventContract.StaminaSpent(0f,DateTimeOffset.UnixEpoch));Assert.True(ProgressionProof.ValueChanged(true,100,125));Assert.False(ProgressionProof.ValueChanged(true,100,100));Assert.True(ProgressionProof.ValueIncreased(true,10,15));Assert.False(ProgressionProof.ValueIncreased(false,10,15));Assert.True(ProgressionProof.ValueDecreased(true,15,10));Assert.True(ProgressionProof.SkillRaised(true,7,0.2,7,0.3));Assert.True(ProgressionProof.SkillRaised(true,7,0.9,8,0));Assert.False(ProgressionProof.SkillRaised(true,7,0.2,7,0.2));Assert.True(ProgressionProof.SkillsLowered(true,0.05,100,1,95,0));Assert.False(ProgressionProof.SkillsLowered(true,0,100,1,100,0));Assert.True(ProgressionProof.PlayerDied(true,true,false,true));Assert.False(ProgressionProof.PlayerDied(true,false,false,true));var set=WorldStateEventContract.GlobalKeySet("defeated_eikthyr",DateTimeOffset.UnixEpoch);Assert.Equal("defeated_eikthyr",set.Target);Assert.True(WorldStateProof.GlobalKeySet(true,false,true));Assert.False(WorldStateProof.GlobalKeySet(true,true,true));Assert.True(WorldStateProof.GlobalKeyRemoved(true,true,false));Assert.False(WorldStateProof.GlobalKeyRemoved(false,true,false));}
  [Fact] public void ActivatesOnlyOnExplicitLoad(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"hello.questpack"),"1.0.0",Valid);var store=new QuestPackStore(root);Assert.False(File.Exists(Path.Combine(root,"active","active-set.json")));Assert.Single(store.CheckInbox(new HashSet<string>{"kill"}));var loaded=store.LoadLatest(new HashSet<string>{"kill"});Assert.Equal("1.0.0",loaded.Manifest.Version);Assert.True(File.Exists(Path.Combine(root,"active","active-set.json")));}finally{Directory.Delete(root,true);}}
  [Fact] public void SameVersionDifferentContentFailsClosed(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"a.questpack"),"1.0.0",Valid);WritePack(Path.Combine(inbox,"b.questpack"),"1.0.0",Valid.Replace("Skal!","Hail!"));var store=new QuestPackStore(root);Assert.Throws<InvalidOperationException>(()=>store.LoadLatest(new HashSet<string>{"kill"}));}finally{Directory.Delete(root,true);}}
  [Fact] public void RejectsUnsupportedArchiveEntries(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;var path=Path.Combine(inbox,"unsafe.questpack");WritePack(path,"1.0.0",Valid);using(var zip=ZipFile.Open(path,ZipArchiveMode.Update))using(var writer=new StreamWriter(zip.CreateEntry("scripts/run.txt").Open()))writer.Write("no");Assert.Contains(new QuestPackStore(root).Inspect(path,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="pack.path");}finally{Directory.Delete(root,true);}}
  [Fact] public void SelectsVersionAndRollsBackWithFreshActivationEpochs(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"one.questpack"),"1.0.0",Valid);WritePack(Path.Combine(inbox,"two.questpack"),"2.0.0",Valid.Replace("Skal!","Hail!"));var store=new QuestPackStore(root);Assert.Equal("2.0.0",store.LoadLatest(new HashSet<string>{"kill"}).Manifest.Version);var first=ReadActive(root);Assert.Matches("^act-[0-9]{8}T[0-9]{9}Z-[0-9a-f]{8}$",first.ActivationId);Assert.Equal("comfy-quest-active-set/v1",first.Schema);Assert.Equal("1.0.0",store.LoadVersion("demo","1.0.0",new HashSet<string>{"kill"}).Manifest.Version);var second=ReadActive(root);Assert.NotEqual(first.ActivationId,second.ActivationId);Assert.Equal("2.0.0",store.Rollback(new HashSet<string>{"kill"}).Manifest.Version);var rollback=ReadActive(root);Assert.Equal("2.0.0",rollback.Version);Assert.NotEqual(first.ActivationId,rollback.ActivationId);Assert.NotEqual(second.ActivationId,rollback.ActivationId);Assert.False(File.Exists(Path.Combine(root,"active","active-set.json.tmp")));}finally{Directory.Delete(root,true);}}
  [Fact] public void DevLaneActivatesExactRevisionWithoutPollutingProduction(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;var dev=Directory.CreateDirectory(Path.Combine(root,"inbox-dev")).FullName;WritePack(Path.Combine(inbox,"public.questpack"),"1.0.0",Valid);WritePack(Path.Combine(dev,"r1.questpack"),"1.0.0",Valid.Replace("Skal!","First"));WritePack(Path.Combine(dev,"r2.questpack"),"1.0.0",Valid.Replace("Skal!","Second"));var store=new QuestPackStore(root);Assert.Single(store.CheckInbox(new HashSet<string>{"kill"}));Assert.Equal(2,store.CheckDevInbox(new HashSet<string>{"kill"}).Count);Assert.Contains(store.Inspect(Path.Combine(dev,"r1.questpack"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="pack.path");var chosen=store.LoadDevRevision("r2.questpack",new HashSet<string>{"kill"});Assert.Equal(QuestPackLane.Dev,chosen.Lane);var active=ReadActive(root);Assert.Equal("dev",active.SourceChannel);Assert.Equal("r2.questpack",active.Source);Assert.Null(active.PreviousActivationId);}finally{Directory.Delete(root,true);}}
  [Fact] public void RollbackWalksActivationLineageAndSupportsAddressedHistory(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"one.questpack"),"1.0.0",Valid);WritePack(Path.Combine(inbox,"two.questpack"),"2.0.0",Valid.Replace("Skal!","Two"));WritePack(Path.Combine(inbox,"three.questpack"),"3.0.0",Valid.Replace("Skal!","Three"));var store=new QuestPackStore(root);store.LoadVersion("demo","1.0.0",new HashSet<string>{"kill"});var first=ReadActive(root);store.LoadVersion("demo","2.0.0",new HashSet<string>{"kill"});var second=ReadActive(root);store.LoadVersion("demo","3.0.0",new HashSet<string>{"kill"});Assert.Equal("2.0.0",store.Rollback(new HashSet<string>{"kill"}).Manifest.Version);var rollbackTwo=ReadActive(root);Assert.Equal(first.ActivationId,rollbackTwo.PreviousActivationId);Assert.Equal("1.0.0",store.Rollback(new HashSet<string>{"kill"}).Manifest.Version);var rollbackOne=ReadActive(root);Assert.Null(rollbackOne.PreviousActivationId);Assert.Null(store.Rollback(new HashSet<string>{"kill"}));Assert.Equal("2.0.0",store.Rollback(second.ActivationId,new HashSet<string>{"kill"}).Manifest.Version);Assert.NotEqual(second.ActivationId,ReadActive(root).ActivationId);}finally{Directory.Delete(root,true);}}
  [Fact] public void ActivationHistoryIsBoundedAndOldActiveSetsStayReadable(){var old=JsonConvert.DeserializeObject<ActiveSet>("{\"schema\":\"comfy-quest-active-set/v1\",\"pack_id\":\"demo\",\"version\":\"1.0.0\",\"source\":\"demo.questpack\"}");Assert.Null(old.ActivationId);Assert.Null(old.SourceChannel);Assert.Null(old.PreviousActivationId);var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"one.questpack"),"1.0.0",Valid);var store=new QuestPackStore(root);for(var i=0;i<13;i++)store.LoadVersion("demo","1.0.0",new HashSet<string>{"kill"});Assert.Equal(QuestPackStore.MaxActivationHistory,store.ActivationHistory().Count);}finally{Directory.Delete(root,true);}}
  [Fact] public void ArmedDevChannelPullsOnlyPostArmRevisionsAndCorrelatesProof(){var root=Path.Combine(Path.GetTempPath(),"comfy-dev-"+Guid.NewGuid().ToString("N"));try{var dev=Directory.CreateDirectory(Path.Combine(root,"inbox-dev")).FullName;WritePack(Path.Combine(dev,"old.questpack"),"1.0.0",Valid);var rebound=new List<ActiveSet>();var channel=new RuntimeDevChannelCoordinator(root,(active,correlation)=>{rebound.Add(active);return new[]{new RuntimeReceipt{Operation="dev_rebind",Status="rebound",PackId=active.PackId,Version=active.Version,ContentHash=active.ContentHash,ActivationId=active.ActivationId,CorrelationId=correlation,BindingZdo="1:2",Diagnostics=Array.Empty<ContractDiagnostic>()}};});var at=DateTimeOffset.Parse("2026-08-19T15:00:00Z");channel.Arm(at);Assert.False(channel.Poll(at.AddSeconds(1)).Activated);Assert.Null(new QuestPackStore(root).ReadActive());WritePack(Path.Combine(dev,"r2.questpack"),"1.0.0",Valid.Replace("Skal!","New"));var result=channel.Poll(at.AddSeconds(2),"start");Assert.True(result.Activated);Assert.Single(rebound);Assert.Equal("dev",result.ActiveSet.SourceChannel);var proofs=new RuntimeReceiptStore(root).List(20).Select(path=>JsonConvert.DeserializeObject<RuntimeReceipt>(File.ReadAllText(path))).Where(receipt=>receipt.CorrelationId==result.CorrelationId).ToArray();Assert.Equal(new[]{"dev_activation","dev_rebind","dev_transfer","dev_validation"},proofs.Select(receipt=>receipt.Operation).OrderBy(value=>value,StringComparer.Ordinal));Assert.All(proofs,receipt=>Assert.Equal(result.ActiveSet.ActivationId,receipt.ActivationId));var status=new RuntimeDevChannelStatusStore(root).Read();Assert.True(status.Armed);Assert.Equal("active",status.State);Assert.Equal("start",status.CurrentStageId);Assert.Equal(result.ActiveSet.ActivationId,status.ActiveActivationId);}finally{Directory.Delete(root,true);}}
  [Fact] public void DevChannelRejectsInvalidRevisionAndStartsDisarmedEachSession(){var root=Path.Combine(Path.GetTempPath(),"comfy-dev-"+Guid.NewGuid().ToString("N"));try{var dev=Directory.CreateDirectory(Path.Combine(root,"inbox-dev")).FullName;var first=new RuntimeDevChannelCoordinator(root);first.Heartbeat(DateTimeOffset.UnixEpoch);Assert.False(new RuntimeDevChannelStatusStore(root).Read().Armed);first.Arm(DateTimeOffset.UnixEpoch.AddSeconds(1));File.WriteAllText(Path.Combine(dev,"bad.questpack"),"not a zip");var rejected=first.Poll(DateTimeOffset.UnixEpoch.AddSeconds(2));Assert.False(rejected.Activated);Assert.Equal("pack_invalid",first.LastRejection);Assert.Equal("rejected",new RuntimeDevChannelStatusStore(root).Read().State);var restarted=new RuntimeDevChannelCoordinator(root);Assert.False(restarted.Armed);restarted.Heartbeat(DateTimeOffset.UnixEpoch.AddSeconds(3));Assert.False(new RuntimeDevChannelStatusStore(root).Read().Armed);}finally{Directory.Delete(root,true);}}
  [Fact] public void RollbackFailsClosedWhenPreviousPackageChanged(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;var one=Path.Combine(inbox,"one.questpack");WritePack(one,"1.0.0",Valid);WritePack(Path.Combine(inbox,"two.questpack"),"2.0.0",Valid.Replace("Skal!","Hail!"));var store=new QuestPackStore(root);store.LoadVersion("demo","1.0.0",new HashSet<string>{"kill"});store.LoadLatest(new HashSet<string>{"kill"});File.AppendAllText(one,"tamper");Assert.Throws<InvalidOperationException>(()=>store.Rollback(new HashSet<string>{"kill"}));}finally{Directory.Delete(root,true);}}
  [Fact] public void RuntimeReceiptsAreImmutableFiles(){var root=Path.Combine(Path.GetTempPath(),"comfy-receipt-"+Guid.NewGuid().ToString("N"));try{var store=new RuntimeReceiptStore(root);var path=store.Write(new RuntimeReceipt{Operation="check",Status="accepted",CandidateCount=1,ValidCount=1});Assert.True(File.Exists(path));Assert.Single(store.List());Assert.Empty(Directory.GetFiles(Path.Combine(root,"receipts"),"*.tmp"));Assert.Contains("comfy-quest-runtime-receipt/v1",File.ReadAllText(path));}finally{Directory.Delete(root,true);}}
  [Fact] public void RuntimeReceiptIdsUseInvariantUtcDigits(){var root=Path.Combine(Path.GetTempPath(),"comfy-receipt-"+Guid.NewGuid().ToString("N"));var original=CultureInfo.CurrentCulture;try{CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo("ar-SA");var receipt=new RuntimeReceipt{AtUtc=new DateTimeOffset(2026,8,18,3,2,3,4,TimeSpan.FromHours(2)),Operation="check",Status="accepted"};var path=new RuntimeReceiptStore(root).Write(receipt);Assert.Matches("^20260818T010203004Z-[0-9a-f]{32}\\.json$",Path.GetFileName(path));Assert.Equal(Path.GetFileNameWithoutExtension(path),receipt.Id);}finally{CultureInfo.CurrentCulture=original;if(Directory.Exists(root))Directory.Delete(root,true);}}
  [Fact] public void OldRuntimeReceiptRoundTripsWithAdditiveFieldsOmitted(){var json=File.ReadAllText(Fixture("runtime-receipt-v1.json"));var receipt=JsonConvert.DeserializeObject<RuntimeReceipt>(json);Assert.Equal("comfy-quest-runtime-receipt/v1",receipt.Schema);Assert.Null(receipt.ActivationId);Assert.Null(receipt.CorrelationId);Assert.Null(receipt.StageEnteredUtc);Assert.Null(receipt.Evidence);Assert.Null(receipt.RejectedEvidence);var oldRoundTrip=JsonConvert.SerializeObject(receipt);foreach(var field in new[]{"activation_id","correlation_id","stage_entered_utc","evidence","rejected_evidence"})Assert.DoesNotContain("\""+field+"\"",oldRoundTrip);receipt.ActivationId="act-19700101T000000000Z-deadbeef";receipt.CorrelationId="evt-0123456789ab";receipt.StageEnteredUtc=DateTimeOffset.UnixEpoch;receipt.Evidence=new TriggerClauseTrace{Op="EVENT",Event="kill",Satisfied=true,Current=1,Required=1};receipt.RejectedEvidence=new[]{new RejectedTransitionEvidence{TransitionId="other",Evidence=new TriggerClauseTrace{Op="EVENT",Event="hit",Satisfied=false,Current=0,Required=1}}};var populated=JsonConvert.DeserializeObject<RuntimeReceipt>(JsonConvert.SerializeObject(receipt));Assert.Equal(receipt.ActivationId,populated.ActivationId);Assert.Equal(receipt.CorrelationId,populated.CorrelationId);Assert.Equal(receipt.StageEnteredUtc,populated.StageEnteredUtc);Assert.True(populated.Evidence.Satisfied);Assert.Equal("other",Assert.Single(populated.RejectedEvidence).TransitionId);}
  [Fact] public void ExplainIsDeterministicAndAgreesWithMatchesForEveryOperator(){var at=DateTimeOffset.UnixEpoch;var history=new[]{new RuntimeEvent{Name="hit",Target="Troll",At=at,Fields=new Dictionary<string,string>{{"actor_role","peer"}}},new RuntimeEvent{Name="hit",Target="Troll",At=at.AddSeconds(2),Fields=new Dictionary<string,string>{{"actor_role","peer"}}},new RuntimeEvent{Name="kill",Target="Troll",At=at.AddSeconds(3)}};var hit=new TriggerExpression{Op="EVENT",Event="hit",Target="Troll",Where=new(){{"actor_role","peer"}}};var kill=new TriggerExpression{Op="EVENT",Event="kill",Target="Troll"};var miss=new TriggerExpression{Op="EVENT",Event="hit",Target="Greydwarf"};var cases=new[]{hit,miss,new TriggerExpression{Op="ANY",Children=new(){miss,kill}},new TriggerExpression{Op="ANY",Children=new(){miss,new(){Op="EVENT",Event="missing"}}},new TriggerExpression{Op="ALL",Children=new(){hit,kill}},new TriggerExpression{Op="ALL",Children=new(){hit,miss}},new TriggerExpression{Op="COUNT",Count=2,Children=new(){hit}},new TriggerExpression{Op="COUNT",Count=3,Children=new(){hit}},new TriggerExpression{Op="SEQUENCE",Children=new(){hit,kill}},new TriggerExpression{Op="SEQUENCE",Children=new(){kill,hit}},new TriggerExpression{Op="COUNT",Count=1,WithinSeconds=1,Children=new(){hit}}};foreach(var expression in cases){var expected=TriggerEvaluator.Matches(expression,history);var first=TriggerEvaluator.Explain(expression,history);var second=TriggerEvaluator.Explain(expression,history);Assert.Equal(expected,first.Satisfied);Assert.Equal(JsonConvert.SerializeObject(first),JsonConvert.SerializeObject(second));}var count=TriggerEvaluator.Explain(cases[6],history);Assert.Equal(2,count.Current);Assert.Equal(2,count.Required);var sequence=TriggerEvaluator.Explain(cases[8],history);Assert.Equal(2,sequence.SequenceIndex);Assert.Equal(1,TriggerEvaluator.Explain(cases[10],history).WithinSeconds);var nestedWindow=new TriggerExpression{Op="ALL",Children=new(){new(){Op="EVENT",Event="hit",WithinSeconds=1}}};var nestedTrace=TriggerEvaluator.Explain(nestedWindow,history);Assert.Equal(TriggerEvaluator.Matches(nestedWindow,history),nestedTrace.Satisfied);Assert.Null(Assert.Single(nestedTrace.Children).WithinSeconds);var overshoot=new TriggerExpression{Op="COUNT",Count=1,Children=new(){hit}};var measured=TriggerEvaluator.Measure(overshoot,history);var explained=TriggerEvaluator.Explain(overshoot,history);Assert.Equal(measured.Current,explained.Current);Assert.Equal(measured.Required,explained.Required);Assert.Equal(1,explained.Current);}
  [Fact] public void ExplainKeepsRelevantWhereActualsAndEnforcesEvidenceBounds(){var where=Enumerable.Range(0,12).ToDictionary(x=>$"field-{x:00}",x=>$"value-{x:00}",StringComparer.Ordinal);var expression=new TriggerExpression{Op="EVENT",Event="signal",Where=where};var history=new[]{new RuntimeEvent{Name="signal",At=DateTimeOffset.UnixEpoch,Fields=where}};var bounded=TriggerEvaluator.Explain(expression,history);Assert.True(bounded.Satisfied);Assert.Equal(TriggerEvaluator.MaxTraceWhereEntries,bounded.Where.Count);Assert.True(bounded.Truncated);var mismatchedFields=new Dictionary<string,string>(where,StringComparer.Ordinal);mismatchedFields["field-11"]="wrong";var cappedMismatch=TriggerEvaluator.Explain(expression,new[]{new RuntimeEvent{Name="signal",At=DateTimeOffset.UnixEpoch,Fields=mismatchedFields}});var failed=Assert.Single(cappedMismatch.Where,item=>!item.Satisfied);Assert.Equal("field-11",failed.Field);Assert.Equal("value-11",failed.Expected);Assert.Equal("wrong",failed.Actual);Assert.True(cappedMismatch.Truncated);var latest=TriggerEvaluator.Explain(new TriggerExpression{Op="EVENT",Event="signal",Where=new(){{"state","expected"}}},new[]{new RuntimeEvent{Name="signal",At=DateTimeOffset.UnixEpoch,Fields=new Dictionary<string,string>{{"state","old"}}},new RuntimeEvent{Name="signal",At=DateTimeOffset.UnixEpoch.AddSeconds(1),Fields=new Dictionary<string,string>{{"state","latest"}}}});Assert.Equal("latest",Assert.Single(latest.Where).Actual);var large=new TriggerExpression{Op="ALL",Children=Enumerable.Range(0,128).Select(x=>new TriggerExpression{Op="EVENT",Event=$"event-{x:000}",Target=new string('x',128),Where=Enumerable.Range(0,12).ToDictionary(y=>$"field-{y:00}",y=>new string('v',128),StringComparer.Ordinal)}).ToList()};var trace=TriggerEvaluator.Explain(large,Array.Empty<RuntimeEvent>());Assert.Equal(TriggerEvaluator.Matches(large,Array.Empty<RuntimeEvent>()),trace.Satisfied);Assert.True(trace.Truncated==true);Assert.All(TraceNodes(trace),node=>Assert.InRange(node.Where.Count,0,TriggerEvaluator.MaxTraceWhereEntries));Assert.True(Encoding.UTF8.GetByteCount(JsonConvert.SerializeObject(trace,Formatting.Indented))<=TriggerEvaluator.MaxTraceSerializedBytes);}
  [Fact]
  public void AdaptiveThresholdSchemaMovesAsOneClosedGate() {
    Assert.Equal(new[]{"time_since_progress","time_since_stage_entered"},AdaptiveMeasureCatalog.All.Select(x=>x.Name).OrderBy(x=>x,StringComparer.Ordinal));
    Assert.All(AdaptiveMeasureCatalog.All,x=>Assert.Equal("extended",x.Palette));
    var adaptive=Valid.Replace("\"when\":{\"op\":\"EVENT\",\"event\":\"kill\",\"target\":\"Troll\"}","\"when\":{\"op\":\"ALL\",\"children\":[{\"op\":\"EVENT\",\"event\":\"kill\",\"target\":\"Troll\"},{\"op\":\"THRESHOLD\",\"measure\":\"time_since_stage_entered\",\"comparison\":\"gte\",\"value\":30}]}");
    Assert.True(ExperienceCompiler.CompileJson(adaptive,new HashSet<string>{"kill"}).IsValid);
    Assert.Contains(ExperienceCompiler.CompileJson(adaptive.Replace("time_since_stage_entered","invented_measure"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="threshold.measure");
    Assert.Contains(ExperienceCompiler.CompileJson(adaptive.Replace("\"gte\"","\"lte\""),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="threshold.comparison");
    Assert.Contains(ExperienceCompiler.CompileJson(adaptive.Replace("\"value\":30","\"value\":0"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="threshold.value");
    var undriven=Valid.Replace("{\"op\":\"EVENT\",\"event\":\"kill\",\"target\":\"Troll\"}","{\"op\":\"THRESHOLD\",\"measure\":\"time_since_stage_entered\",\"comparison\":\"gte\",\"value\":30}");
    Assert.Contains(ExperienceCompiler.CompileJson(undriven,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="trigger.event_driver");
    var child=adaptive.Replace("\"value\":30}","\"value\":30,\"children\":[{\"op\":\"EVENT\",\"event\":\"kill\"}]}");
    Assert.Contains(ExperienceCompiler.CompileJson(child,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="threshold.children");
  }
  [Fact]
  public void AdaptiveThresholdUsesEventTimeAndExplainsActualVersusExpected() {
    var start=DateTimeOffset.Parse("2026-08-19T01:00:00Z");
    var history=new[]{new RuntimeEvent{Name="kill",Target="Troll",At=start.AddSeconds(45)}};
    var threshold=new TriggerExpression{Op="THRESHOLD",Measure="time_since_stage_entered",Comparison="gte",Value=30};
    var expression=new TriggerExpression{Op="ALL",Children=new(){new(){Op="EVENT",Event="kill",Target="Troll"},threshold}};
    var context=new TriggerEvaluationContext{At=history[0].At,StageEnteredUtc=start,LastProgressUtc=start.AddSeconds(20)};
    Assert.False(TriggerEvaluator.Matches(expression,history));
    Assert.True(TriggerEvaluator.Matches(expression,history,context));
    Assert.False(TriggerEvaluator.Matches(expression,history,new TriggerEvaluationContext{At=start.AddSeconds(29),StageEnteredUtc=start,LastProgressUtc=start}));
    var trace=TriggerEvaluator.Explain(expression,history,context);
    Assert.True(trace.Satisfied);
    Assert.Equal(2,trace.Current);
    Assert.Equal(2,trace.Required);
    var measured=Assert.Single(trace.Children,x=>x.Op=="THRESHOLD");
    Assert.Equal(30,measured.Current);
    Assert.Equal(30,measured.Required);
    var comparison=Assert.Single(measured.Where);
    Assert.Equal("time_since_stage_entered",comparison.Field);
    Assert.Equal(">= 30 seconds",comparison.Expected);
    Assert.Equal("45 seconds",comparison.Actual);
    Assert.True(comparison.Satisfied);
    Assert.Equal(JsonConvert.SerializeObject(trace),JsonConvert.SerializeObject(TriggerEvaluator.Explain(expression,history,context)));
    var quiet=new TriggerExpression{Op="THRESHOLD",Measure="time_since_progress",Comparison="gte",Value=30};
    Assert.False(TriggerEvaluator.Matches(quiet,history,context));
    context.At=start.AddSeconds(51);
    Assert.True(TriggerEvaluator.Matches(quiet,history,context));
  }
  [Theory][InlineData(CharmTargetKind.PlayerBuiltPiece)][InlineData(CharmTargetKind.Sign)][InlineData(CharmTargetKind.ItemStand)][InlineData(CharmTargetKind.DedicatedCharm)] public void PrivateHostCanInscribeAllowlistedOwnedTargets(CharmTargetKind kind){var world=new WorldAuthority{IsPrivateWorld=true,IsListenHost=true};Assert.True(CharmPolicy.CanInscribe(world,new CharmTarget{Kind=kind,HasZdo=true,LocallyOwned=true}).Allowed);}
  [Theory][InlineData(CharmTargetKind.Creature)][InlineData(CharmTargetKind.Portal)][InlineData(CharmTargetKind.Terrain)][InlineData(CharmTargetKind.Container)][InlineData(CharmTargetKind.DroppedItem)] public void UnsafeCharmTargetsFailClosed(CharmTargetKind kind){var world=new WorldAuthority{IsPrivateWorld=true,IsSolo=true};Assert.Equal("charm_target_not_allowlisted",CharmPolicy.CanInscribe(world,new CharmTarget{Kind=kind,HasZdo=true,LocallyOwned=true}).Diagnostic);}
  [Fact] public void PeerMutationFailsClosedButReferenceRemainsInspectable(){var world=new WorldAuthority{IsPrivateWorld=true,IsPeerClient=true};Assert.Equal("mutation_authority_unavailable",CharmPolicy.CanMutate(world).Diagnostic);Assert.True(CharmPolicy.ValidateReference(new CharmReference{PackId="demo",ExperienceId="quest",BindingId="default",Version="1.0.0",ContentHash=new string('a',64)}).Allowed);}
  [Fact] public void OmenLiveFixtureIsCertifiedAndHashExact(){var root=Path.Combine(AppContext.BaseDirectory,"LiveTest");var experience=File.ReadAllText(Path.Combine(root,"experiences","omen-inscription.json"));Assert.True(ExperienceCompiler.CompileJson(experience,CanonicalEventCatalog.CreateSet()).IsValid);var bytes=File.ReadAllBytes(Path.Combine(root,"experiences","omen-inscription.json"));var hash=QuestPackContent.ComputeHash(new[]{new KeyValuePair<string,byte[]>("experiences/omen-inscription.json",bytes)});var manifest=JsonConvert.DeserializeObject<QuestPackManifest>(File.ReadAllText(Path.Combine(root,"manifest.json")));Assert.Equal(manifest.ContentHash,hash);}
  [Fact] public void ActionClaimsSurviveDuplicatesAndReload(){var root=Path.Combine(Path.GetTempPath(),"comfy-actions-"+Guid.NewGuid().ToString("N"));try{var key="world|player|zdo|hash|stage|transition|action";Assert.True(new ActionExecutionLedger(root).TryClaim(key));Assert.False(new ActionExecutionLedger(root).TryClaim(key));Assert.True(new ActionExecutionLedger(root).TryClaim(key+"-2"));}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowUsesEventTimeForCreationAdvanceAndReplay(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();var id=new WorkflowIdentity{WorldId="world",CharacterId="hero",BindingZdo="1:2",ContentHash=new string('a',64)};var created=DateTimeOffset.Parse("2026-08-18T01:00:00Z");var advanced=created.AddMinutes(2);var finished=advanced.AddMinutes(3);var store=new WorkflowStateStore(root);Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="ignored",At=created}));var initial=store.Get(id);Assert.Equal(created,initial.StageEnteredUtc);Assert.Equal(created,initial.LastEventUtc);var first=store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=advanced});Assert.Equal("first-hit",first.Transition.Id);Assert.Equal(advanced,first.EventAt);Assert.False(first.IsPendingReplay);Assert.DoesNotContain("EventAt",JsonConvert.SerializeObject(first));var replay=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=advanced.AddSeconds(30)});Assert.True(replay.IsPendingReplay);Assert.Equal(advanced,replay.EventAt);Assert.True(new WorkflowStateStore(root).Complete(replay));var second=new WorkflowStateStore(root).Get(id);Assert.Equal("second",second.StageId);Assert.Equal(advanced,second.StageEnteredUtc);Assert.Equal(advanced,second.LastEventUtc);var finish=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=finished});Assert.Equal("finish",finish.Transition.Id);Assert.True(new WorkflowStateStore(root).Complete(finish));var complete=new WorkflowStateStore(root).Get(id);Assert.Equal("complete",complete.Outcome);Assert.Equal(advanced,complete.StageEnteredUtc);Assert.Equal(finished,complete.LastEventUtc);Assert.Null(new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=finished.AddSeconds(1)}));}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowPersistsPendingTransitionAndAdvancesAfterCompletion(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();var id=new WorkflowIdentity{WorldId="world",CharacterId="hero",BindingZdo="1:2",ContentHash=new string('a',64)};var at=DateTimeOffset.Parse("2026-08-18T04:00:00Z");var first=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=at});Assert.Equal("first-hit",first.Transition.Id);Assert.False(first.IsPendingReplay);var replay=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=at.AddSeconds(1)});Assert.True(replay.IsPendingReplay);Assert.Equal(at,replay.EventAt);Assert.True(new WorkflowStateStore(root).Complete(replay));Assert.Equal("second",new WorkflowStateStore(root).Get(id).StageId);var finish=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=at.AddSeconds(2)});Assert.Equal("finish",finish.Transition.Id);Assert.True(new WorkflowStateStore(root).Complete(finish));Assert.Equal("complete",new WorkflowStateStore(root).Get(id).Outcome);Assert.Null(new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=at.AddSeconds(3)}));}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowFailsClosedWhenPendingEventTimeIsMissing(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();var id=new WorkflowIdentity{WorldId="world",CharacterId="hero",BindingZdo="1:2",ContentHash="hash"};var at=DateTimeOffset.Parse("2026-08-18T05:00:00Z");var decision=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=at});decision.EventAt=null;Assert.False(new WorkflowStateStore(root).Complete(decision));Assert.Equal("first",new WorkflowStateStore(root).Get(id).StageId);var replay=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=at.AddMinutes(1)});Assert.Equal(at,replay.EventAt);Assert.True(new WorkflowStateStore(root).Complete(replay));var legacyRoot=Path.Combine(root,"legacy");var state=Directory.CreateDirectory(Path.Combine(legacyRoot,"state")).FullName;File.Copy(Fixture("workflow-state-v1-pending-without-event-time.json"),Path.Combine(state,"workflow-states.json"));var legacyId=new WorkflowIdentity{WorldId="pending-world",CharacterId="pending-hero",BindingZdo="pending-zdo",ContentHash="pending-hash"};var legacyStore=new WorkflowStateStore(legacyRoot);Assert.Null(legacyStore.Begin(legacyId,doc,new RuntimeEvent{Name="piece_damaged",At=at}));var pending=legacyStore.Get(legacyId);Assert.NotNull(pending.History);Assert.Empty(pending.History);Assert.Equal("first-hit",pending.PendingTransitionId);Assert.Equal("first",pending.StageId);}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowUsesPriorityThenStableId(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();doc.Stages[0].Transitions.Add(new ExperienceTransition{Id="alternate",Priority=1,When=new TriggerExpression{Op="EVENT",Event="piece_damaged"},Outcome="fail"});var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};Assert.Equal("first-hit",new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow}).Transition.Id);}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowAccumulatesBoundedCountAcrossEvents(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();doc.Stages[0].Transitions[0].When=new TriggerExpression{Op="COUNT",Count=2,Children=new(){new(){Op="EVENT",Event="piece_damaged"}}};var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};var store=new WorkflowStateStore(root);Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow}));Assert.Equal("first-hit",store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow.AddSeconds(1)}).Transition.Id);}finally{Directory.Delete(root,true);}}
  [Fact] public void OldWorkflowStateLoadsWithNullTimestampsAndAdvances(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var state=Directory.CreateDirectory(Path.Combine(root,"state")).FullName;File.Copy(Fixture("workflow-state-v1.json"),Path.Combine(state,"workflow-states.json"));var id=new WorkflowIdentity{WorldId="old-world",CharacterId="old-hero",BindingZdo="old-zdo",ContentHash="old-hash"};var store=new WorkflowStateStore(root);var old=store.Get(id);Assert.Equal("first",old.StageId);Assert.Null(old.StageEnteredUtc);Assert.Null(old.LastEventUtc);Assert.Null(old.LastProgressUtc);var at=DateTimeOffset.Parse("2026-08-18T02:00:00Z");var decision=store.Begin(id,TwoStage(),new RuntimeEvent{Name="piece_damaged",At=at});Assert.Equal(at,decision.EventAt);Assert.True(store.Complete(decision));var updated=store.Get(id);Assert.Equal("second",updated.StageId);Assert.Equal(at,updated.StageEnteredUtc);Assert.Equal(at,updated.LastEventUtc);Assert.Equal(at,updated.LastProgressUtc);}finally{Directory.Delete(root,true);}}
  [Fact]
  public void WorkflowPersistsTemporalProgressFromEventTimeOnly() {
    var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));
    try {
      var doc=TwoStage();
      doc.Stages[0].Transitions[0].When=new TriggerExpression{Op="ALL",Children=new(){new(){Op="EVENT",Event="piece_damaged"},new(){Op="THRESHOLD",Measure="time_since_stage_entered",Comparison="gte",Value=30},new(){Op="THRESHOLD",Measure="time_since_progress",Comparison="gte",Value=20}}};
      var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};
      var start=DateTimeOffset.Parse("2026-08-19T02:00:00Z");
      var store=new WorkflowStateStore(root);
      Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="ignored",At=start}));
      Assert.Equal(start,store.Get(id).LastProgressUtc);
      Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="ignored",At=start.AddSeconds(25)}));
      Assert.Equal(start,store.Get(id).LastProgressUtc);
      var decision=store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=start.AddSeconds(31)});
      Assert.NotNull(decision);
      Assert.Equal(start,decision.EvaluationContext.StageEnteredUtc);
      Assert.Equal(start,decision.EvaluationContext.LastProgressUtc);
      Assert.True(store.Complete(decision));
      var advanced=store.Get(id);
      Assert.Equal(start.AddSeconds(31),advanced.StageEnteredUtc);
      Assert.Equal(start.AddSeconds(31),advanced.LastEventUtc);
      Assert.Equal(start.AddSeconds(31),advanced.LastProgressUtc);
    } finally { Directory.Delete(root,true); }
  }
  [Fact]
  public void NoProgressThresholdResetsOnlyWhenStructuralEventProgressAdvances() {
    var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));
    try {
      var doc=TwoStage();
      doc.Stages[0].Transitions[0].When=new TriggerExpression{Op="ALL",Children=new(){new(){Op="COUNT",Count=2,Children=new(){new(){Op="EVENT",Event="piece_damaged"}}},new(){Op="THRESHOLD",Measure="time_since_progress",Comparison="gte",Value=20}}};
      var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="quiet"};
      var start=DateTimeOffset.Parse("2026-08-19T03:00:00Z");
      var store=new WorkflowStateStore(root);
      Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="ignored",At=start}));
      Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=start.AddSeconds(31)}));
      Assert.Equal(start.AddSeconds(31),store.Get(id).LastProgressUtc);
      Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=start.AddSeconds(40)}));
      Assert.Equal(start.AddSeconds(40),store.Get(id).LastProgressUtc);
      var decision=store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=start.AddSeconds(61)});
      Assert.NotNull(decision);
      Assert.Equal(start.AddSeconds(40),decision.EvaluationContext.LastProgressUtc);
    } finally { Directory.Delete(root,true); }
  }
  [Fact] public void DurableTimersSurviveReloadUntilAcknowledged(){var root=Path.Combine(Path.GetTempPath(),"comfy-timer-"+Guid.NewGuid().ToString("N"));try{var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};var now=DateTimeOffset.UtcNow;new DurableTimerStore(root).Start(id,"bell",now.AddSeconds(2));Assert.Empty(new DurableTimerStore(root).Due(now));var due=Assert.Single(new DurableTimerStore(root).Due(now.AddSeconds(3)));Assert.Equal("bell",due.TimerId);Assert.Single(new DurableTimerStore(root).Due(now.AddSeconds(4)));Assert.True(new DurableTimerStore(root).Acknowledge(due.Key));Assert.Empty(new DurableTimerStore(root).Due(now.AddSeconds(5)));}finally{Directory.Delete(root,true);}}
  [Fact] public void EngineTimerSignalRequiresStableTimerClause(){var valid=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"timer_elapsed\",\"where\":{\"timer_id\":\"bell\"}");Assert.True(ExperienceCompiler.CompileJson(valid,new HashSet<string>{"kill"}).IsValid);var invalid=valid.Replace("\"where\":{\"timer_id\":\"bell\"}","\"where\":{}");Assert.Contains(ExperienceCompiler.CompileJson(invalid,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="timer.id");}
  [Fact] public void CooperativeChatRequiresClosedActorRole(){var valid=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"chat_received\",\"target\":\"shout\",\"where\":{\"actor_role\":\"peer\"}");Assert.True(ExperienceCompiler.CompileJson(valid,new HashSet<string>{"kill"}).IsValid);var missing=valid.Replace(",\"where\":{\"actor_role\":\"peer\"}","");Assert.Contains(ExperienceCompiler.CompileJson(missing,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="chat.actor_role");var rawIdentity=valid.Replace("\"peer\"","\"123456789\"");Assert.Contains(ExperienceCompiler.CompileJson(rawIdentity,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="chat.actor_role");}
  [Fact] public void CooperativeEventsPersistRoleOnly(){Assert.True(CooperativeEventContract.TryCreateInboundChat(22,11,"Shout","secret words",DateTimeOffset.UnixEpoch,out var peer));Assert.Equal("chat_received",peer.Name);Assert.Equal("shout",peer.Target);Assert.Equal("peer",CooperativeEventContract.ActorRole(peer));Assert.Null(peer.SourceId);Assert.DoesNotContain("secret",JsonConvert.SerializeObject(peer));Assert.True(CooperativeEventContract.TryCreateInboundChat(11,11,"Shout","host words",DateTimeOffset.UnixEpoch,out var host));Assert.Equal("listen_host",CooperativeEventContract.ActorRole(host));Assert.False(CooperativeEventContract.TryCreateInboundChat(22,11,"Whisper","private",DateTimeOffset.UnixEpoch,out _));var placed=CooperativeEventContract.CreateHostPlacement("sign(Clone)",DateTimeOffset.UnixEpoch);Assert.Equal("sign",placed.Target);Assert.Equal("listen_host",CooperativeEventContract.ActorRole(placed));}
  [Fact] public void NestedChatWitnessesEmitExactlyOnce(){var dedupe=new CooperativeChatDedupe();Assert.True(dedupe.ShouldEmit(22,"Shout","one","OnNew",10));Assert.False(dedupe.ShouldEmit(22,"Shout","one","RPC",10.1));Assert.True(dedupe.ShouldEmit(22,"Shout","one","OnNew",10.2));Assert.True(dedupe.ShouldEmit(22,"Shout","two","RPC",10.3));}
  [Fact] public void BindingTargetKindsUseClosedRegistry(){var valid=Valid.Replace("\"experience_id\":\"hello\"","\"experience_id\":\"hello\",\"target_kinds\":[\"sign\"]");Assert.True(ExperienceCompiler.CompileJson(valid,new HashSet<string>{"kill"}).IsValid);var invalid=valid.Replace("\"sign\"","\"portal\"");Assert.Contains(ExperienceCompiler.CompileJson(invalid,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="binding.target_kind");}
  [Fact] public void MutationActionsUseClosedPrefabAndQuantityRegistry(){var grant=Valid.Replace("{\"id\":\"say\",\"type\":\"message\",\"text\":\"Skal!\"}","{\"id\":\"say\",\"type\":\"grant_item\",\"item\":\"Wood\",\"quantity\":50}");Assert.True(ExperienceCompiler.CompileJson(grant,new HashSet<string>{"kill"}).IsValid);Assert.Contains(ExperienceCompiler.CompileJson(grant.Replace("\"Wood\"","\"SwordCheat\""),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="grant_item_not_allowlisted");Assert.Contains(ExperienceCompiler.CompileJson(grant.Replace(":50",":51"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="grant_quantity_exceeds_stack_cap");var spawn=Valid.Replace("{\"id\":\"say\",\"type\":\"message\",\"text\":\"Skal!\"}","{\"id\":\"say\",\"type\":\"spawn\",\"kind\":\"creature\",\"prefab\":\"Greyling\",\"count\":1,\"radius\":3}");Assert.True(ExperienceCompiler.CompileJson(spawn,new HashSet<string>{"kill"}).IsValid);Assert.Contains(ExperienceCompiler.CompileJson(spawn.Replace("\"Greyling\"","\"Troll\""),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="spawn_prefab_not_allowlisted");}
  [Fact] public void SpawnLedgerPersistsExactZdoIdentityAndRemovesOnlySelectedRecords(){var root=Path.Combine(Path.GetTempPath(),"comfy-spawn-"+Guid.NewGuid().ToString("N"));try{var store=new SpawnExecutionStore(root);store.Record(new SpawnedObject{ActionKey="owner|stage-one|transition|spawn",ContentHash="h",ActionId="spawn",UserId=7,ObjectId=9});store.Record(new SpawnedObject{ActionKey="other|stage|transition|spawn",ContentHash="h",ActionId="spawn",UserId=7,ObjectId=10});var one=Assert.Single(new SpawnExecutionStore(root).ForOwnerAction("owner","spawn"));Assert.Equal((uint)9,one.ObjectId);new SpawnExecutionStore(root).Remove(new[]{one});Assert.Empty(new SpawnExecutionStore(root).ForOwnerAction("owner","spawn"));Assert.Single(new SpawnExecutionStore(root).ForOwnerAction("other","spawn"));}finally{Directory.Delete(root,true);}}
  static ExperienceDocument TwoStage()=>new(){EntryStage="first",Stages=new(){new(){Id="first",Transitions=new(){new(){Id="first-hit",Priority=10,When=new(){Op="EVENT",Event="piece_damaged"},NextStage="second"}}},new(){Id="second",Transitions=new(){new(){Id="finish",Priority=10,When=new(){Op="EVENT",Event="piece_damaged"},Outcome="complete"}}}}};
  static IEnumerable<TriggerClauseTrace> TraceNodes(TriggerClauseTrace trace){yield return trace;foreach(var child in trace.Children??new())foreach(var nested in TraceNodes(child))yield return nested;}
  static ActiveSet ReadActive(string root)=>JsonConvert.DeserializeObject<ActiveSet>(File.ReadAllText(Path.Combine(root,"active","active-set.json")));
  static string Fixture(string name)=>Path.Combine(AppContext.BaseDirectory,"Fixtures",name);
  static void WritePack(string path,string version,string experience){using var zip=ZipFile.Open(path,ZipArchiveMode.Create);using(var writer=new StreamWriter(zip.CreateEntry("manifest.json").Open()))writer.Write($"{{\"schema\":\"comfy-quest-pack/v2\",\"pack_id\":\"demo\",\"version\":\"{version}\"}}");using(var writer=new StreamWriter(zip.CreateEntry("experiences/demo.json").Open()))writer.Write(experience);}
}
