#!/usr/bin/env python3
"""Generate the in-game journal from the atlas plus the written pages.

Two halves, joined here so they cannot drift apart:

  journal-pages.json          the drafted half — prose a person wrote
  valheim-event-atlas.json    the verified half — seams read from the DLL
  quest-capability-manifest   the generated creator-event and profile policy

A page can therefore never claim a seam the extractor does not see, and adding a
hook updates its page's seam list for free. That is the confidence contract from
docs/guides/custom-fields/STARTHERE.md applied to a UI instead of a document.

Seams the lab actually hooks are marked, so a reader can tell "this exists in the
game" from "this lab will show it to you" — a distinction that is invisible in a
list of method names and matters enormously to somebody deciding what to build.

  python tools/component-packets/generate_journal.py

Writes network/mod/ComfyQuestLab/Ui/LabJournal.g.cs
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
ATLAS = os.path.join(HERE, "samples", "valheim-event-atlas.json")
CAPABILITIES = os.path.join(HERE, "samples", "quest-capability-manifest.json")
PAGES = os.path.join(HERE, "journal-pages.json")
PATCHES = os.path.join(REPO, "network", "mod", "ComfyQuestLab", "Patches")
OUT = os.path.join(REPO, "network", "mod", "ComfyQuestLab", "Ui", "LabJournal.g.cs")

CATEGORY_CONST = {
    "combat": "LabCategory.Combat", "harvest": "LabCategory.Harvest",
    "inventory": "LabCategory.Inventory", "building": "LabCategory.Building",
    "crafting": "LabCategory.Crafting", "progression": "LabCategory.Progression",
    "world": "LabCategory.World", "social": "LabCategory.Social",
}
ORDER = ["combat", "harvest", "inventory", "building", "crafting", "progression",
         "world", "social"]

atlas = json.load(open(ATLAS, encoding="utf-8"))
capabilities = json.load(open(CAPABILITIES, encoding="utf-8"))
_doc = json.load(open(PAGES, encoding="utf-8"))
pages = _doc["pages"]
incantations = _doc["incantations"]

# Which seams this build actually hooks, read from the patch sources rather than
# assumed — the same source of truth check_lab_patches.py uses.
hooked = set()
call = re.compile(r'(?:LabPatching\.TryPatch|TryAtlasPatch)\(\s*harmony,\s*typeof\(([A-Za-z0-9_.]+)\)\s*,\s*"([A-Za-z0-9_]+)"')
for name in os.listdir(PATCHES):
    if name.endswith(".cs"):
        for m in call.finditer(open(os.path.join(PATCHES, name), encoding="utf-8").read()):
            hooked.add(f"{m.group(1)}.{m.group(2)}")

# Seam -> capability rows, collapsing overloads (a page lists a method once).
capabilities_by_method = {}
for capability in capabilities["Signatures"]:
    capabilities_by_method.setdefault(capability["MethodId"], []).append(capability)

seams_by_cat = {}
for s in atlas["Seams"]:
    seams_by_cat.setdefault(s["Category"], {})[s["Id"]] = capabilities_by_method[s["Id"]]


def capability_verdict(rows):
    safe_events = sorted({row["CanonicalEvent"] for row in rows if row["CreatorSafe"]})
    if safe_events:
        return "bindable: " + ", ".join(safe_events)
    if any(row["Profile"] != "disabled" for row in rows):
        return "diagnostic only — never bindable"
    return "intentionally disabled"


def cs(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// <auto-generated>",
    "//   Generated by tools/component-packets/generate_journal.py from",
    "//   journal-pages.json (written prose), samples/valheim-event-atlas.json (assembly",
    "//   seams), and samples/quest-capability-manifest.json (creator policy). Do not edit",
    "//   by hand — edit the source files",
    "//   or rerun the extractor, then regenerate.",
    "// </auto-generated>",
    "",
    "namespace ComfyQuestLab;",
    "",
    "using System.Collections.Generic;",
    "",
    "/// <summary>The tome. One page per school: what it covers, something to go and try,",
    "/// and the thing that would otherwise cost an hour.",
    "///",
    "/// Every spell listed is something the world genuinely answers to — the list is",
    "/// joined from the atlas at generation time, so a page cannot name something the game",
    "/// does not do. Spells this build can witness are listed first, because those are the",
    "/// ones a student can go and see.</summary>",
    "public static class LabJournal {",
    "  public sealed class Page {",
    "    public string Category;",
    "    public string Title;",
    "    public string[] What;",
    "    public string[] Try;",
    "    public string[] Watch;",
    "    public Spell[] Spells;",
    "  }",
    "",
    "  /// <summary>One thing the world answers to.",
    "  ///",
    "  /// <see cref=\"Name\"/> is what it is, in words. <see cref=\"TrueName\"/> is the method",
    "  /// a mod would have to reach for — shown only when asked, because a student does not",
    "  /// need to know how a spell works in order to cast one. Knowing a thing's true name",
    "  /// is what gives you power over it, and here that is not a metaphor: the true name",
    "  /// is literally what you would write code against.</summary>",
    "  public sealed class Spell {",
    "    public string Name;",
    "    public string TrueName;",
    "    public string Verdict;",
    "    /// <summary>True when this build has an explicit runtime integration. False means",
    "    /// policy intentionally leaves the query or cheat surface disabled.</summary>",
    "    public bool Bound;",
    "  }",
    "",
    "  public static readonly List<Page> Pages = new List<Page> {",
]

total_seams = 0
for cat in ORDER:
    page = pages[cat]
    seams = seams_by_cat.get(cat, {})
    total_seams += len(seams)
    rows = []
    for seam_id in sorted(seams, key=lambda s: (s not in hooked, incantations.get(s, s))):
        rows.append((incantations.get(seam_id, seam_id), seam_id,
                     capability_verdict(seams[seam_id]), seam_id in hooked))

    lines.append("    new Page {")
    lines.append(f"      Category = {CATEGORY_CONST[cat]},")
    lines.append(f"      Title = {cs(page['title'])},")
    for field, key in (("What", "what"), ("Try", "try"), ("Watch", "watch")):
        body = ", ".join(cs(l) for l in page[key])
        lines.append(f"      {field} = new[] {{ {body} }},")
    lines.append("      Spells = new[] {")
    for name, true_name, verdict, bound in rows:
        lines.append(f"        new Spell {{ Name = {cs(name)}, TrueName = {cs(true_name)}, "
                     f"Verdict = {cs(verdict)}, Bound = {str(bound).lower()} }},")
    lines.append("      },")
    lines.append("    },")

lines += [
    "  };",
    "",
    "  public static Page For(string category) {",
    "    foreach (Page page in Pages) {",
    "      if (page.Category == category) {",
    "        return page;",
    "      }",
    "    }",
    "    return Pages[0];",
    "  }",
    "}",
    "",
]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines))

print(f"  {OUT}")
integrated_atlas_methods = len(hooked & set(capabilities_by_method))
print(
    f"  {len(ORDER)} pages, {total_seams} spells named, "
    f"{integrated_atlas_methods} atlas methods integrated by this build"
)
