#!/usr/bin/env python3
"""Generate the mod's seam catalog from the event atlas.

One source of truth. The atlas is extracted from assembly_valheim.dll; this projects
it into a C# lookup the lab compiles in, so a patch names its seam and the catalog
answers "can a quest fire on this?". Without it every patch file would restate a
verdict the atlas already knows, and the two would drift the first time a hook landed.

  python tools/component-packets/generate_seam_catalog.py

Reads  tools/component-packets/samples/valheim-event-atlas.json
Writes network/mod/ComfyQuestLab/Core/LabSeamCatalog.g.cs
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
ATLAS = os.path.join(HERE, "samples", "valheim-event-atlas.json")
OUT = os.path.join(REPO, "network", "mod", "ComfyQuestLab", "Core", "LabSeamCatalog.g.cs")

USABILITY_CONST = {
    "today": "LabUsability.Today",
    "produces-event-no-trigger": "LabUsability.ProducesEventNoTrigger",
    "lab-candidate": "LabUsability.LabCandidate",
    "not-patchable": "LabUsability.LabCandidate",
}
CATEGORY_CONST = {
    "combat": "LabCategory.Combat", "harvest": "LabCategory.Harvest",
    "inventory": "LabCategory.Inventory", "building": "LabCategory.Building",
    "crafting": "LabCategory.Crafting", "progression": "LabCategory.Progression",
    "world": "LabCategory.World", "social": "LabCategory.Social",
}

atlas = json.load(open(ATLAS, encoding="utf-8"))

# One row per seam id. Overloads share an id and a verdict, so collapse them; the
# distinction that matters at runtime is which method fired, and the patch knows that.
seams = {}
for s in atlas["Seams"]:
    seams.setdefault(s["Id"], (s["Category"], s["QuestUsable"]))

lines = [
    "// <auto-generated>",
    "//   Generated by tools/component-packets/generate_seam_catalog.py from",
    "//   samples/valheim-event-atlas.json. Do not edit by hand: rerun the extractor",
    "//   (--events) and then the generator, and commit both.",
    "//",
    f"//   Source: {atlas['Source']}",
    f"//   Seams: {len(seams)} across {len(atlas['Categories'])} categories.",
    "// </auto-generated>",
    "",
    "namespace ComfyQuestLab;",
    "",
    "using System.Collections.Generic;",
    "",
    "/// <summary>What the event atlas knows about each seam, compiled in.",
    "///",
    "/// A patch names the seam it hooked; this answers which category it belongs to and",
    "/// whether a quest can fire on it. Keeping the verdict here rather than in each patch",
    "/// file means regenerating the atlas updates the mod, instead of leaving ninety-one",
    "/// hand-copied answers to rot.</summary>",
    "public static class LabSeamCatalog {",
    "  public struct Entry {",
    "    public string Category;",
    "    public string Usability;",
    "  }",
    "",
    "  static readonly Dictionary<string, Entry> _seams = new Dictionary<string, Entry> {",
]

for seam_id in sorted(seams):
    category, usable = seams[seam_id]
    lines.append(
        f'    {{ "{seam_id}", new Entry {{ Category = {CATEGORY_CONST[category]}, '
        f'Usability = {USABILITY_CONST[usable]} }} }},')

lines += [
    "  };",
    "",
    "  public static int Count { get { return _seams.Count; } }",
    "",
    "  /// <summary>Every seam the atlas knows, whether or not this build hooks it.</summary>",
    "  public static IEnumerable<string> AllSeamIds { get { return _seams.Keys; } }",
    "",
    "  /// <summary>The honest answer for a seam id such as \"TreeBase.Damage\".",
    "  /// An unknown id reads as lab-candidate: if the atlas has never heard of it, a",
    "  /// quest certainly cannot fire on it.</summary>",
    "  public static string Usability(string seamId) {",
    "    Entry entry;",
    "    return _seams.TryGetValue(seamId, out entry) ? entry.Usability : LabUsability.LabCandidate;",
    "  }",
    "",
    "  public static string Category(string seamId) {",
    "    Entry entry;",
    "    return _seams.TryGetValue(seamId, out entry) ? entry.Category : LabCategory.Combat;",
    "  }",
    "",
    "  /// <summary>How many seams in a category a quest can fire on today. The journal",
    "  /// uses this to tell a builder where the useful ground is.</summary>",
    "  public static int UsableTodayIn(string category) {",
    "    int n = 0;",
    "    foreach (KeyValuePair<string, Entry> pair in _seams) {",
    "      if (pair.Value.Category == category && pair.Value.Usability == LabUsability.Today) {",
    "        n++;",
    "      }",
    "    }",
    "    return n;",
    "  }",
    "",
    "  public static int CountIn(string category) {",
    "    int n = 0;",
    "    foreach (KeyValuePair<string, Entry> pair in _seams) {",
    "      if (pair.Value.Category == category) {",
    "        n++;",
    "      }",
    "    }",
    "    return n;",
    "  }",
    "}",
    "",
]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines))

print(f"  {OUT}")
print(f"  {len(seams)} seams, {sum(1 for c, u in seams.values() if u == 'today')} usable today")
