#!/usr/bin/env python3
"""Generate the in-game journal from the atlas plus the written pages.

Two halves, joined here so they cannot drift apart:

  journal-pages.json          the drafted half — prose a person wrote
  valheim-event-atlas.json    the verified half — seams read from the DLL

A page can therefore never claim a seam the extractor does not see, and adding a
hook updates its page's seam list for free. That is the confidence contract from
docs/guides/custom-fields/STARTHERE.md applied to a UI instead of a document.

Seams the lab actually hooks are marked, so a reader can tell "this exists in the
game" from "this lab will show it to you" — a distinction that is invisible in a
list of method names and matters enormously to somebody deciding what to build.

  python tools/component-packets/generate_journal.py

Writes network/mod/ComfyQuestLab/Ui/LabJournal.g.cs
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
ATLAS = os.path.join(HERE, "samples", "valheim-event-atlas.json")
PAGES = os.path.join(HERE, "journal-pages.json")
PATCHES = os.path.join(REPO, "network", "mod", "ComfyQuestLab", "Patches")
OUT = os.path.join(REPO, "network", "mod", "ComfyQuestLab", "Ui", "LabJournal.g.cs")

CATEGORY_CONST = {
    "combat": "LabCategory.Combat", "harvest": "LabCategory.Harvest",
    "inventory": "LabCategory.Inventory", "building": "LabCategory.Building",
    "crafting": "LabCategory.Crafting", "progression": "LabCategory.Progression",
    "world": "LabCategory.World", "social": "LabCategory.Social",
}
ORDER = ["combat", "harvest", "inventory", "building", "crafting", "progression",
         "world", "social"]

atlas = json.load(open(ATLAS, encoding="utf-8"))
pages = json.load(open(PAGES, encoding="utf-8"))["pages"]

# Which seams this build actually hooks, read from the patch sources rather than
# assumed — the same source of truth check_lab_patches.py uses.
hooked = set()
call = re.compile(r'LabPatching\.TryPatch\(\s*harmony,\s*typeof\(([A-Za-z0-9_.]+)\)\s*,\s*"([A-Za-z0-9_]+)"')
for name in os.listdir(PATCHES):
    if name.endswith(".cs"):
        for m in call.finditer(open(os.path.join(PATCHES, name), encoding="utf-8").read()):
            hooked.add(f"{m.group(1)}.{m.group(2)}")

# Seam -> verdict, collapsing overloads (a page lists a seam once).
seams_by_cat = {}
for s in atlas["Seams"]:
    seams_by_cat.setdefault(s["Category"], {})[s["Id"]] = s["QuestUsable"]

VERDICT_SHORT = {
    "today": "quests can use this",
    "produces-event-no-trigger": "fires, but no trigger matches",
    "lab-candidate": "not wired to quests",
    "not-patchable": "not reachable",
}


def cs(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// <auto-generated>",
    "//   Generated by tools/component-packets/generate_journal.py from",
    "//   journal-pages.json (written prose) joined with samples/valheim-event-atlas.json",
    "//   (seams read from the game assembly). Do not edit by hand — edit the prose file",
    "//   or rerun the extractor, then regenerate.",
    "// </auto-generated>",
    "",
    "namespace ComfyQuestLab;",
    "",
    "using System.Collections.Generic;",
    "",
    "/// <summary>One page per category: what it covers, something to go and do, and the",
    "/// thing that would otherwise cost an hour. Seam lists come from the atlas, so a page",
    "/// cannot promise something the game does not have.</summary>",
    "public static class LabJournal {",
    "  public sealed class Page {",
    "    public string Category;",
    "    public string Title;",
    "    public string[] What;",
    "    public string[] Try;",
    "    public string[] Watch;",
    "    /// <summary>\"[x] TreeBase.Damage — quests can use this\". The [x] means this",
    "    /// build hooks it; [ ] means the seam exists in the game and the lab is not",
    "    /// showing it to you.</summary>",
    "    public string[] Seams;",
    "  }",
    "",
    "  public static readonly List<Page> Pages = new List<Page> {",
]

total_seams = 0
for cat in ORDER:
    page = pages[cat]
    seams = seams_by_cat.get(cat, {})
    total_seams += len(seams)
    rows = []
    for seam_id in sorted(seams):
        mark = "[x]" if seam_id in hooked else "[ ]"
        rows.append(f"{mark} {seam_id} — {VERDICT_SHORT[seams[seam_id]]}")

    lines.append("    new Page {")
    lines.append(f"      Category = {CATEGORY_CONST[cat]},")
    lines.append(f"      Title = {cs(page['title'])},")
    for field, key in (("What", "what"), ("Try", "try"), ("Watch", "watch")):
        body = ", ".join(cs(l) for l in page[key])
        lines.append(f"      {field} = new[] {{ {body} }},")
    seam_body = ",\n        ".join(cs(r) for r in rows) if rows else ""
    lines.append("      Seams = new[] {")
    if seam_body:
        lines.append("        " + seam_body + ",")
    lines.append("      },")
    lines.append("    },")

lines += [
    "  };",
    "",
    "  public static Page For(string category) {",
    "    foreach (Page page in Pages) {",
    "      if (page.Category == category) {",
    "        return page;",
    "      }",
    "    }",
    "    return Pages[0];",
    "  }",
    "}",
    "",
]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines))

print(f"  {OUT}")
print(f"  {len(ORDER)} pages, {total_seams} seams listed, {len(hooked)} hooked by this build")
