namespace ComfyQuestRuntime;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using BepInEx;
using BepInEx.Configuration;
using ComfyQuestContracts;
using HarmonyLib;

[BepInPlugin("djcdevelopment.valheim.comfyquestruntime", "ComfyQuestRuntime", "0.1.0")]
public sealed class ComfyQuestRuntimePlugin : BaseUnityPlugin {
  QuestPackStore packs;
  RuntimeReceiptStore receipts;
  RuntimeCharmBinding charms;
  RuntimeDevChannelCoordinator devChannel;
  RuntimeArcaneSight arcaneSight;
  RuntimeExperienceEngine engine;
  ConfigEntry<KeyboardShortcut> checkHotkey;
  ConfigEntry<KeyboardShortcut> loadHotkey;
  ConfigEntry<KeyboardShortcut> drawerHotkey;
  ConfigEntry<KeyboardShortcut> castHotkey;
  ConfigEntry<bool> privateWorldConfirmed;
  ConfigEntry<string> studioUrl;
  string runtimeRoot; bool inboxChecked; int checkedCandidates,checkedValid; bool showMaintenance; double nextDevPoll;
  readonly List<string> outcomes=new(); UnityEngine.Vector2 outcomeScroll,evidenceScroll;
  bool drawerVisible; string status="Runtime ready"; PackCandidate[] available=Array.Empty<PackCandidate>(); ActiveSet[] activationHistory=Array.Empty<ActiveSet>(); int selectedVersion,selectedActivation; UnityEngine.Rect drawer=new(24,90,560,590);
  UnityEngine.Texture2D windowBackground,headerBackground,rowBackground,helpBackground,greenBackground,greenGlowBackground,blueBackground,amberBackground,dimBackground; UnityEngine.GUIStyle windowStyle,sectionStyle,rowStyle,helpStyle,readyStyle,primaryStyle,blueButtonStyle,amberButtonStyle,dimButtonStyle,stepDoneStyle,stepPendingStyle;
  void Awake(){runtimeRoot=Path.Combine(Paths.ConfigPath,"comfy-quest-runtime");Directory.CreateDirectory(Path.Combine(runtimeRoot,"inbox"));Directory.CreateDirectory(Path.Combine(runtimeRoot,"inbox-dev"));packs=new QuestPackStore(runtimeRoot);receipts=new RuntimeReceiptStore(runtimeRoot);charms=new RuntimeCharmBinding(runtimeRoot,receipts);devChannel=new RuntimeDevChannelCoordinator(runtimeRoot,charms.RebindDevActive);arcaneSight=new RuntimeArcaneSight(runtimeRoot);privateWorldConfirmed=Config.Bind("Safety","PrivateWorldConfirmed",false,"Required before Charm inscription or mutation. Enable only for a private solo/listen-host world you control.");studioUrl=Config.Bind("Studio","Url","http://127.0.0.1:8085/quest-studio","Loopback URL opened by the Runtime drawer. Only an http:// localhost address is accepted.");engine=new RuntimeExperienceEngine(runtimeRoot,receipts,()=>privateWorldConfirmed.Value);RuntimeEventRouter.Engine=engine;drawerHotkey=Config.Bind("Runtime","DrawerHotkey",new KeyboardShortcut(UnityEngine.KeyCode.F9),"Open the compact runtime drawer. F9 avoids Quest Lab F6 and legacy Control F7.");castHotkey=Config.Bind("Runtime","CharmGestureHotkey",new KeyboardShortcut(UnityEngine.KeyCode.BackQuote),"While F9 is open: first press CHECKS and captures the aimed target; second press CASTS onto that exact target.");checkHotkey=Config.Bind("Runtime","CheckHotkey",new KeyboardShortcut(UnityEngine.KeyCode.F10),"Check inbox without activating content.");loadHotkey=Config.Bind("Runtime","LoadLatestHotkey",new KeyboardShortcut(UnityEngine.KeyCode.F11),"Activate the highest compatible version.");devChannel.Heartbeat(DateTimeOffset.UtcNow);var harmony=new Harmony("djcdevelopment.valheim.comfyquestruntime");harmony.PatchAll(typeof(RuntimeInputPatches));RuntimeKillPatches.Apply(harmony);RuntimeCooperativePatches.Apply(harmony);RuntimeEasyEventPatches.Apply(harmony);RuntimeProgressionPatches.Apply(harmony);RuntimeWorldStatePatches.Apply(harmony);RuntimeCoreActionPatches.Apply(harmony);RuntimeHarvestPatches.Apply(harmony);foreach(var patch in RuntimePatching.Outcomes)Logger.LogInfo($"Runtime patch {patch.SignatureId}: {(patch.Applied?"ok":patch.Detail)}");Logger.LogInfo($"Runtime ready. Drawer={drawerHotkey.Value}, charm={castHotkey.Value}, check={checkHotkey.Value}, load={loadHotkey.Value}, inbox={Path.Combine(runtimeRoot,"inbox")}");}
  void Update(){engine?.Tick();PollDevChannel();arcaneSight?.Tick();if(drawerHotkey.Value.IsDown())SetDrawer(!drawerVisible);if(drawerVisible&&UnityEngine.Input.GetKeyDown(UnityEngine.KeyCode.Escape))SetDrawer(false);if(drawerVisible&&castHotkey.Value.IsDown())HandleCharmGesture();if(drawerVisible)RuntimeInputPatches.Maintain();if(checkHotkey.Value.IsDown()){status=CheckForNew();Report(status);}if(loadHotkey.Value.IsDown()){status=LoadLatest();Report(status);}}
  void OnGUI(){if(!drawerVisible)return;EnsureStyles();arcaneSight?.Draw(helpStyle);drawer=UnityEngine.GUILayout.Window(94731,drawer,DrawDrawer,"Comfy Quest Runtime",windowStyle,UnityEngine.GUILayout.MinWidth(520f),UnityEngine.GUILayout.MinHeight(560f));drawer.x=UnityEngine.Mathf.Clamp(drawer.x,0,UnityEngine.Screen.width-drawer.width);drawer.y=UnityEngine.Mathf.Clamp(drawer.y,0,UnityEngine.Screen.height-drawer.height);}
  void DrawDrawer(int id){UnityEngine.GUILayout.BeginHorizontal();UnityEngine.GUILayout.Label("RUNTIME",sectionStyle,UnityEngine.GUILayout.Width(90));UnityEngine.GUILayout.Label("creator bridge · game pulls",helpStyle);UnityEngine.GUILayout.FlexibleSpace();if(UnityEngine.GUILayout.Button("Open Studio",blueButtonStyle,UnityEngine.GUILayout.Width(100)))OpenStudio();if(UnityEngine.GUILayout.Button("Close",dimButtonStyle,UnityEngine.GUILayout.Width(62)))SetDrawer(false);UnityEngine.GUILayout.EndHorizontal();UnityEngine.GUILayout.Space(7);DrawDevChannel();UnityEngine.GUILayout.Space(7);DrawReady(charms.CapturedPreview);UnityEngine.GUILayout.Space(7);DrawUpdateWorkflow();UnityEngine.GUILayout.Space(7);DrawArcaneSight();UnityEngine.GUILayout.Space(7);UnityEngine.GUILayout.Label("EXPERIENCE",amberButtonStyle,UnityEngine.GUILayout.Height(27));UnityEngine.GUILayout.Label(engine.DescribeProgress(),rowStyle,UnityEngine.GUILayout.Height(34));DrawOutcomes();UnityEngine.GUILayout.Space(7);DrawRecentEvidence();UnityEngine.GUILayout.Space(7);if(UnityEngine.GUILayout.Button((showMaintenance?"− ":"+ ")+"VERSIONS & ROLLBACK",dimButtonStyle,UnityEngine.GUILayout.Height(27))){showMaintenance=!showMaintenance;if(showMaintenance)RefreshActivationHistory();}if(showMaintenance)DrawMaintenance();UnityEngine.GUILayout.FlexibleSpace();UnityEngine.GUILayout.Label("F9 / Esc close  ·  ` CHECK / CAST  ·  drag title bar to move",helpStyle,UnityEngine.GUILayout.Height(28));UnityEngine.GUI.DragWindow(new UnityEngine.Rect(0,0,drawer.width-70,25));}
  void DrawDevChannel(){UnityEngine.GUILayout.Label("CREATOR LOOP",sectionStyle,UnityEngine.GUILayout.Height(25));if(devChannel.Armed){if(UnityEngine.GUILayout.Button("DEV CHANNEL ARMED · DISARM",primaryStyle,UnityEngine.GUILayout.Height(34)))devChannel.Disarm(DateTimeOffset.UtcNow);UnityEngine.GUILayout.Label("Studio revisions are validated and pulled into this private session.",helpStyle,UnityEngine.GUILayout.Height(30));return;}var allowed=privateWorldConfirmed.Value;var prior=UnityEngine.GUI.enabled;UnityEngine.GUI.enabled=allowed;if(UnityEngine.GUILayout.Button(allowed?"ARM DEV CHANNEL":"PRIVATE WORLD CONFIRMATION REQUIRED",allowed?amberButtonStyle:dimButtonStyle,UnityEngine.GUILayout.Height(34))&&allowed)devChannel.Arm(DateTimeOffset.UtcNow);UnityEngine.GUI.enabled=prior;UnityEngine.GUILayout.Label("Arming is session-only. Studio can publish bytes; only the game may activate them.",helpStyle,UnityEngine.GUILayout.Height(30));}
  void PollDevChannel(){if(devChannel==null||UnityEngine.Time.realtimeSinceStartup<nextDevPoll)return;nextDevPoll=UnityEngine.Time.realtimeSinceStartup+.5;try{var result=devChannel.Poll(DateTimeOffset.UtcNow,engine?.CurrentStageId());if(result.Activated){status=result.Message;AddOutcome("DEV · "+result.Message);}else if(result.Message!=null&&result.Message.StartsWith("Dev revision rejected",StringComparison.Ordinal)){status=result.Message;AddOutcome("DEV REJECTED · "+result.Message);}}catch(Exception e){status="Dev channel unavailable: "+e.Message;Logger.LogWarning(status);}}
  void DrawArcaneSight(){if(UnityEngine.GUILayout.Button(arcaneSight.Active?"ARCANE SIGHT - ON":"ARCANE SIGHT - OFF",amberButtonStyle,UnityEngine.GUILayout.Height(27)))arcaneSight.Toggle();UnityEngine.GUILayout.Label(arcaneSight.Describe(),rowStyle,UnityEngine.GUILayout.Height(36));}
  void OpenStudio(){if(!Uri.TryCreate(studioUrl.Value,UriKind.Absolute,out var uri)||uri.Scheme!="http"||!(uri.Host=="127.0.0.1"||uri.Host=="localhost"||uri.Host=="::1")){status="Studio URL rejected: loopback http required.";Report(status);return;}UnityEngine.Application.OpenURL(uri.AbsoluteUri);}
  void DrawReady(RuntimeCharmBinding.AimPreview aim){var checkedTarget=aim!=null;var ready=checkedTarget&&aim.Allowed;UnityEngine.GUILayout.BeginHorizontal();UnityEngine.GUILayout.Label(ready?"READY":checkedTarget?"NOT READY":"CHECK",ready?readyStyle:stepPendingStyle,UnityEngine.GUILayout.Width(120),UnityEngine.GUILayout.Height(54));UnityEngine.GUILayout.Label(checkedTarget?aim.Summary:"Aim the crosshair, then press ` to capture the target.",rowStyle,UnityEngine.GUILayout.Height(54));UnityEngine.GUILayout.EndHorizontal();UnityEngine.GUILayout.Label(ready?"`  ·  CAST CHARM":"`  ·  CHECK TARGET",ready?primaryStyle:blueButtonStyle,UnityEngine.GUILayout.Height(38));}
  void DrawOutcomes(){UnityEngine.GUILayout.Label("CAPTURES & OUTCOMES",sectionStyle,UnityEngine.GUILayout.Height(25));outcomeScroll=UnityEngine.GUILayout.BeginScrollView(outcomeScroll,rowStyle,UnityEngine.GUILayout.Height(74));if(outcomes.Count==0)UnityEngine.GUILayout.Label("No captures yet.",helpStyle);else foreach(var line in outcomes)UnityEngine.GUILayout.Label(line,helpStyle);UnityEngine.GUILayout.EndScrollView();}
  void DrawRecentEvidence(){UnityEngine.GUILayout.Label("RECENT RUNTIME EVIDENCE",sectionStyle,UnityEngine.GUILayout.Height(25));IReadOnlyList<string> evidence=engine?.RecentEvidence()??Array.Empty<string>();evidenceScroll=UnityEngine.GUILayout.BeginScrollView(evidenceScroll,rowStyle,UnityEngine.GUILayout.Height(88));if(evidence.Count==0)UnityEngine.GUILayout.Label("No gameplay evidence yet.",helpStyle);else foreach(var line in evidence)UnityEngine.GUILayout.Label(line,helpStyle);UnityEngine.GUILayout.EndScrollView();}
  void HandleCharmGesture(){if(!charms.HasCapture){var aim=charms.Capture(privateWorldConfirmed.Value);AddOutcome((aim.Allowed?"CHECK READY · ":"CHECK REJECTED · ")+aim.Summary);status=aim.Allowed?"Target captured. Press ` again to Cast Charm.":"Target rejected. Aim elsewhere and CHECK again.";Report(status);}else{status=charms.CastCaptured(privateWorldConfirmed.Value);AddOutcome("CAST · "+status);Report(status);}}
  void AddOutcome(string value){outcomes.Add(DateTime.Now.ToString("HH:mm:ss")+"  "+value);if(outcomes.Count>20)outcomes.RemoveAt(0);outcomeScroll.y=float.MaxValue;}
  void DrawUpdateWorkflow(){UnityEngine.GUILayout.Label("CONTENT UPDATE",blueButtonStyle,UnityEngine.GUILayout.Height(27));var active=ReadActive();var valid=inboxChecked&&checkedCandidates==checkedValid;var latest=available.Length>0?available[0]:null;var confirmed=active!=null&&latest!=null&&active.PackId==latest.Manifest.PackId&&active.Version==latest.Manifest.Version&&string.Equals(active.ContentHash,latest.ContentHash,StringComparison.OrdinalIgnoreCase);UnityEngine.GUILayout.BeginHorizontal();Step("1","LOOK",inboxChecked,inboxChecked?$"{checkedCandidates} found":"inbox");Step("2","VALIDATE",valid,inboxChecked?$"{checkedValid} valid":"waiting");Step("3","LOAD",confirmed,active==null?"none":active.Version);Step("4","CONFIRM",confirmed,confirmed?"active":"waiting");UnityEngine.GUILayout.EndHorizontal();if(!inboxChecked){if(UnityEngine.GUILayout.Button("CHECK FOR UPDATES",blueButtonStyle,UnityEngine.GUILayout.Height(36))){status=CheckForNew();Report(status);}}else if(!valid){if(UnityEngine.GUILayout.Button("CHECK AGAIN · DIAGNOSTICS PRESENT",amberButtonStyle,UnityEngine.GUILayout.Height(36))){status=CheckForNew();Report(status);}}else if(!confirmed){if(UnityEngine.GUILayout.Button("LOAD VALIDATED UPDATE",primaryStyle,UnityEngine.GUILayout.Height(36))){status=LoadLatest();Report(status);}}else{var prior=UnityEngine.GUI.enabled;UnityEngine.GUI.enabled=false;UnityEngine.GUILayout.Button("UP TO DATE · "+active.Version,primaryStyle,UnityEngine.GUILayout.Height(36));UnityEngine.GUI.enabled=prior;}UnityEngine.GUILayout.Label(status,rowStyle,UnityEngine.GUILayout.Height(30));}
  void Step(string number,string name,bool done,string detail){UnityEngine.GUILayout.Label(number+"  "+name+"\n"+detail,done?stepDoneStyle:stepPendingStyle,UnityEngine.GUILayout.MinWidth(110),UnityEngine.GUILayout.Height(46));}
  void DrawMaintenance(){if(available.Length>0){selectedVersion=Math.Max(0,Math.Min(selectedVersion,available.Length-1));var selected=available[selectedVersion];UnityEngine.GUILayout.Label($"CERTIFIED VERSION · {selected.Manifest.PackId}  ·  {selected.Manifest.Version}\n{selected.ContentHash}",rowStyle,UnityEngine.GUILayout.Height(46));UnityEngine.GUILayout.BeginHorizontal();if(UnityEngine.GUILayout.Button("Next certified",dimButtonStyle))selectedVersion=(selectedVersion+1)%available.Length;if(UnityEngine.GUILayout.Button("Load selected",amberButtonStyle)){status=LoadSelected();Report(status);RefreshActivationHistory();}UnityEngine.GUILayout.EndHorizontal();}else UnityEngine.GUILayout.Label("Run Check for updates to list certified production versions.",rowStyle);if(activationHistory.Length==0){UnityEngine.GUILayout.Label("No earlier activation epochs are available.",helpStyle);return;}selectedActivation=Math.Max(0,Math.Min(selectedActivation,activationHistory.Length-1));var prior=activationHistory[selectedActivation];UnityEngine.GUILayout.Label($"EARLIER ACTIVATION · {prior.PackId}  ·  {prior.Version} · {prior.ActivationId.Substring(prior.ActivationId.Length-8)}\n{prior.ContentHash}",rowStyle,UnityEngine.GUILayout.Height(46));UnityEngine.GUILayout.BeginHorizontal();if(UnityEngine.GUILayout.Button("Next earlier",dimButtonStyle))selectedActivation=(selectedActivation+1)%activationHistory.Length;if(UnityEngine.GUILayout.Button("Rollback to this activation",amberButtonStyle)){status=Rollback(prior.ActivationId);Report(status);RefreshActivationHistory();}UnityEngine.GUILayout.EndHorizontal();}
  void RefreshActivationHistory(){try{activationHistory=packs.ActivationHistory().ToArray();selectedActivation=Math.Max(0,Math.Min(selectedActivation,Math.Max(0,activationHistory.Length-1)));}catch(Exception e){activationHistory=Array.Empty<ActiveSet>();status="Activation history unavailable: "+e.Message;}}
  ActiveSet ReadActive(){try{var path=Path.Combine(runtimeRoot,"active","active-set.json");return File.Exists(path)?Newtonsoft.Json.JsonConvert.DeserializeObject<ActiveSet>(File.ReadAllText(path)):null;}catch{return null;}}
  void EnsureStyles(){if(windowStyle!=null)return;windowBackground=Solid("runtime-window",new UnityEngine.Color(.02f,.03f,.05f,.985f));headerBackground=Solid("runtime-header",new UnityEngine.Color(.10f,.16f,.24f,1f));rowBackground=Solid("runtime-row",new UnityEngine.Color(.035f,.05f,.075f,.98f));helpBackground=Solid("runtime-help",new UnityEngine.Color(.065f,.085f,.12f,.98f));greenBackground=Solid("runtime-green",new UnityEngine.Color(.10f,.36f,.23f,1f));greenGlowBackground=Solid("runtime-green-glow",new UnityEngine.Color(.18f,.62f,.36f,1f));blueBackground=Solid("runtime-blue",new UnityEngine.Color(.12f,.30f,.50f,1f));amberBackground=Solid("runtime-amber",new UnityEngine.Color(.48f,.32f,.10f,1f));dimBackground=Solid("runtime-dim",new UnityEngine.Color(.16f,.19f,.23f,1f));windowStyle=new UnityEngine.GUIStyle(UnityEngine.GUI.skin.window){fontSize=15,fontStyle=UnityEngine.FontStyle.Bold,padding=new UnityEngine.RectOffset(12,12,30,12)};Pin(windowStyle,windowBackground,UnityEngine.Color.white);sectionStyle=LabelStyle(headerBackground,UnityEngine.Color.white,UnityEngine.FontStyle.Bold,13);rowStyle=LabelStyle(rowBackground,new UnityEngine.Color(.92f,.95f,1f,1f),UnityEngine.FontStyle.Normal,13);rowStyle.wordWrap=true;helpStyle=LabelStyle(helpBackground,new UnityEngine.Color(.66f,.72f,.80f,1f),UnityEngine.FontStyle.Normal,12);helpStyle.wordWrap=true;readyStyle=LabelStyle(greenGlowBackground,UnityEngine.Color.white,UnityEngine.FontStyle.Bold,17);readyStyle.alignment=UnityEngine.TextAnchor.MiddleCenter;primaryStyle=ButtonStyle(greenBackground,UnityEngine.Color.white,14);blueButtonStyle=ButtonStyle(blueBackground,UnityEngine.Color.white,13);amberButtonStyle=ButtonStyle(amberBackground,UnityEngine.Color.white,13);dimButtonStyle=ButtonStyle(dimBackground,new UnityEngine.Color(.82f,.85f,.88f,1f),13);stepDoneStyle=LabelStyle(greenBackground,UnityEngine.Color.white,UnityEngine.FontStyle.Bold,12);stepDoneStyle.alignment=UnityEngine.TextAnchor.MiddleCenter;stepPendingStyle=LabelStyle(dimBackground,new UnityEngine.Color(.65f,.70f,.76f,1f),UnityEngine.FontStyle.Bold,12);stepPendingStyle.alignment=UnityEngine.TextAnchor.MiddleCenter;}
  static UnityEngine.GUIStyle LabelStyle(UnityEngine.Texture2D background,UnityEngine.Color color,UnityEngine.FontStyle weight,int size){var style=new UnityEngine.GUIStyle(UnityEngine.GUI.skin.label){padding=new UnityEngine.RectOffset(8,8,5,5),margin=new UnityEngine.RectOffset(1,1,1,1),alignment=UnityEngine.TextAnchor.MiddleLeft,fontStyle=weight,fontSize=size};style.normal.background=background;style.normal.textColor=color;return style;}
  static UnityEngine.GUIStyle ButtonStyle(UnityEngine.Texture2D background,UnityEngine.Color color,int size){var style=new UnityEngine.GUIStyle(UnityEngine.GUI.skin.button){fontSize=size,fontStyle=UnityEngine.FontStyle.Bold,padding=new UnityEngine.RectOffset(8,8,6,6)};Pin(style,background,color);return style;}
  static void Pin(UnityEngine.GUIStyle style,UnityEngine.Texture2D background,UnityEngine.Color color){style.normal.background=background;style.hover.background=background;style.active.background=background;style.focused.background=background;style.onNormal.background=background;style.onHover.background=background;style.onActive.background=background;style.onFocused.background=background;style.normal.textColor=color;style.hover.textColor=color;style.active.textColor=color;style.focused.textColor=color;style.onNormal.textColor=color;style.onHover.textColor=color;style.onActive.textColor=color;style.onFocused.textColor=color;}
  static UnityEngine.Texture2D Solid(string name,UnityEngine.Color color){var texture=new UnityEngine.Texture2D(1,1,UnityEngine.TextureFormat.RGBA32,false){name=name,hideFlags=UnityEngine.HideFlags.HideAndDontSave};texture.SetPixel(0,0,color);texture.Apply(false,true);return texture;}
  void SetDrawer(bool visible){drawerVisible=visible;if(visible){RuntimeInputPatches.Acquire();arcaneSight?.Enable();}else{RuntimeInputPatches.Release();arcaneSight?.Disable();}}
  void Report(string message){Logger.LogInfo(message);try{if(MessageHud.instance!=null)MessageHud.instance.ShowMessage(MessageHud.MessageType.Center,message);}catch(Exception e){Logger.LogWarning("HUD status unavailable: "+e.Message);}}
  void OnDestroy(){try{devChannel?.Disarm(DateTimeOffset.UtcNow);}catch{}RuntimeInputPatches.Release();arcaneSight?.Disable();RuntimeCoreActionPatches.Reset();RuntimeHarvestPatches.Reset();RuntimeEventRouter.Reset();RuntimeEventRouter.Engine=null;Destroy(ref windowBackground);Destroy(ref headerBackground);Destroy(ref rowBackground);Destroy(ref helpBackground);Destroy(ref greenBackground);Destroy(ref greenGlowBackground);Destroy(ref blueBackground);Destroy(ref amberBackground);Destroy(ref dimBackground);}
  static void Destroy(ref UnityEngine.Texture2D texture){if(texture!=null)UnityEngine.Object.Destroy(texture);texture=null;}
  // UI/input and world mutation remain outside the contract. The dev pull loop is inert until the
  // creator explicitly arms it in-game for this process session.
  public string CheckForNew(){var c=packs.CheckInbox();var valid=c.Count(x=>x.IsValid);inboxChecked=true;checkedCandidates=c.Count;checkedValid=valid;available=c.Where(x=>x.IsValid).OrderByDescending(x=>SemanticVersion.Parse(x.Manifest.Version)).ToArray();selectedVersion=0;receipts.Write(new RuntimeReceipt{Operation="check",Status=c.Count==valid?"accepted":"diagnostics",CandidateCount=c.Count,ValidCount=valid,Diagnostics=c.SelectMany(x=>x.Diagnostics).ToArray()});foreach(var candidate in available)receipts.Write(new RuntimeReceipt{Operation="check",Status="accepted",PackId=candidate.Manifest.PackId,Version=candidate.Manifest.Version,ContentHash=candidate.ContentHash,CandidateCount=c.Count,ValidCount=valid,Diagnostics=Array.Empty<ContractDiagnostic>()});return $"{c.Count} pack(s), {valid} valid";}
  public string LoadLatest(){try{var c=packs.LoadLatest();if(c==null){receipts.Write(new RuntimeReceipt{Operation="load",Status="rejected",Error="no_compatible_pack"});return "No compatible pack.";}var active=packs.ReadActive();receipts.Write(new RuntimeReceipt{Operation="load",Status="activated",PackId=c.Manifest.PackId,Version=c.Manifest.Version,ContentHash=c.ContentHash,ActivationId=active?.ActivationId,Diagnostics=Array.Empty<ContractDiagnostic>()});return $"Activated {c.Manifest.PackId} {c.Manifest.Version} · {ShortHash(c.ContentHash)}";}catch(Exception e){receipts.Write(new RuntimeReceipt{Operation="load",Status="rejected",Error=e.Message});return "Load failed: "+e.Message;}}
  public string LoadSelected(){if(available.Length==0)return "Check for new first.";var selected=available[Math.Max(0,Math.Min(selectedVersion,available.Length-1))];return Activate("load_selected",()=>packs.LoadVersion(selected.Manifest.PackId,selected.Manifest.Version));}
  public string Rollback()=>Activate("rollback",()=>packs.Rollback());
  public string Rollback(string activationId)=>Activate("rollback",()=>packs.Rollback(activationId));
  string Activate(string operation,Func<PackCandidate> choose){try{var c=choose();if(c==null){receipts.Write(new RuntimeReceipt{Operation=operation,Status="rejected",Error="version_unavailable"});return operation=="rollback"?"No older activation available.":"Selected version unavailable.";}var active=packs.ReadActive();var correlation=operation+"-"+Guid.NewGuid().ToString("N");receipts.Write(new RuntimeReceipt{Operation=operation,Status="activated",PackId=c.Manifest.PackId,Version=c.Manifest.Version,ContentHash=c.ContentHash,ActivationId=active?.ActivationId,CorrelationId=correlation,Diagnostics=Array.Empty<ContractDiagnostic>()});if(operation=="rollback"&&string.Equals(active?.SourceChannel,"dev",StringComparison.OrdinalIgnoreCase))foreach(var receipt in charms.RebindDevActive(active,correlation))receipts.Write(receipt);return $"{(operation=="rollback"?"Rolled back to":"Activated")} {c.Manifest.PackId} {c.Manifest.Version}";}catch(Exception e){receipts.Write(new RuntimeReceipt{Operation=operation,Status="rejected",Error=e.Message});return operation+" failed: "+e.Message;}}
  static string ShortHash(string value)=>string.IsNullOrWhiteSpace(value)?"no hash":value.Substring(0,Math.Min(8,value.Length));
}
