namespace ComfyQuestRuntime;

using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using ComfyQuestContracts;
using Newtonsoft.Json;

sealed class RuntimeExperienceEngine {
  const string Prefix="comfyQuestRuntime.";readonly string root;readonly RuntimeReceiptStore receipts;readonly ActionExecutionLedger ledger;readonly SpawnExecutionStore spawned;readonly WorkflowStateStore workflows;readonly DurableTimerStore timers;readonly Func<bool> privateConfirmed;DateTimeOffset nextTimerPoll;
  public RuntimeExperienceEngine(string runtimeRoot,RuntimeReceiptStore receiptStore,Func<bool> isPrivateConfirmed){root=runtimeRoot;receipts=receiptStore;ledger=new ActionExecutionLedger(root);spawned=new SpawnExecutionStore(root);workflows=new WorkflowStateStore(root);timers=new DurableTimerStore(root);privateConfirmed=isPrivateConfirmed;}
  public void Tick(){var now=DateTimeOffset.UtcNow;if(now<nextTimerPoll)return;nextTimerPoll=now.AddSeconds(1);foreach(var timer in timers.Due(now)){OnEvent(new RuntimeEvent{Name=ExperienceSchema.TimerElapsedEvent,SourceId=timer.Identity.BindingZdo,At=now,Fields=new Dictionary<string,string>{{"timer_id",timer.TimerId}}});timers.Acknowledge(timer.Key);}}
  public void OnEvent(RuntimeEvent evt){try{var authority=CharmPolicy.CanMutate(World());if(!authority.Allowed){Write("transition",authority.Diagnostic,null,null,null);return;}if(!TryLoad(out var active,out var diagnostic)){Write("transition",diagnostic,null,null,null);return;}foreach(var wear in WearNTear.GetAllInstances().ToArray()){if(wear==null)continue;var view=wear.GetComponent<ZNetView>();var zdo=view==null?null:view.GetZDO();if(zdo==null||!view.IsOwner()||(!string.IsNullOrWhiteSpace(evt.SourceId)&&evt.SourceId!=zdo.m_uid.ToString()))continue;var reference=Read(zdo);if(reference==null||reference.PackId!=active.PackId||reference.ExperienceId!=active.Document.Id||reference.Version!=active.Version||reference.ContentHash!=active.ContentHash)continue;var identity=Identity(zdo,active);var decision=workflows.Begin(identity,active.Document,evt);if(decision==null)continue;var stage=active.Document.Stages.FirstOrDefault(x=>x.Id==decision.StageId);if(stage==null)continue;var succeeded=true;foreach(var action in decision.Transition.Actions??new())succeeded&=Execute(active,zdo,stage.Id,decision.Transition.Id,action);if(succeeded&&!string.IsNullOrWhiteSpace(decision.Transition.NextStage)){var next=active.Document.Stages.FirstOrDefault(x=>x.Id==decision.Transition.NextStage);foreach(var action in next?.EntryActions??new())succeeded&=Execute(active,zdo,next.Id,"entry",action);}if(!succeeded)continue;if(workflows.Complete(decision))receipts.Write(new RuntimeReceipt{Operation="transition",Status=string.IsNullOrWhiteSpace(decision.Transition.Outcome)?"advanced":decision.Transition.Outcome,PackId=active.PackId,Version=active.Version,ContentHash=active.ContentHash,BindingZdo=zdo.m_uid.ToString(),StageId=stage.Id,TransitionId=decision.Transition.Id,Diagnostics=Array.Empty<ContractDiagnostic>()});}}
    catch(Exception e){Write("action","runtime_event_failed",null,null,e.Message);}}
  bool Execute(Active active,ZDO zdo,string stage,string transition,ExperienceAction action){try{var identity=Identity(zdo,active);var zdoId=zdo.m_uid.ToString();var key=string.Join("|",identity.Key,stage,transition,action.Id);if(!ledger.TryClaim(key)){receipts.Write(ActionReceipt("suppressed","duplicate_suppressed",active,zdoId,stage,transition,action.Id));return true;}switch(action.Type){case "message":MessageHud.instance?.ShowMessage(MessageHud.MessageType.Center,Param(action,"text"));break;case "timer_start":timers.Start(identity,Param(action,"timer_id"),DateTimeOffset.UtcNow.AddSeconds(IntParam(action,"seconds")));break;case "timer_cancel":timers.Cancel(identity,Param(action,"timer_id"));break;case "grant_item":if(!Grant(action))throw new InvalidOperationException("grant_failed");break;case "spawn":if(!Spawn(active,zdo,action,key))throw new InvalidOperationException("spawn_failed");break;case "clear_spawned":Clear(active,Param(action,"action_id"),identity,stage,transition);break;default:throw new InvalidOperationException("action_not_implemented");}receipts.Write(ActionReceipt("executed",null,active,zdoId,stage,transition,action.Id));return true;}catch(Exception e){Write("action",e.Message,active,null,action.Id);return false;}}
  static string Param(ExperienceAction action,string name)=>action.Parameters!=null&&action.Parameters.TryGetValue(name,out var value)?value.ToString():"";
  static int IntParam(ExperienceAction action,string name)=>action.Parameters!=null&&action.Parameters.TryGetValue(name,out var value)?value.ToObject<int>():0;
  static bool Grant(ExperienceAction action){var item=Param(action,"item");var count=IntParam(action,"quantity");if(!MutationRegistry.TryGrant(item,count,out _))return false;var prefab=ZNetScene.instance?.GetPrefab(item);if(prefab==null||prefab.GetComponent<ItemDrop>()==null||Player.m_localPlayer==null)return false;return Player.m_localPlayer.GetInventory().AddItem(prefab,count);}
  bool Spawn(Active active,ZDO binding,ExperienceAction action,string key){var kind=Param(action,"kind");var prefabName=Param(action,"prefab");var count=IntParam(action,"count");var radius=IntParam(action,"radius");if(!MutationRegistry.CanSpawn(kind,prefabName)||count<1||count>16||radius<0||radius>30)return false;var prefab=ZNetScene.instance?.GetPrefab(prefabName);if(prefab==null||!PrefabMatches(prefab,kind))return false;var center=binding.GetPosition();for(var i=0;i<count;i++){var angle=(float)(i*Math.PI*2/Math.Max(1,count));var distance=Math.Min(radius,2+i/4);var position=center+new UnityEngine.Vector3((float)Math.Cos(angle)*distance,0.5f,(float)Math.Sin(angle)*distance);var go=UnityEngine.Object.Instantiate(prefab,position,UnityEngine.Quaternion.identity);var view=go?.GetComponent<ZNetView>();var z=view?.GetZDO();if(z==null)return false;z.Set(Prefix+"spawnedContentHash",active.ContentHash);z.Set(Prefix+"spawnedActionId",action.Id);z.Set(Prefix+"spawnedActionKey",key);var piece=go.GetComponent<Piece>();if(piece!=null&&Player.m_localPlayer!=null)piece.SetCreator(Player.m_localPlayer.GetPlayerID());spawned.Record(new SpawnedObject{ActionKey=key,ContentHash=active.ContentHash,ActionId=action.Id,UserId=z.m_uid.UserID,ObjectId=z.m_uid.ID});}return true;}
  static bool PrefabMatches(UnityEngine.GameObject prefab,string kind)=>kind=="creature"?prefab.GetComponent<Character>()!=null&&prefab.GetComponent<Player>()==null:kind=="item"?prefab.GetComponent<ItemDrop>()!=null:kind=="piece"&&prefab.GetComponent<Piece>()!=null;
  void Clear(Active active,string targetAction,WorkflowIdentity identity,string stage,string transition){var records=spawned.ForOwnerAction(identity.Key,targetAction);var removed=new List<SpawnedObject>();foreach(var record in records){var zdo=ZDOMan.instance?.GetZDO(new ZDOID(record.UserId,record.ObjectId));if(zdo==null){removed.Add(record);continue;}if(record.ContentHash!=active.ContentHash||zdo.GetString(Prefix+"spawnedContentHash","")!=record.ContentHash||zdo.GetString(Prefix+"spawnedActionId","")!=record.ActionId||zdo.GetString(Prefix+"spawnedActionKey","")!=record.ActionKey)continue;var view=ZNetScene.instance?.FindInstance(zdo);if(view!=null){view.ClaimOwnership();view.Destroy();}else{zdo.SetOwner(ZDOMan.GetSessionID());ZDOMan.instance.DestroyZDO(zdo);}removed.Add(record);}spawned.Remove(removed);}
  static RuntimeReceipt ActionReceipt(string status,string error,Active active,string zdo,string stage,string transition,string action)=>new(){Operation="action",Status=status,Error=error,PackId=active.PackId,Version=active.Version,ContentHash=active.ContentHash,BindingZdo=zdo,StageId=stage,TransitionId=transition,ActionId=action,Diagnostics=Array.Empty<ContractDiagnostic>()};
  CharmReference Read(ZDO zdo){var r=new CharmReference{PackId=zdo.GetString(Prefix+"packId",""),ExperienceId=zdo.GetString(Prefix+"experienceId",""),BindingId=zdo.GetString(Prefix+"bindingId",""),Version=zdo.GetString(Prefix+"version",""),ContentHash=zdo.GetString(Prefix+"contentHash","")};return CharmPolicy.ValidateReference(r).Allowed?r:null;}
  WorkflowIdentity Identity(ZDO zdo,Active active)=>new(){WorldId=ZNet.instance.GetWorldUID().ToString(),CharacterId=Player.m_localPlayer==null?"0":Player.m_localPlayer.GetPlayerID().ToString(),BindingZdo=zdo.m_uid.ToString(),ContentHash=active.ContentHash};
  public string DescribeProgress(){try{if(!TryLoad(out var active,out _))return "not ready";foreach(var wear in WearNTear.GetAllInstances()){var zdo=wear?.GetComponent<ZNetView>()?.GetZDO();if(zdo==null)continue;var reference=Read(zdo);if(reference==null||reference.ContentHash!=active.ContentHash)continue;var progress=workflows.Get(Identity(zdo,active));if(progress!=null)return string.IsNullOrWhiteSpace(progress.Outcome)?$"{active.Document.Title}: {progress.StageId}":$"{active.Document.Title}: {progress.Outcome}";}return $"{active.Document.Title}: not started";}catch{return "unavailable";}}
  bool TryLoad(out Active active,out string error){active=null;error="active_set_missing";try{var activePath=Path.Combine(root,"active","active-set.json");if(!File.Exists(activePath))return false;var set=JsonConvert.DeserializeObject<ActiveSet>(File.ReadAllText(activePath));if(set==null||set.Source!=Path.GetFileName(set.Source)){error="active_source_invalid";return false;}var package=Path.Combine(root,"inbox",set.Source);var inspected=new QuestPackStore(root).Inspect(package);if(!inspected.IsValid||inspected.ContentHash!=set.ContentHash||inspected.Manifest.PackId!=set.PackId||inspected.Manifest.Version!=set.Version){error="active_content_mismatch";return false;}using var zip=ZipFile.OpenRead(package);var entries=zip.Entries.Where(x=>x.FullName.StartsWith("experiences/",StringComparison.Ordinal)&&x.FullName.EndsWith(".json",StringComparison.Ordinal)).ToArray();if(entries.Length!=1){error="active_experience_ambiguous";return false;}using var reader=new StreamReader(entries[0].Open());var compiled=ExperienceCompiler.CompileJson(reader.ReadToEnd(),CanonicalEventCatalog.CreateSet());if(!compiled.IsValid){error="active_experience_invalid";return false;}active=new Active{PackId=set.PackId,Version=set.Version,ContentHash=set.ContentHash,Document=compiled.Document};error=null;return true;}catch{error="active_set_unreadable";return false;}}
  WorldAuthority World(){try{var dedicated=ZNet.instance!=null&&ZNet.instance.IsDedicated();var host=ZNet.instance!=null&&ZNet.instance.IsServer()&&!dedicated;return new(){IsPrivateWorld=privateConfirmed(),IsSolo=host,IsListenHost=host,IsDedicated=dedicated,IsPeerClient=ZNet.instance!=null&&!ZNet.instance.IsServer()};}catch{return new(){IsPrivateWorld=privateConfirmed()};}}
  void Write(string operation,string error,Active active,string status,string detail)=>receipts.Write(new RuntimeReceipt{Operation=operation,Status=status??"rejected",Error=detail==null?error:error+":"+detail,PackId=active?.PackId,Version=active?.Version,ContentHash=active?.ContentHash});
  sealed class ActiveSet{[JsonProperty("pack_id")]public string PackId{get;set;}[JsonProperty("version")]public string Version{get;set;}[JsonProperty("content_hash")]public string ContentHash{get;set;}[JsonProperty("source")]public string Source{get;set;}}
  sealed class Active{public string PackId,Version,ContentHash;public ExperienceDocument Document;}
}
