// <auto-generated>
//   Generated by tools/component-packets/generate_gallery.py.
//   The rune strokes are read from Ui/LabRunes.cs, so a monument is the same shape
//   as the glyph on its page — one table, two scales. Do not edit by hand.
// </auto-generated>

namespace ComfyQuestLab;

/// <summary>Where everything in the gallery goes, relative to its origin.
///
/// Coordinates are metres from the gallery centre, not world coordinates: the builder
/// adds the player's chosen origin, so the gallery can be raised anywhere rather than
/// tying the Tome to one world.</summary>
public static class LabGalleryPlan {
  public struct Beam { public float X, Y, Z, Dx, Dy, Dz; }
  public struct Station { public string Prefab, Kind, Note; public float X, Z; }
  public struct Monument { public string Category; public float Angle, Cx, Cz;
                           public Beam[] Beams; public Station Station; }
  public struct RackItem { public string Item, Note; public float X, Z, Yaw; }

  public const float RingRadius = 46.0f;
  public const float RuneHeight = 11.0f;
  public const float BeamLength = 2.0f;

  public static readonly Monument[] Monuments = {
    new Monument {
      Category = LabCategory.Combat,
      Angle = 0.0f, Cx = 0.0f, Cz = 46.0f,
      Station = new Station { Prefab = "Greyling", Kind = "spawner", Note = "a target that fights back, respawned on demand", X = 0.0f, Z = 35.0f },
      Beams = new[] {
        new Beam { X = 0.0f, Y = 9.465f, Z = 46.0f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = 0.0f, Y = 7.595f, Z = 46.0f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = 0.0f, Y = 5.725f, Z = 46.0f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = 0.0f, Y = 3.855f, Z = 46.0f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = 0.0f, Y = 1.985f, Z = 46.0f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -0.787f, Y = 9.52f, Z = 46.0f, Dx = -0.6669f, Dy = -0.7452f, Dz = -0.0f },
        new Beam { X = -2.362f, Y = 7.76f, Z = 46.0f, Dx = -0.6669f, Dy = -0.7452f, Dz = -0.0f },
        new Beam { X = 0.787f, Y = 9.52f, Z = 46.0f, Dx = 0.6669f, Dy = -0.7452f, Dz = 0.0f },
        new Beam { X = 2.362f, Y = 7.76f, Z = 46.0f, Dx = 0.6669f, Dy = -0.7452f, Dz = 0.0f },
      },
    },
    new Monument {
      Category = LabCategory.Harvest,
      Angle = 45.0f, Cx = 32.527f, Cz = 32.527f,
      Station = new Station { Prefab = "Birch1", Kind = "prop", Note = "a tree to strike, a bush and a berry to pick", X = 24.749f, Z = 24.749f },
      Beams = new[] {
        new Beam { X = 30.713f, Y = 8.695f, Z = 34.341f, Dx = 0.5772f, Dy = -0.5776f, Dz = -0.5772f },
        new Beam { X = 31.922f, Y = 7.485f, Z = 33.131f, Dx = 0.5772f, Dy = -0.5776f, Dz = -0.5772f },
        new Beam { X = 31.922f, Y = 6.33f, Z = 33.131f, Dx = -0.5947f, Dy = -0.541f, Dz = 0.5947f },
        new Beam { X = 30.713f, Y = 5.23f, Z = 34.341f, Dx = -0.5947f, Dy = -0.541f, Dz = 0.5947f },
        new Beam { X = 34.341f, Y = 3.305f, Z = 30.713f, Dx = -0.5772f, Dy = 0.5776f, Dz = 0.5772f },
        new Beam { X = 33.131f, Y = 4.515f, Z = 31.922f, Dx = -0.5772f, Dy = 0.5776f, Dz = 0.5772f },
        new Beam { X = 33.131f, Y = 5.67f, Z = 31.922f, Dx = 0.5947f, Dy = 0.541f, Dz = -0.5947f },
        new Beam { X = 34.341f, Y = 6.77f, Z = 30.713f, Dx = 0.5947f, Dy = 0.541f, Dz = -0.5947f },
      },
    },
    new Monument {
      Category = LabCategory.Inventory,
      Angle = 90.0f, Cx = 46.0f, Cz = 0.0f,
      Station = new Station { Prefab = "piece_chest_wood", Kind = "piece", Note = "a chest to empty, with something in it", X = 35.0f, Z = 0.0f },
      Beams = new[] {
        new Beam { X = 46.0f, Y = 9.96f, Z = 1.98f, Dx = 0.0f, Dy = -1.0f, Dz = -0.0f },
        new Beam { X = 46.0f, Y = 7.98f, Z = 1.98f, Dx = 0.0f, Dy = -1.0f, Dz = -0.0f },
        new Beam { X = 46.0f, Y = 6.0f, Z = 1.98f, Dx = 0.0f, Dy = -1.0f, Dz = -0.0f },
        new Beam { X = 46.0f, Y = 4.02f, Z = 1.98f, Dx = 0.0f, Dy = -1.0f, Dz = -0.0f },
        new Beam { X = 46.0f, Y = 2.04f, Z = 1.98f, Dx = 0.0f, Dy = -1.0f, Dz = -0.0f },
        new Beam { X = 46.0f, Y = 8.787f, Z = 1.2f, Dx = 0.0f, Dy = 0.4254f, Dz = -0.905f },
        new Beam { X = 46.0f, Y = 9.52f, Z = -0.36f, Dx = 0.0f, Dy = 0.4254f, Dz = -0.905f },
        new Beam { X = 46.0f, Y = 10.253f, Z = -1.92f, Dx = 0.0f, Dy = 0.4254f, Dz = -0.905f },
        new Beam { X = 46.0f, Y = 5.817f, Z = 1.2f, Dx = 0.0f, Dy = 0.4254f, Dz = -0.905f },
        new Beam { X = 46.0f, Y = 6.55f, Z = -0.36f, Dx = 0.0f, Dy = 0.4254f, Dz = -0.905f },
        new Beam { X = 46.0f, Y = 7.283f, Z = -1.92f, Dx = 0.0f, Dy = 0.4254f, Dz = -0.905f },
      },
    },
    new Monument {
      Category = LabCategory.Building,
      Angle = 135.0f, Cx = 32.527f, Cz = -32.527f,
      Station = new Station { Prefab = "piece_workbench", Kind = "piece", Note = "a workbench, so pieces can be placed and repaired", X = 24.749f, Z = -24.749f },
      Beams = new[] {
        new Beam { X = 33.036f, Y = 9.795f, Z = -32.018f, Dx = 0.4649f, Dy = -0.7534f, Dz = 0.4649f },
        new Beam { X = 34.054f, Y = 8.145f, Z = -31.0f, Dx = 0.4649f, Dy = -0.7534f, Dz = 0.4649f },
        new Beam { X = 32.018f, Y = 9.795f, Z = -33.036f, Dx = -0.4649f, Dy = -0.7534f, Dz = -0.4649f },
        new Beam { X = 31.0f, Y = 8.145f, Z = -34.054f, Dx = -0.4649f, Dy = -0.7534f, Dz = -0.4649f },
        new Beam { X = 34.054f, Y = 6.77f, Z = -31.0f, Dx = -0.5619f, Dy = -0.607f, Dz = -0.5619f },
        new Beam { X = 33.036f, Y = 5.67f, Z = -32.018f, Dx = -0.5619f, Dy = -0.607f, Dz = -0.5619f },
        new Beam { X = 31.0f, Y = 6.77f, Z = -34.054f, Dx = 0.5619f, Dy = -0.607f, Dz = 0.5619f },
        new Beam { X = 32.018f, Y = 5.67f, Z = -33.036f, Dx = 0.5619f, Dy = -0.607f, Dz = 0.5619f },
        new Beam { X = 33.885f, Y = 5.175f, Z = -31.169f, Dx = 0.2416f, Dy = -0.9398f, Dz = 0.2416f },
        new Beam { X = 34.309f, Y = 3.525f, Z = -30.745f, Dx = 0.2416f, Dy = -0.9398f, Dz = 0.2416f },
        new Beam { X = 34.733f, Y = 1.875f, Z = -30.321f, Dx = 0.2416f, Dy = -0.9398f, Dz = 0.2416f },
        new Beam { X = 31.169f, Y = 5.175f, Z = -33.885f, Dx = -0.2416f, Dy = -0.9398f, Dz = -0.2416f },
        new Beam { X = 30.745f, Y = 3.525f, Z = -34.309f, Dx = -0.2416f, Dy = -0.9398f, Dz = -0.2416f },
        new Beam { X = 30.321f, Y = 1.875f, Z = -34.733f, Dx = -0.2416f, Dy = -0.9398f, Dz = -0.2416f },
      },
    },
    new Monument {
      Category = LabCategory.Crafting,
      Angle = 180.0f, Cx = 0.0f, Cz = -46.0f,
      Station = new Station { Prefab = "smelter", Kind = "piece", Note = "a smelter and a kiln, fuelled", X = 0.0f, Z = -35.0f },
      Beams = new[] {
        new Beam { X = -1.725f, Y = 9.85f, Z = -46.0f, Dx = 0.7183f, Dy = -0.6957f, Dz = 0.0f },
        new Beam { X = -0.135f, Y = 8.31f, Z = -46.0f, Dx = 0.7183f, Dy = -0.6957f, Dz = 0.0f },
        new Beam { X = 1.455f, Y = 6.77f, Z = -46.0f, Dx = 0.7183f, Dy = -0.6957f, Dz = 0.0f },
        new Beam { X = 1.455f, Y = 5.23f, Z = -46.0f, Dx = -0.7183f, Dy = -0.6957f, Dz = -0.0f },
        new Beam { X = -0.135f, Y = 3.69f, Z = -46.0f, Dx = -0.7183f, Dy = -0.6957f, Dz = -0.0f },
        new Beam { X = -1.725f, Y = 2.15f, Z = -46.0f, Dx = -0.7183f, Dy = -0.6957f, Dz = -0.0f },
      },
    },
    new Monument {
      Category = LabCategory.Progression,
      Angle = 225.0f, Cx = -32.527f, Cz = -32.527f,
      Station = new Station { Prefab = "piece_workbench", Kind = "piece", Note = "a bench, and room to swing until a skill rises", X = -24.749f, Z = -24.749f },
      Beams = new[] {
        new Beam { X = -33.672f, Y = 10.4f, Z = -31.381f, Dx = 0.7071f, Dy = 0.0f, Dz = -0.7071f },
        new Beam { X = -32.145f, Y = 10.4f, Z = -32.909f, Dx = 0.7071f, Dy = 0.0f, Dz = -0.7071f },
        new Beam { X = -31.763f, Y = 9.667f, Z = -33.291f, Dx = -0.4193f, Dy = -0.8052f, Dz = 0.4193f },
        new Beam { X = -32.527f, Y = 8.2f, Z = -32.527f, Dx = -0.4193f, Dy = -0.8052f, Dz = 0.4193f },
        new Beam { X = -33.291f, Y = 6.733f, Z = -31.763f, Dx = -0.4193f, Dy = -0.8052f, Dz = 0.4193f },
        new Beam { X = -32.909f, Y = 6.0f, Z = -32.145f, Dx = 0.7071f, Dy = 0.0f, Dz = -0.7071f },
        new Beam { X = -31.381f, Y = 6.0f, Z = -33.672f, Dx = 0.7071f, Dy = 0.0f, Dz = -0.7071f },
        new Beam { X = -31.0f, Y = 5.267f, Z = -34.054f, Dx = -0.4193f, Dy = -0.8052f, Dz = 0.4193f },
        new Beam { X = -31.763f, Y = 3.8f, Z = -33.291f, Dx = -0.4193f, Dy = -0.8052f, Dz = 0.4193f },
        new Beam { X = -32.527f, Y = 2.333f, Z = -32.527f, Dx = -0.4193f, Dy = -0.8052f, Dz = 0.4193f },
      },
    },
    new Monument {
      Category = LabCategory.World,
      Angle = 270.0f, Cx = -46.0f, Cz = -0.0f,
      Station = new Station { Prefab = "portal_wood", Kind = "piece", Note = "a portal pair, to travel between", X = -35.0f, Z = -0.0f },
      Beams = new[] {
        new Beam { X = -46.0f, Y = 9.96f, Z = -2.25f, Dx = -0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -46.0f, Y = 7.98f, Z = -2.25f, Dx = -0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -46.0f, Y = 6.0f, Z = -2.25f, Dx = -0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -46.0f, Y = 4.02f, Z = -2.25f, Dx = -0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -46.0f, Y = 2.04f, Z = -2.25f, Dx = -0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -46.0f, Y = 10.482f, Z = -1.125f, Dx = -0.0f, Dy = -0.3837f, Dz = 0.9234f },
        new Beam { X = -46.0f, Y = 9.547f, Z = 1.125f, Dx = -0.0f, Dy = -0.3837f, Dz = 0.9234f },
        new Beam { X = -46.0f, Y = 8.603f, Z = 1.5f, Dx = 0.0f, Dy = -0.5364f, Dz = -0.844f },
        new Beam { X = -46.0f, Y = 7.65f, Z = -0.0f, Dx = 0.0f, Dy = -0.5364f, Dz = -0.844f },
        new Beam { X = -46.0f, Y = 6.697f, Z = -1.5f, Dx = 0.0f, Dy = -0.5364f, Dz = -0.844f },
        new Beam { X = -46.0f, Y = 5.358f, Z = -0.675f, Dx = -0.0f, Dy = -0.7872f, Dz = 0.6167f },
        new Beam { X = -46.0f, Y = 3.635f, Z = 0.675f, Dx = -0.0f, Dy = -0.7872f, Dz = 0.6167f },
        new Beam { X = -46.0f, Y = 1.912f, Z = 2.025f, Dx = -0.0f, Dy = -0.7872f, Dz = 0.6167f },
      },
    },
    new Monument {
      Category = LabCategory.Social,
      Angle = 315.0f, Cx = -32.527f, Cz = 32.527f,
      Station = new Station { Prefab = "sign", Kind = "piece", Note = "a sign to write on", X = -24.749f, Z = 24.749f },
      Beams = new[] {
        new Beam { X = -34.754f, Y = 9.696f, Z = 30.3f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -34.754f, Y = 7.848f, Z = 30.3f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -34.754f, Y = 6.0f, Z = 30.3f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -34.754f, Y = 4.152f, Z = 30.3f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -34.754f, Y = 2.304f, Z = 30.3f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -30.3f, Y = 9.696f, Z = 34.754f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -30.3f, Y = 7.848f, Z = 34.754f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -30.3f, Y = 6.0f, Z = 34.754f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -30.3f, Y = 4.152f, Z = 34.754f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -30.3f, Y = 2.304f, Z = 34.754f, Dx = 0.0f, Dy = -1.0f, Dz = 0.0f },
        new Beam { X = -34.197f, Y = 9.547f, Z = 30.856f, Dx = 0.5513f, Dy = -0.6262f, Dz = 0.5513f },
        new Beam { X = -33.084f, Y = 8.282f, Z = 31.97f, Dx = 0.5513f, Dy = -0.6262f, Dz = 0.5513f },
        new Beam { X = -31.97f, Y = 7.018f, Z = 33.084f, Dx = 0.5513f, Dy = -0.6262f, Dz = 0.5513f },
        new Beam { X = -30.856f, Y = 5.753f, Z = 34.197f, Dx = 0.5513f, Dy = -0.6262f, Dz = 0.5513f },
        new Beam { X = -30.856f, Y = 9.547f, Z = 34.197f, Dx = -0.5513f, Dy = -0.6262f, Dz = -0.5513f },
        new Beam { X = -31.97f, Y = 8.282f, Z = 33.084f, Dx = -0.5513f, Dy = -0.6262f, Dz = -0.5513f },
        new Beam { X = -33.084f, Y = 7.018f, Z = 31.97f, Dx = -0.5513f, Dy = -0.6262f, Dz = -0.5513f },
        new Beam { X = -34.197f, Y = 5.753f, Z = 30.856f, Dx = -0.5513f, Dy = -0.6262f, Dz = -0.5513f },
      },
    },
  };

  public static readonly RackItem[] Armoury = {
    new RackItem { Item = "AxeBronze", Note = "an axe, for trees", X = 0.0f, Z = 6.0f, Yaw = 180.0f },
    new RackItem { Item = "Club", Note = "a club, for creatures", X = 4.243f, Z = 4.243f, Yaw = 225.0f },
    new RackItem { Item = "Bow", Note = "a bow", X = 6.0f, Z = 0.0f, Yaw = 270.0f },
    new RackItem { Item = "ArrowWood", Note = "arrows for it", X = 4.243f, Z = -4.243f, Yaw = 315.0f },
    new RackItem { Item = "PickaxeBronze", Note = "a pickaxe, for rock", X = 0.0f, Z = -6.0f, Yaw = 0.0f },
    new RackItem { Item = "Hammer", Note = "a hammer, for building", X = -4.243f, Z = -4.243f, Yaw = 45.0f },
    new RackItem { Item = "Cultivator", Note = "a cultivator", X = -6.0f, Z = -0.0f, Yaw = 90.0f },
    new RackItem { Item = "Torch", Note = "a torch", X = -4.243f, Z = 4.243f, Yaw = 135.0f },
  };
}
