// <auto-generated>
//   Generated by tools/component-packets/generate_seam_catalog.py from the
//   assembly-derived atlas plus quest-capability-rules.json. Do not edit.
//
//   Source: assembly_valheim.dll (Steam client install, extracted 2026-08-07)
//   Atlas rows: 91; exact signatures: 90; method ids: 77.
// </auto-generated>

namespace ComfyQuestLab;

using System.Collections.Generic;

/// <summary>Exact atlas identities joined to stable creator-event policy.</summary>
public static class LabSeamCatalog {
  public struct Entry {
    public string SignatureId;
    public string MethodId;
    public string Category;
    public string AtlasCategories;
    public string Usability;
    public string CanonicalEvent;
    public string Route;
    public string Profile;
    public bool CreatorSafe;
    public string DedupeGroup;
    public string ActorScope;
  }

  static readonly Dictionary<string, Entry> _signatures = new Dictionary<string, Entry> {
    { "Character.AddStaggerDamage(float, Vector3, HitData)", new Entry { SignatureId = "Character.AddStaggerDamage(float, Vector3, HitData)", MethodId = "Character.AddStaggerDamage", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "character_staggered", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "character-staggered", ActorScope = "local-player-caused" } },
    { "Character.BlockAttack(HitData, Character)", new Entry { SignatureId = "Character.BlockAttack(HitData, Character)", MethodId = "Character.BlockAttack", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "attack_blocked", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "attack-blocked", ActorScope = "local-player" } },
    { "Character.Damage(HitData)", new Entry { SignatureId = "Character.Damage(HitData)", MethodId = "Character.Damage", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.ProducesEventNoTrigger, CanonicalEvent = "damage_dealt", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "character-damage", ActorScope = "local-player-caused" } },
    { "Character.Heal(float, bool)", new Entry { SignatureId = "Character.Heal(float, bool)", MethodId = "Character.Heal", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "character_healed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "character-healed", ActorScope = "local-player" } },
    { "Character.OnDeath()", new Entry { SignatureId = "Character.OnDeath()", MethodId = "Character.OnDeath", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.Today, CanonicalEvent = "kill", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "creature-killed", ActorScope = "local-player-caused" } },
    { "Character.RPC_Damage(long, HitData)", new Entry { SignatureId = "Character.RPC_Damage(long, HitData)", MethodId = "Character.RPC_Damage", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.ProducesEventNoTrigger, CanonicalEvent = "damage_dealt", Route = "alternate", Profile = "extended", CreatorSafe = true, DedupeGroup = "character-damage", ActorScope = "local-player-caused" } },
    { "Character.RPC_Heal(long, float, bool)", new Entry { SignatureId = "Character.RPC_Heal(long, float, bool)", MethodId = "Character.RPC_Heal", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "character_healed", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "character-healed", ActorScope = "local-player" } },
    { "Character.RPC_Stagger(long, Vector3)", new Entry { SignatureId = "Character.RPC_Stagger(long, Vector3)", MethodId = "Character.RPC_Stagger", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "character_staggered", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "character-staggered", ActorScope = "local-player-caused" } },
    { "Character.SetHealth(float)", new Entry { SignatureId = "Character.SetHealth(float)", MethodId = "Character.SetHealth", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "health_changed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "health-changed", ActorScope = "observed-character" } },
    { "Character.Stagger(Vector3)", new Entry { SignatureId = "Character.Stagger(Vector3)", MethodId = "Character.Stagger", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "character_staggered", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "character-staggered", ActorScope = "local-player-caused" } },
    { "Chat.OnNewChatMessage(GameObject, long, Vector3, Type, UserInfo, string)", new Entry { SignatureId = "Chat.OnNewChatMessage(GameObject, long, Vector3, Type, UserInfo, string)", MethodId = "Chat.OnNewChatMessage", Category = LabCategory.Social, AtlasCategories = "social", Usability = LabUsability.LabCandidate, CanonicalEvent = "chat_received", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "chat-received", ActorScope = "observed-player" } },
    { "Chat.RPC_ChatMessage(long, Vector3, int, UserInfo, string)", new Entry { SignatureId = "Chat.RPC_ChatMessage(long, Vector3, int, UserInfo, string)", MethodId = "Chat.RPC_ChatMessage", Category = LabCategory.Social, AtlasCategories = "social", Usability = LabUsability.LabCandidate, CanonicalEvent = "chat_received", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "chat-received", ActorScope = "observed-player" } },
    { "Chat.SendText(Type, string)", new Entry { SignatureId = "Chat.SendText(Type, string)", MethodId = "Chat.SendText", Category = LabCategory.Social, AtlasCategories = "social", Usability = LabUsability.LabCandidate, CanonicalEvent = "chat_sent", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "chat-sent", ActorScope = "local-player" } },
    { "Container.RPC_RequestTakeAll(long, long)", new Entry { SignatureId = "Container.RPC_RequestTakeAll(long, long)", MethodId = "Container.RPC_RequestTakeAll", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "container_emptied", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "container-take-all", ActorScope = "local-player" } },
    { "Container.TakeAll(Humanoid)", new Entry { SignatureId = "Container.TakeAll(Humanoid)", MethodId = "Container.TakeAll", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "container_emptied", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "container-take-all", ActorScope = "local-player" } },
    { "CookingStation.RPC_AddFuel(long)", new Entry { SignatureId = "CookingStation.RPC_AddFuel(long)", MethodId = "CookingStation.RPC_AddFuel", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_fuel_added", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "cooking-fuel-added", ActorScope = "local-player-caused" } },
    { "CookingStation.RPC_AddItem(long, string)", new Entry { SignatureId = "CookingStation.RPC_AddItem(long, string)", MethodId = "CookingStation.RPC_AddItem", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_input_added", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "cooking-input-added", ActorScope = "local-player-caused" } },
    { "CookingStation.RPC_RemoveDoneItem(long, Vector3, int)", new Entry { SignatureId = "CookingStation.RPC_RemoveDoneItem(long, Vector3, int)", MethodId = "CookingStation.RPC_RemoveDoneItem", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_output_collected", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "cooking-output-collected", ActorScope = "local-player-caused" } },
    { "Destructible.Damage(HitData)", new Entry { SignatureId = "Destructible.Damage(HitData)", MethodId = "Destructible.Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "Destructible.RPC_Damage(long, HitData)", new Entry { SignatureId = "Destructible.RPC_Damage(long, HitData)", MethodId = "Destructible.RPC_Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "alternate", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "Fermenter.RPC_AddItem(long, string)", new Entry { SignatureId = "Fermenter.RPC_AddItem(long, string)", MethodId = "Fermenter.RPC_AddItem", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_input_added", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "fermenter-input-added", ActorScope = "local-player-caused" } },
    { "Humanoid.BlockAttack(HitData, Character)", new Entry { SignatureId = "Humanoid.BlockAttack(HitData, Character)", MethodId = "Humanoid.BlockAttack", Category = LabCategory.Combat, AtlasCategories = "combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "attack_blocked", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "attack-blocked", ActorScope = "local-player" } },
    { "Humanoid.ConsumeItem(Inventory, ItemData, bool)", new Entry { SignatureId = "Humanoid.ConsumeItem(Inventory, ItemData, bool)", MethodId = "Humanoid.ConsumeItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_consumed", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "item-consumed", ActorScope = "local-player" } },
    { "Humanoid.DropItem(Inventory, ItemData, int)", new Entry { SignatureId = "Humanoid.DropItem(Inventory, ItemData, int)", MethodId = "Humanoid.DropItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_dropped", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "item-dropped", ActorScope = "local-player" } },
    { "Humanoid.EquipItem(ItemData, bool)", new Entry { SignatureId = "Humanoid.EquipItem(ItemData, bool)", MethodId = "Humanoid.EquipItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_equipped", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "item-equipped", ActorScope = "local-player" } },
    { "Humanoid.Pickup(GameObject, bool, bool)", new Entry { SignatureId = "Humanoid.Pickup(GameObject, bool, bool)", MethodId = "Humanoid.Pickup", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_picked_up", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "item-picked-up", ActorScope = "local-player" } },
    { "Humanoid.UnequipItem(ItemData, bool)", new Entry { SignatureId = "Humanoid.UnequipItem(ItemData, bool)", MethodId = "Humanoid.UnequipItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_unequipped", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "item-unequipped", ActorScope = "local-player" } },
    { "Inventory.AddItem(GameObject, int)", new Entry { SignatureId = "Inventory.AddItem(GameObject, int)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.AddItem(ItemData)", new Entry { SignatureId = "Inventory.AddItem(ItemData)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.AddItem(ItemData, Vector2i)", new Entry { SignatureId = "Inventory.AddItem(ItemData, Vector2i)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.AddItem(ItemData, int, int, int)", new Entry { SignatureId = "Inventory.AddItem(ItemData, int, int, int)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.AddItem(string, int, float, Vector2i, bool, int, int, long, string, Dictionary`2, int, bool)", new Entry { SignatureId = "Inventory.AddItem(string, int, float, Vector2i, bool, int, int, long, string, Dictionary`2, int, bool)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.AddItem(string, int, int, int, long, string, Vector2i, bool)", new Entry { SignatureId = "Inventory.AddItem(string, int, int, int, long, string, Vector2i, bool)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.AddItem(string, int, int, int, long, string, bool)", new Entry { SignatureId = "Inventory.AddItem(string, int, int, int, long, string, bool)", MethodId = "Inventory.AddItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_added", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-add", ActorScope = "local-player-inventory" } },
    { "Inventory.RemoveItem(ItemData)", new Entry { SignatureId = "Inventory.RemoveItem(ItemData)", MethodId = "Inventory.RemoveItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_removed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-remove", ActorScope = "local-player-inventory" } },
    { "Inventory.RemoveItem(ItemData, int)", new Entry { SignatureId = "Inventory.RemoveItem(ItemData, int)", MethodId = "Inventory.RemoveItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_removed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-remove", ActorScope = "local-player-inventory" } },
    { "Inventory.RemoveItem(int)", new Entry { SignatureId = "Inventory.RemoveItem(int)", MethodId = "Inventory.RemoveItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_removed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-remove", ActorScope = "local-player-inventory" } },
    { "Inventory.RemoveItem(string, int, int, bool)", new Entry { SignatureId = "Inventory.RemoveItem(string, int, int, bool)", MethodId = "Inventory.RemoveItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "inventory_item_removed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "inventory-remove", ActorScope = "local-player-inventory" } },
    { "InventoryGui.DoCrafting(Player)", new Entry { SignatureId = "InventoryGui.DoCrafting(Player)", MethodId = "InventoryGui.DoCrafting", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_crafted", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "item-crafted", ActorScope = "local-player" } },
    { "InventoryGui.OnCraftPressed()", new Entry { SignatureId = "InventoryGui.OnCraftPressed()", MethodId = "InventoryGui.OnCraftPressed", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_crafted", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "item-crafted", ActorScope = "local-player" } },
    { "ItemDrop.DropItem(ItemData, int, Vector3, Quaternion)", new Entry { SignatureId = "ItemDrop.DropItem(ItemData, int, Vector3, Quaternion)", MethodId = "ItemDrop.DropItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_dropped", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "item-dropped", ActorScope = "local-player" } },
    { "ItemDrop.Pickup(Humanoid)", new Entry { SignatureId = "ItemDrop.Pickup(Humanoid)", MethodId = "ItemDrop.Pickup", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_picked_up", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "item-picked-up", ActorScope = "local-player" } },
    { "ItemDrop.RPC_RequestOwn(long)", new Entry { SignatureId = "ItemDrop.RPC_RequestOwn(long)", MethodId = "ItemDrop.RPC_RequestOwn", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_picked_up", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "item-picked-up", ActorScope = "local-player" } },
    { "MineRock.Damage(HitData)", new Entry { SignatureId = "MineRock.Damage(HitData)", MethodId = "MineRock.Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "MineRock5.Damage(HitData)", new Entry { SignatureId = "MineRock5.Damage(HitData)", MethodId = "MineRock5.Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "MineRock5.RPC_Damage(long, HitData, int)", new Entry { SignatureId = "MineRock5.RPC_Damage(long, HitData, int)", MethodId = "MineRock5.RPC_Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "alternate", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "Pickable.Interact(Humanoid, bool, bool)", new Entry { SignatureId = "Pickable.Interact(Humanoid, bool, bool)", MethodId = "Pickable.Interact", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_picked", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "resource-picked", ActorScope = "local-player" } },
    { "Pickable.RPC_Pick(long, int)", new Entry { SignatureId = "Pickable.RPC_Pick(long, int)", MethodId = "Pickable.RPC_Pick", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_picked", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "resource-picked", ActorScope = "local-player" } },
    { "Pickable.RPC_SetPicked(long, bool)", new Entry { SignatureId = "Pickable.RPC_SetPicked(long, bool)", MethodId = "Pickable.RPC_SetPicked", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_pick_state_changed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "resource-pick-state", ActorScope = "observed-world" } },
    { "Pickable.SetPicked(bool)", new Entry { SignatureId = "Pickable.SetPicked(bool)", MethodId = "Pickable.SetPicked", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_pick_state_changed", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "resource-pick-state", ActorScope = "observed-world" } },
    { "Player.AddStamina(float)", new Entry { SignatureId = "Player.AddStamina(float)", MethodId = "Player.AddStamina", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "stamina_gained", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "stamina-gained", ActorScope = "local-player" } },
    { "Player.ConsumeItem(Inventory, ItemData, bool)", new Entry { SignatureId = "Player.ConsumeItem(Inventory, ItemData, bool)", MethodId = "Player.ConsumeItem", Category = LabCategory.Inventory, AtlasCategories = "inventory", Usability = LabUsability.LabCandidate, CanonicalEvent = "item_consumed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "item-consumed", ActorScope = "local-player" } },
    { "Player.OnDeath()", new Entry { SignatureId = "Player.OnDeath()", MethodId = "Player.OnDeath", Category = LabCategory.Progression, AtlasCategories = "progression|combat", Usability = LabUsability.LabCandidate, CanonicalEvent = "player_died", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "player-died", ActorScope = "local-player" } },
    { "Player.PlacePiece(Piece, Vector3, Quaternion, bool)", new Entry { SignatureId = "Player.PlacePiece(Piece, Vector3, Quaternion, bool)", MethodId = "Player.PlacePiece", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_placed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "piece-placed", ActorScope = "local-player" } },
    { "Player.RaiseSkill(SkillType, float)", new Entry { SignatureId = "Player.RaiseSkill(SkillType, float)", MethodId = "Player.RaiseSkill", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "skill_raised", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "skill-raised", ActorScope = "local-player" } },
    { "Player.RemovePiece()", new Entry { SignatureId = "Player.RemovePiece()", MethodId = "Player.RemovePiece", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_removed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "piece-removed", ActorScope = "local-player" } },
    { "Player.Repair(ItemData, Piece)", new Entry { SignatureId = "Player.Repair(ItemData, Piece)", MethodId = "Player.Repair", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_repaired", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "piece-repaired", ActorScope = "local-player" } },
    { "Player.SetMaxHealth(float, bool)", new Entry { SignatureId = "Player.SetMaxHealth(float, bool)", MethodId = "Player.SetMaxHealth", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "max_health_changed", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "max-health-changed", ActorScope = "local-player" } },
    { "Player.TeleportTo(Vector3, Quaternion, bool)", new Entry { SignatureId = "Player.TeleportTo(Vector3, Quaternion, bool)", MethodId = "Player.TeleportTo", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "player_teleported", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "player-teleported", ActorScope = "local-player" } },
    { "Player.UseStamina(float)", new Entry { SignatureId = "Player.UseStamina(float)", MethodId = "Player.UseStamina", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "stamina_spent", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "stamina-spent", ActorScope = "local-player" } },
    { "Sign.SetText(string)", new Entry { SignatureId = "Sign.SetText(string)", MethodId = "Sign.SetText", Category = LabCategory.Social, AtlasCategories = "social", Usability = LabUsability.LabCandidate, CanonicalEvent = "sign_written", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "sign-written", ActorScope = "local-player" } },
    { "Skills.CheatRaiseSkill(string, float, bool)", new Entry { SignatureId = "Skills.CheatRaiseSkill(string, float, bool)", MethodId = "Skills.CheatRaiseSkill", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "skill_cheat_used", Route = "suppressed", Profile = "disabled", CreatorSafe = false, DedupeGroup = "skill-cheat", ActorScope = "local-player" } },
    { "Skills.GetSkillLevel(SkillType)", new Entry { SignatureId = "Skills.GetSkillLevel(SkillType)", MethodId = "Skills.GetSkillLevel", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "skill_level_queried", Route = "suppressed", Profile = "disabled", CreatorSafe = false, DedupeGroup = "skill-query", ActorScope = "local-player" } },
    { "Skills.LowerAllSkills(float)", new Entry { SignatureId = "Skills.LowerAllSkills(float)", MethodId = "Skills.LowerAllSkills", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "skills_lowered", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "skills-lowered", ActorScope = "local-player" } },
    { "Skills.OnDeath()", new Entry { SignatureId = "Skills.OnDeath()", MethodId = "Skills.OnDeath", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "skills_lowered", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "skills-lowered", ActorScope = "local-player" } },
    { "Skills.RaiseSkill(SkillType, float)", new Entry { SignatureId = "Skills.RaiseSkill(SkillType, float)", MethodId = "Skills.RaiseSkill", Category = LabCategory.Progression, AtlasCategories = "progression", Usability = LabUsability.LabCandidate, CanonicalEvent = "skill_raised", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "skill-raised", ActorScope = "local-player" } },
    { "Smelter.OnAddFuel(Switch, Humanoid, ItemData)", new Entry { SignatureId = "Smelter.OnAddFuel(Switch, Humanoid, ItemData)", MethodId = "Smelter.OnAddFuel", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_fuel_added", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "smelter-fuel-added", ActorScope = "local-player" } },
    { "Smelter.OnAddOre(Switch, Humanoid, ItemData)", new Entry { SignatureId = "Smelter.OnAddOre(Switch, Humanoid, ItemData)", MethodId = "Smelter.OnAddOre", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_input_added", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "smelter-input-added", ActorScope = "local-player" } },
    { "Smelter.RPC_AddFuel(long)", new Entry { SignatureId = "Smelter.RPC_AddFuel(long)", MethodId = "Smelter.RPC_AddFuel", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_fuel_added", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "smelter-fuel-added", ActorScope = "local-player-caused" } },
    { "Smelter.RPC_AddOre(long, string)", new Entry { SignatureId = "Smelter.RPC_AddOre(long, string)", MethodId = "Smelter.RPC_AddOre", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_input_added", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "smelter-input-added", ActorScope = "local-player-caused" } },
    { "Smelter.Spawn(string, int)", new Entry { SignatureId = "Smelter.Spawn(string, int)", MethodId = "Smelter.Spawn", Category = LabCategory.Crafting, AtlasCategories = "crafting", Usability = LabUsability.LabCandidate, CanonicalEvent = "station_output_produced", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "station-output-produced", ActorScope = "observed-world" } },
    { "Talker.Say(Type, string)", new Entry { SignatureId = "Talker.Say(Type, string)", MethodId = "Talker.Say", Category = LabCategory.Social, AtlasCategories = "social", Usability = LabUsability.LabCandidate, CanonicalEvent = "speech_heard", Route = "diagnostic", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "speech-heard", ActorScope = "observed-character" } },
    { "TreeBase.Damage(HitData)", new Entry { SignatureId = "TreeBase.Damage(HitData)", MethodId = "TreeBase.Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "TreeBase.RPC_Damage(long, HitData)", new Entry { SignatureId = "TreeBase.RPC_Damage(long, HitData)", MethodId = "TreeBase.RPC_Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "alternate", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "TreeLog.Damage(HitData)", new Entry { SignatureId = "TreeLog.Damage(HitData)", MethodId = "TreeLog.Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "TreeLog.RPC_Damage(long, HitData)", new Entry { SignatureId = "TreeLog.RPC_Damage(long, HitData)", MethodId = "TreeLog.RPC_Damage", Category = LabCategory.Harvest, AtlasCategories = "harvest", Usability = LabUsability.LabCandidate, CanonicalEvent = "resource_damaged", Route = "alternate", Profile = "extended", CreatorSafe = true, DedupeGroup = "resource-damage", ActorScope = "local-player-caused" } },
    { "WearNTear.ApplyDamage(float, HitData)", new Entry { SignatureId = "WearNTear.ApplyDamage(float, HitData)", MethodId = "WearNTear.ApplyDamage", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_damaged", Route = "primary", Profile = "extended", CreatorSafe = true, DedupeGroup = "piece-damaged", ActorScope = "local-player-caused" } },
    { "WearNTear.Destroy(HitData, bool)", new Entry { SignatureId = "WearNTear.Destroy(HitData, bool)", MethodId = "WearNTear.Destroy", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_destroyed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "piece-destroyed", ActorScope = "local-player-caused" } },
    { "WearNTear.RPC_Remove(long, bool)", new Entry { SignatureId = "WearNTear.RPC_Remove(long, bool)", MethodId = "WearNTear.RPC_Remove", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_removed", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "piece-removed", ActorScope = "local-player-caused" } },
    { "WearNTear.RPC_Repair(long)", new Entry { SignatureId = "WearNTear.RPC_Repair(long)", MethodId = "WearNTear.RPC_Repair", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_repaired", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "piece-repaired", ActorScope = "local-player-caused" } },
    { "WearNTear.Remove(bool)", new Entry { SignatureId = "WearNTear.Remove(bool)", MethodId = "WearNTear.Remove", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_removed", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "piece-removed", ActorScope = "observed-world" } },
    { "WearNTear.Repair()", new Entry { SignatureId = "WearNTear.Repair()", MethodId = "WearNTear.Repair", Category = LabCategory.Building, AtlasCategories = "building", Usability = LabUsability.LabCandidate, CanonicalEvent = "piece_repaired", Route = "corroborating", Profile = "diagnostic", CreatorSafe = false, DedupeGroup = "piece-repaired", ActorScope = "observed-world" } },
    { "WorldGenerator.GetBiome(Vector3)", new Entry { SignatureId = "WorldGenerator.GetBiome(Vector3)", MethodId = "WorldGenerator.GetBiome", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "biome_queried", Route = "suppressed", Profile = "disabled", CreatorSafe = false, DedupeGroup = "biome-query", ActorScope = "world-query" } },
    { "WorldGenerator.GetBiome(float, float, float, bool)", new Entry { SignatureId = "WorldGenerator.GetBiome(float, float, float, bool)", MethodId = "WorldGenerator.GetBiome", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "biome_queried", Route = "suppressed", Profile = "disabled", CreatorSafe = false, DedupeGroup = "biome-query", ActorScope = "world-query" } },
    { "ZoneSystem.RPC_SetGlobalKey(long, string)", new Entry { SignatureId = "ZoneSystem.RPC_SetGlobalKey(long, string)", MethodId = "ZoneSystem.RPC_SetGlobalKey", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "global_key_set", Route = "alternate", Profile = "core", CreatorSafe = true, DedupeGroup = "global-key-set", ActorScope = "world-authority" } },
    { "ZoneSystem.RemoveGlobalKey(GlobalKeys)", new Entry { SignatureId = "ZoneSystem.RemoveGlobalKey(GlobalKeys)", MethodId = "ZoneSystem.RemoveGlobalKey", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "global_key_removed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "global-key-removed", ActorScope = "world-authority" } },
    { "ZoneSystem.RemoveGlobalKey(string)", new Entry { SignatureId = "ZoneSystem.RemoveGlobalKey(string)", MethodId = "ZoneSystem.RemoveGlobalKey", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "global_key_removed", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "global-key-removed", ActorScope = "world-authority" } },
    { "ZoneSystem.SetGlobalKey(GlobalKeys)", new Entry { SignatureId = "ZoneSystem.SetGlobalKey(GlobalKeys)", MethodId = "ZoneSystem.SetGlobalKey", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "global_key_set", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "global-key-set", ActorScope = "world-authority" } },
    { "ZoneSystem.SetGlobalKey(GlobalKeys, float)", new Entry { SignatureId = "ZoneSystem.SetGlobalKey(GlobalKeys, float)", MethodId = "ZoneSystem.SetGlobalKey", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "global_key_set", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "global-key-set", ActorScope = "world-authority" } },
    { "ZoneSystem.SetGlobalKey(string)", new Entry { SignatureId = "ZoneSystem.SetGlobalKey(string)", MethodId = "ZoneSystem.SetGlobalKey", Category = LabCategory.World, AtlasCategories = "world", Usability = LabUsability.LabCandidate, CanonicalEvent = "global_key_set", Route = "primary", Profile = "core", CreatorSafe = true, DedupeGroup = "global-key-set", ActorScope = "world-authority" } },
  };

  // Legacy patch calls name a method id. Resolve those to a deterministic exact
  // signature while new patches name the exact overload directly.
  static readonly Dictionary<string, string> _methodSignatures = new Dictionary<string, string> {
    { "Character.AddStaggerDamage", "Character.AddStaggerDamage(float, Vector3, HitData)" },
    { "Character.BlockAttack", "Character.BlockAttack(HitData, Character)" },
    { "Character.Damage", "Character.Damage(HitData)" },
    { "Character.Heal", "Character.Heal(float, bool)" },
    { "Character.OnDeath", "Character.OnDeath()" },
    { "Character.RPC_Damage", "Character.RPC_Damage(long, HitData)" },
    { "Character.RPC_Heal", "Character.RPC_Heal(long, float, bool)" },
    { "Character.RPC_Stagger", "Character.RPC_Stagger(long, Vector3)" },
    { "Character.SetHealth", "Character.SetHealth(float)" },
    { "Character.Stagger", "Character.Stagger(Vector3)" },
    { "Chat.OnNewChatMessage", "Chat.OnNewChatMessage(GameObject, long, Vector3, Type, UserInfo, string)" },
    { "Chat.RPC_ChatMessage", "Chat.RPC_ChatMessage(long, Vector3, int, UserInfo, string)" },
    { "Chat.SendText", "Chat.SendText(Type, string)" },
    { "Container.RPC_RequestTakeAll", "Container.RPC_RequestTakeAll(long, long)" },
    { "Container.TakeAll", "Container.TakeAll(Humanoid)" },
    { "CookingStation.RPC_AddFuel", "CookingStation.RPC_AddFuel(long)" },
    { "CookingStation.RPC_AddItem", "CookingStation.RPC_AddItem(long, string)" },
    { "CookingStation.RPC_RemoveDoneItem", "CookingStation.RPC_RemoveDoneItem(long, Vector3, int)" },
    { "Destructible.Damage", "Destructible.Damage(HitData)" },
    { "Destructible.RPC_Damage", "Destructible.RPC_Damage(long, HitData)" },
    { "Fermenter.RPC_AddItem", "Fermenter.RPC_AddItem(long, string)" },
    { "Humanoid.BlockAttack", "Humanoid.BlockAttack(HitData, Character)" },
    { "Humanoid.ConsumeItem", "Humanoid.ConsumeItem(Inventory, ItemData, bool)" },
    { "Humanoid.DropItem", "Humanoid.DropItem(Inventory, ItemData, int)" },
    { "Humanoid.EquipItem", "Humanoid.EquipItem(ItemData, bool)" },
    { "Humanoid.Pickup", "Humanoid.Pickup(GameObject, bool, bool)" },
    { "Humanoid.UnequipItem", "Humanoid.UnequipItem(ItemData, bool)" },
    { "Inventory.AddItem", "Inventory.AddItem(GameObject, int)" },
    { "Inventory.RemoveItem", "Inventory.RemoveItem(ItemData)" },
    { "InventoryGui.DoCrafting", "InventoryGui.DoCrafting(Player)" },
    { "InventoryGui.OnCraftPressed", "InventoryGui.OnCraftPressed()" },
    { "ItemDrop.DropItem", "ItemDrop.DropItem(ItemData, int, Vector3, Quaternion)" },
    { "ItemDrop.Pickup", "ItemDrop.Pickup(Humanoid)" },
    { "ItemDrop.RPC_RequestOwn", "ItemDrop.RPC_RequestOwn(long)" },
    { "MineRock.Damage", "MineRock.Damage(HitData)" },
    { "MineRock5.Damage", "MineRock5.Damage(HitData)" },
    { "MineRock5.RPC_Damage", "MineRock5.RPC_Damage(long, HitData, int)" },
    { "Pickable.Interact", "Pickable.Interact(Humanoid, bool, bool)" },
    { "Pickable.RPC_Pick", "Pickable.RPC_Pick(long, int)" },
    { "Pickable.RPC_SetPicked", "Pickable.RPC_SetPicked(long, bool)" },
    { "Pickable.SetPicked", "Pickable.SetPicked(bool)" },
    { "Player.AddStamina", "Player.AddStamina(float)" },
    { "Player.ConsumeItem", "Player.ConsumeItem(Inventory, ItemData, bool)" },
    { "Player.OnDeath", "Player.OnDeath()" },
    { "Player.PlacePiece", "Player.PlacePiece(Piece, Vector3, Quaternion, bool)" },
    { "Player.RaiseSkill", "Player.RaiseSkill(SkillType, float)" },
    { "Player.RemovePiece", "Player.RemovePiece()" },
    { "Player.Repair", "Player.Repair(ItemData, Piece)" },
    { "Player.SetMaxHealth", "Player.SetMaxHealth(float, bool)" },
    { "Player.TeleportTo", "Player.TeleportTo(Vector3, Quaternion, bool)" },
    { "Player.UseStamina", "Player.UseStamina(float)" },
    { "Sign.SetText", "Sign.SetText(string)" },
    { "Skills.CheatRaiseSkill", "Skills.CheatRaiseSkill(string, float, bool)" },
    { "Skills.GetSkillLevel", "Skills.GetSkillLevel(SkillType)" },
    { "Skills.LowerAllSkills", "Skills.LowerAllSkills(float)" },
    { "Skills.OnDeath", "Skills.OnDeath()" },
    { "Skills.RaiseSkill", "Skills.RaiseSkill(SkillType, float)" },
    { "Smelter.OnAddFuel", "Smelter.OnAddFuel(Switch, Humanoid, ItemData)" },
    { "Smelter.OnAddOre", "Smelter.OnAddOre(Switch, Humanoid, ItemData)" },
    { "Smelter.RPC_AddFuel", "Smelter.RPC_AddFuel(long)" },
    { "Smelter.RPC_AddOre", "Smelter.RPC_AddOre(long, string)" },
    { "Smelter.Spawn", "Smelter.Spawn(string, int)" },
    { "Talker.Say", "Talker.Say(Type, string)" },
    { "TreeBase.Damage", "TreeBase.Damage(HitData)" },
    { "TreeBase.RPC_Damage", "TreeBase.RPC_Damage(long, HitData)" },
    { "TreeLog.Damage", "TreeLog.Damage(HitData)" },
    { "TreeLog.RPC_Damage", "TreeLog.RPC_Damage(long, HitData)" },
    { "WearNTear.ApplyDamage", "WearNTear.ApplyDamage(float, HitData)" },
    { "WearNTear.Destroy", "WearNTear.Destroy(HitData, bool)" },
    { "WearNTear.RPC_Remove", "WearNTear.RPC_Remove(long, bool)" },
    { "WearNTear.RPC_Repair", "WearNTear.RPC_Repair(long)" },
    { "WearNTear.Remove", "WearNTear.Remove(bool)" },
    { "WearNTear.Repair", "WearNTear.Repair()" },
    { "WorldGenerator.GetBiome", "WorldGenerator.GetBiome(Vector3)" },
    { "ZoneSystem.RPC_SetGlobalKey", "ZoneSystem.RPC_SetGlobalKey(long, string)" },
    { "ZoneSystem.RemoveGlobalKey", "ZoneSystem.RemoveGlobalKey(GlobalKeys)" },
    { "ZoneSystem.SetGlobalKey", "ZoneSystem.SetGlobalKey(GlobalKeys)" },
  };

  public const int AtlasRowCount = 91;
  public static int Count { get { return _methodSignatures.Count; } }
  public static int SignatureCount { get { return _signatures.Count; } }
  public static int CreatorSafeSignatureCount { get { return 57; } }
  public const int CreatorSafeEventCount = 34;

  public static IEnumerable<string> AllSeamIds { get { return _methodSignatures.Keys; } }
  public static IEnumerable<string> AllSignatureIds { get { return _signatures.Keys; } }

  public static bool TryGet(string seamOrSignatureId, out Entry entry) {
    if (_signatures.TryGetValue(seamOrSignatureId, out entry)) {
      return true;
    }
    string signatureId;
    if (_methodSignatures.TryGetValue(seamOrSignatureId, out signatureId)) {
      return _signatures.TryGetValue(signatureId, out entry);
    }
    entry = default(Entry);
    return false;
  }

  public static string Usability(string seamOrSignatureId) {
    Entry entry;
    return TryGet(seamOrSignatureId, out entry) ? entry.Usability : LabUsability.LabCandidate;
  }

  public static string Category(string seamOrSignatureId) {
    Entry entry;
    return TryGet(seamOrSignatureId, out entry) ? entry.Category : LabCategory.Combat;
  }

  public static string CanonicalEvent(string seamOrSignatureId) {
    Entry entry;
    return TryGet(seamOrSignatureId, out entry) ? entry.CanonicalEvent : string.Empty;
  }

  public static int UsableTodayIn(string category) {
    int count = 0;
    foreach (string signatureId in _methodSignatures.Values) {
      Entry entry = _signatures[signatureId];
      if (entry.Category == category && entry.Usability == LabUsability.Today) {
        count++;
      }
    }
    return count;
  }

  public static int CountIn(string category) {
    int count = 0;
    foreach (string signatureId in _methodSignatures.Values) {
      if (_signatures[signatureId].Category == category) {
        count++;
      }
    }
    return count;
  }
}
