// <auto-generated>
//   Generated by tools/component-packets/generate_seam_catalog.py from
//   samples/valheim-event-atlas.json. Do not edit by hand: rerun the extractor
//   (--events) and then the generator, and commit both.
//
//   Source: assembly_valheim.dll (Steam client install, extracted 2026-08-07)
//   Seams: 77 across 8 categories.
// </auto-generated>

namespace ComfyQuestLab;

using System.Collections.Generic;

/// <summary>What the event atlas knows about each seam, compiled in.
///
/// A patch names the seam it hooked; this answers which category it belongs to and
/// whether a quest can fire on it. Keeping the verdict here rather than in each patch
/// file means regenerating the atlas updates the mod, instead of leaving ninety-one
/// hand-copied answers to rot.</summary>
public static class LabSeamCatalog {
  public struct Entry {
    public string Category;
    public string Usability;
  }

  static readonly Dictionary<string, Entry> _seams = new Dictionary<string, Entry> {
    { "Character.AddStaggerDamage", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Character.BlockAttack", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Character.Damage", new Entry { Category = LabCategory.Combat, Usability = LabUsability.ProducesEventNoTrigger } },
    { "Character.Heal", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Character.OnDeath", new Entry { Category = LabCategory.Combat, Usability = LabUsability.Today } },
    { "Character.RPC_Damage", new Entry { Category = LabCategory.Combat, Usability = LabUsability.ProducesEventNoTrigger } },
    { "Character.RPC_Heal", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Character.RPC_Stagger", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Character.SetHealth", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Character.Stagger", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Chat.OnNewChatMessage", new Entry { Category = LabCategory.Social, Usability = LabUsability.LabCandidate } },
    { "Chat.RPC_ChatMessage", new Entry { Category = LabCategory.Social, Usability = LabUsability.LabCandidate } },
    { "Chat.SendText", new Entry { Category = LabCategory.Social, Usability = LabUsability.LabCandidate } },
    { "Container.RPC_RequestTakeAll", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Container.TakeAll", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "CookingStation.RPC_AddFuel", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "CookingStation.RPC_AddItem", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "CookingStation.RPC_RemoveDoneItem", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Destructible.Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Destructible.RPC_Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Fermenter.RPC_AddItem", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Humanoid.BlockAttack", new Entry { Category = LabCategory.Combat, Usability = LabUsability.LabCandidate } },
    { "Humanoid.ConsumeItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Humanoid.DropItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Humanoid.EquipItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Humanoid.Pickup", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Humanoid.UnequipItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Inventory.AddItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Inventory.RemoveItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "InventoryGui.DoCrafting", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "InventoryGui.OnCraftPressed", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "ItemDrop.DropItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "ItemDrop.Pickup", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "ItemDrop.RPC_RequestOwn", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "MineRock.Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "MineRock5.Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "MineRock5.RPC_Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Pickable.Interact", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Pickable.RPC_Pick", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Pickable.RPC_SetPicked", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Pickable.SetPicked", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "Player.AddStamina", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Player.ConsumeItem", new Entry { Category = LabCategory.Inventory, Usability = LabUsability.LabCandidate } },
    { "Player.OnDeath", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Player.PlacePiece", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "Player.RaiseSkill", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Player.RemovePiece", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "Player.Repair", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "Player.SetMaxHealth", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Player.TeleportTo", new Entry { Category = LabCategory.World, Usability = LabUsability.LabCandidate } },
    { "Player.UseStamina", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Sign.SetText", new Entry { Category = LabCategory.Social, Usability = LabUsability.LabCandidate } },
    { "Skills.CheatRaiseSkill", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Skills.GetSkillLevel", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Skills.LowerAllSkills", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Skills.OnDeath", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Skills.RaiseSkill", new Entry { Category = LabCategory.Progression, Usability = LabUsability.LabCandidate } },
    { "Smelter.OnAddFuel", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Smelter.OnAddOre", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Smelter.RPC_AddFuel", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Smelter.RPC_AddOre", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Smelter.Spawn", new Entry { Category = LabCategory.Crafting, Usability = LabUsability.LabCandidate } },
    { "Talker.Say", new Entry { Category = LabCategory.Social, Usability = LabUsability.LabCandidate } },
    { "TreeBase.Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "TreeBase.RPC_Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "TreeLog.Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "TreeLog.RPC_Damage", new Entry { Category = LabCategory.Harvest, Usability = LabUsability.LabCandidate } },
    { "WearNTear.ApplyDamage", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "WearNTear.Destroy", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "WearNTear.RPC_Remove", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "WearNTear.RPC_Repair", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "WearNTear.Remove", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "WearNTear.Repair", new Entry { Category = LabCategory.Building, Usability = LabUsability.LabCandidate } },
    { "WorldGenerator.GetBiome", new Entry { Category = LabCategory.World, Usability = LabUsability.LabCandidate } },
    { "ZoneSystem.RPC_SetGlobalKey", new Entry { Category = LabCategory.World, Usability = LabUsability.LabCandidate } },
    { "ZoneSystem.RemoveGlobalKey", new Entry { Category = LabCategory.World, Usability = LabUsability.LabCandidate } },
    { "ZoneSystem.SetGlobalKey", new Entry { Category = LabCategory.World, Usability = LabUsability.LabCandidate } },
  };

  public static int Count { get { return _seams.Count; } }

  /// <summary>Every seam the atlas knows, whether or not this build hooks it.</summary>
  public static IEnumerable<string> AllSeamIds { get { return _seams.Keys; } }

  /// <summary>The honest answer for a seam id such as "TreeBase.Damage".
  /// An unknown id reads as lab-candidate: if the atlas has never heard of it, a
  /// quest certainly cannot fire on it.</summary>
  public static string Usability(string seamId) {
    Entry entry;
    return _seams.TryGetValue(seamId, out entry) ? entry.Usability : LabUsability.LabCandidate;
  }

  public static string Category(string seamId) {
    Entry entry;
    return _seams.TryGetValue(seamId, out entry) ? entry.Category : LabCategory.Combat;
  }

  /// <summary>How many seams in a category a quest can fire on today. The journal
  /// uses this to tell a builder where the useful ground is.</summary>
  public static int UsableTodayIn(string category) {
    int n = 0;
    foreach (KeyValuePair<string, Entry> pair in _seams) {
      if (pair.Value.Category == category && pair.Value.Usability == LabUsability.Today) {
        n++;
      }
    }
    return n;
  }

  public static int CountIn(string category) {
    int n = 0;
    foreach (KeyValuePair<string, Entry> pair in _seams) {
      if (pair.Value.Category == category) {
        n++;
      }
    }
    return n;
  }
}
